### ISSUE TITLE
[Feature Request] Support ControlNet inpainting model

### ISSUE THREAD

**Issue by catboxanon** [Bing-su/adetailer#1]
Feature request to support optional usage of the ControlNet inpainting model when this extension is enabled, as I believe this could improve results, especially at higher denoise values. More info here: https://github.com/Mikubill/sd-webui-controlnet/issues/968

This could be handled with the external code API: https://github.com/Mikubill/sd-webui-controlnet/wiki/API#external-code-api

**Comment by Bing-su** [comment]
This is a powerful idea that will take over my weekend. I'll look into it too.
