### ISSUE TITLE
Adetailer on by default?

### ISSUE THREAD

**Issue by jordanjay29** [Bing-su/adetailer#10]
Adetailer being on by default now means that I often miss the setting on my initial generation on a webui load. Not always so bad when using txt2img on a low batch count, but not good when using img2img on an image with many people. 

I've looked through the ui-config.json for an option to disable by default but cannot find it. This was not an issue when the default model was none. 

I would please request restoring adetailer being disabled by default, or add a None model selection so that it isn't triggering when undesired. Additionally, can you add an easily-identifiable (e.g. adetailer.py/XXX2img/Adetailer enabled: true) setting in ui-config.json or point out which one it is currently?

**Comment by Dddokter** [comment]
I would like to add onto this as it would be nice to have a option to choose to auto enable/disable in the settings menu for those that prefer one over the other.

**Comment by Bing-su** [comment]
I'm not sure why the checkbox selection isn't working, I've brought back the `None` option for now.

**Comment by wzgrx** [comment]
There are still issues with the latest version,
AttributeError: 'NoneType' object has no attribute 'to'
[Tiled Diffusion] ControlNet found, support is enabled.

**Comment by wzgrx** [comment]
Switch default on

**Comment by an303042** [comment]
I too support having it off by default, or have it save its last state.
Thanks!

**Comment by Bing-su** [comment]
It is off by default in the latest version. Try clearing all adetailer-related entries in your `ui-config.json`.

**Comment by jordanjay29** [comment]
The none option saves this situation from occurring again, thanks. I think this is solved on the latest versions.

**Comment by Bing-su** [comment]
Try clearing all adetailer-related entries in your ui-config.json.

**Comment by jordanjay29** [comment]
By removing the entire lines? Or just their values?

**Comment by Bing-su** [comment]
Whole line. Take care to ensure that the modified file is a valid JSON file.
