### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by xam0482** [Bing-su/adetailer#100]
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

version: [v1.3.0]•  python: 3.10.10  
•  torch: 2.0.1+cu118  
•  gradio: 3.32.0

**Comment by Bing-su** [comment]
https://stackoverflow.com/questions/75103127/getting-notimplementederror-could-not-run-torchvisionnms-with-arguments-fr
try reinstall torch and torchvision
