### ISSUE TITLE
[Request] Can we have "LEGS Model"

### ISSUE THREAD

**Issue by YKefasu** [Bing-su/adetailer#101]
idk its possible or not, but i want a gorgeous legs😅

**Comment by Bing-su** [comment]
I'll see if I can find a relevant dataset.

**Comment by andupotorac** [comment]
Would be amazing! Would turn those paws into actual child legs. 
![image](https://github.com/Bing-su/adetailer/assets/3269738/368fce6d-5b4d-43ed-a598-72f06c459c72)

**Comment by Bing-su** [comment]
I know the [human-part-segmentation dataset](https://paperswithcode.com/task/human-part-segmentation) exists, but I don't have a GPU available and I don't have the space to store the data too.
