### ISSUE TITLE
[Bug]:  2023-05-30 17:38:29 b'{"error":"HTTPException","detail":"Script \'After Detailer\' not found","body":"","errors":""}'

### ISSUE THREAD

**Issue by zzm88** [Bing-su/adetailer#105]
### Describe the bug

# version
adetailer version May30 ab3567aac63b3b26606c4d5b670b71723682bb5a
webui version May14 89f9faa63388756314e8a1d96cf86bf5e0663045

# what i got in response

2023-05-30 17:38:29 b'{"error":"HTTPException","detail":"Script \'After Detailer\' not found","body":"","errors":""}'

# how i called the script
`
  "alwayson_scripts": {
        
              "After Detailer": {
        "args": [
          {
            #   "ad_enable": True,
            "ad_model": "face_yolov8n.pt",
            "ad_prompt": '1girl',
            "ad_negative_prompt": "lowres, bad anatomy, bad hands, missing fingers, worst quality,low quality,(extra buttons) ,bad_prompt_version2:0.6",
            # "ad_controlnet_model": "control_v11p_sd15_openpose [cab727d4]",
            # "ad_controlnet_weight": 1
          }
        ]
      },
        "controlnet": {
...}
}
`

### Full console logs

```Shell
[-] ADetailer initialized. version: 23.6.0, num models: 8
```

**Comment by zzm88** [comment]
a rollback to 23.5.15 fixed it.

**Comment by Bing-su** [comment]
I apologise for the inconvenience. I changed a bunch of defaults this time and renamed the script as well. Could you please look at the [wiki](https://github.com/Bing-su/adetailer/wiki/API) again?
