### ISSUE TITLE
Help with reinstalling.

### ISSUE THREAD

**Issue by fadedninna** [Bing-su/adetailer#106]
I want to do a complete reinstall but I don't know which folders to delete!

**Comment by fadedninna** [comment]
I want to do a complete reinstall but I don't know which folders to delete!

**Comment by alenknight** [comment]
in your stablediffusion folder, there's an /extensions/adetailer/ folder.  delete the entire /adetailer/ folder.  
then just start SD... and go to extensions... and add again from web.  restart SD.
(do the delete while it's shut down)
