### ISSUE TITLE
Save the settings...

### ISSUE THREAD

**Issue by onegex1214** [Bing-su/adetailer#108]
It's extremely annoying to have to re-put all the settings in each tab each time, could there be a "save presets" button ? Pleeease. I love this extension.

Thanks a lot in advance.

**Comment by Bing-su** [comment]
Use the import from last gen button, png info, modify the `ui-config.json` file, or use [Config-Preset](https://github.com/Zyin055/Config-Presets) extension.

**Comment by onegex1214** [comment]
> Use the import from last gen button, png info, modify the `ui-config.json` file, or use [Config-Preset](https://github.com/Zyin055/Config-Presets) extension.

Issue is, that would take the entire settings. I would only like to save the Adetailer settings, and have'em load automatically.

**Comment by Zyin055** [comment]
Author of Config Presets here. @onegex1214 you can have a config preset that only targets the ADetailer fields with the update a few weeks ago.

**Comment by muunkky** [comment]
I don't understand this at all. I think saving presets is pretty standard, like controlnet and tileddiffusion.
