### ISSUE TITLE
Request help😔

### ISSUE THREAD

**Issue by aimarxjg** [Bing-su/adetailer#11]
"Thank you very much for your sharing. Could you please provide details on how to use it? I installed the plugin and launched it in T2IMG or IMAG2IMG, but the red facial detection box did not appear on the image. Thank you."

**Comment by spldmanager** [comment]
I have some request, don’t know how to setup adetailer prompt,how to use controlnet tab and other configurations

**Comment by aimarxjg** [comment]
> 我有一些要求，不知道如何设置细节提示，如何使用 controlnet 选项卡和其他配置

Let me help you. After installing the plugin, you can see it under SEED. It is enabled by default, so remember to turn off this feature when not in use. Then, if you need to see the red face detection box, you need to find the plugin in SD settings and enable this feature. Reboot will take effect. At this point, you will generate two identical images in the folder, one of which has a red box on its face. (Universal for all modes)

The specific method of this plugin is to select 1 model (8S OR 8N) in the "ADetailer model", check "Use inpaint width/height", and it will use the 512X512 set on the left to repair damaged faces (with a specified resolution). The "ControlNet model" below can be redrawn using CON by directly selecting the unique CON V11p sd15 INPAINT. This function works well in T2IMG and IMG2IMG. Sorry for my poor English, good luck to you
