### ISSUE TITLE
[Feature Request] Integrate Prompt S/R from xyz_grid script

### ISSUE THREAD

**Issue by bilwis** [Bing-su/adetailer#112]
I'm not sure whether this is the right place to ask, or whether it would need a change in how the xyz_grid.py script works, but it would be nice if replacing parts of the prompt for ADetailer worked with the xyz_grid script.

As a use case example, I have a model custom trained on different people and like to run XYZ grids on them where all the people are inserted via Prompt S/R. ADetailer has been an absolutely great addition to my workflow because I don't have to go and inpaint all "low resolution" faces manually, but even with "Apply only selected scripts to ADetailer" disabled, the Prompt S/R doesn't work on the ADetailer script, so it will "detail" all the faces in the grid with the first person.

Although reading #62, it seems like the ADetailer prompt is entirely different to the main prompt, so I assume this wouldn't be possible/easy? And even if ADetailer integrated into the xyz_grid script "on its own" (which would also be great), it wouldn't work "simultaneously" (i.e. on the same grid axis) as the main prompt S/R, I assume?

Maybe there's another way to achieve this?

Regardless of whether it's possible, thanks for your consideration and the amazing work with this extension!

**Comment by andupotorac** [comment]
Did you try using wildcards?
