### ISSUE TITLE
[Feature Request]: Show all outputs (before, mask, result) within webui output viewer.

### ISSUE THREAD

**Issue by vidiotgameboss** [Bing-su/adetailer#113]
**Is your feature request related to a problem? Please describe.**
Having to go to the image folder and using up space to save masks and before pictures. It takes additional seconds going through all the masks and before photos and takes unnecessary disk space.

**Describe the solution you'd like**
Simply show the before adetailer and the mask in the output viewer within webui along with the final result that normally shows.

**Describe alternatives you've considered**
Possibly not by default (should be imo, good for seeing the changes and seeing what it detects and what it does not) but at least make it a toggleable option within settings.

**Additional context**
Here's to visualize it:
![poor visualization](https://github.com/Bing-su/adetailer/assets/63921540/82b6cea5-b3ce-4b51-805d-d698aaa4ac2b)

**Comment by Bing-su** [comment]
It's possible, but I don't want to do it, as I think it will cause problems when used with other extensions.

**Comment by andupotorac** [comment]
> 

Yes there is another way. I use this https://breadboard.me/ and I've set the folders for inpainting to also collect there in the gallery. So for each ADetailer job I have the before, the masks, and the after. Like this:
<img width="856" alt="Screenshot 2023-06-14 at 00 12 21" src="https://github.com/Bing-su/adetailer/assets/3269738/8643d98b-0c79-4dd7-b24f-2fd5b484c4da">
