### ISSUE TITLE
[Feature Request] Using different lora for each face detected

### ISSUE THREAD

**Issue by Gh20221205** [Bing-su/adetailer#115]
**Is your feature request related to a problem? Please describe.**
AD is wonderful except when it comes to group picture where all faces will look the same.
**Describe the solution you'd like**
I hope there is a way to use different lora for each face detected. I'm not sure how the prompt is executed in AD. If it's executed once for each face, then maybe adding support for wildcards or dynamic prompt can solve this. At that time, we can save a list of lora to a txt file named lora.txt, and put `__lora__` in prompt which will be replaced with a lora from lora.txt during execution.
**Describe alternatives you've considered**
Using wildcards or dynamic prompt is just my thought. There should be other ways to have this implemented.
**Additional context**

**Comment by Bing-su** [comment]
Yes. As you say, adetailer applies inpaints for each detected object, with wildcards and dynamic prompts applied to them as well.

**Comment by Gh20221205** [comment]
Awesome!

**Comment by pixelass** [comment]
I'm not sure how this was resolved without a solution. While ADetailer does apply dynamic prompts etc. it will generate the same face for any person in a picture. 

A dynamic prompt will be applied as is to each masked portion. (which could even change a gender in the detailing process)

I would like to see a different seed per masked are or something else that helps generate diverse faces if there is more than one person in the picture.


@Bing-su thank you for your thoughts on this.

**Comment by pixelass** [comment]
some examples of gender changes

![image](https://github.com/Bing-su/adetailer/assets/1148334/117083c6-588a-4140-b07d-a2557beb7627)

![image](https://github.com/Bing-su/adetailer/assets/1148334/d22672f5-b3aa-4eae-8739-e29f0bcf7f19)

![image](https://github.com/Bing-su/adetailer/assets/1148334/3239cdaf-42e4-43f5-ae60-19babbe2a4b6)
