### ISSUE TITLE
Scaling size before downscale

### ISSUE THREAD

**Issue by ema7569** [Bing-su/adetailer#116]
I'm sure of nothing, it's just a question. 

From what I understand your mod upscale the part, then draw it on upscaled internal image then downscale it and draw it on the source image? If this is the case, it is possible to chose the upscale size? 

By example, I draw a face in 512x512 image and I ask adetailer to draw the face to an upscaled 2048x2048 image before returning to 512x512. Currently it seem just upscaling by x2 and the difference of adetailer is not very visible on very detailed source.

**Comment by Bing-su** [comment]
Is using separate height, width options not enough?

**Comment by ema7569** [comment]
Hahaha nice.... ok thank!!
