### ISSUE TITLE
[Feature Request] Add option to not run adetailer with Tilled Diffusion

### ISSUE THREAD

**Issue by Zotikus1001** [Bing-su/adetailer#117]
I use Tilled Diffusion alot,
As it stands, Tilled Diffusion will be used for img2img, then used again on the adetailer phase.
And it really sucks that adetailer will run with Tilled Diffusion.

I'd like to img2img with Tilled Diffusion, then let adetailer do it's thing normally without it.

**Comment by Bing-su** [comment]
It is possible to make adetailer not use any extension, but it is not possible to make a specific extension not use adetailer.
