### ISSUE TITLE
[Question] Is it possible to inpaint a face from an existing image to a generation

### ISSUE THREAD

**Issue by MordechaiHadad** [Bing-su/adetailer#12]
Basically what the title says, I want to generate a completely new generation with completely different features but I want a face from existing images I have to this new generation.

Side note I suggest you enable the discussions tab since this question doesn't really belong in issues

**Comment by Bing-su** [comment]
Is this something like #5?

How about a button that is only visible in the img2img tab, and when checked, adds the mask that the model has detected?

**Comment by MordechaiHadad** [comment]
@Bing-su not exactly it seems like the other guy just trying to refine faces or something? what I am trying to do is let's say I generate an image in txt2img I then move it to inpaint or img2img and take an existing image with the face I want on the the image I just generated

I tried doing something like enable this, and then enable control net tab and in it use the inpaint model but it just gave a weird result

**Comment by MordechaiHadad** [comment]
Basically if I could tldr it; copy x face to y head
