### ISSUE TITLE
[Feature Request]: Is there a way to remove objects from the image using adetailer?

### ISSUE THREAD

**Issue by rbychn** [Bing-su/adetailer#122]
Can we use some of the models that https://github.com/Sanster/lama-cleaner uses and have the option to remove certain areas from the image based on our own trained YOLO models? i.e. detect objects that we want to remove using our model and then use the boxes, in paint (erase) using one of those models for every generation using adetailer?

**Comment by Bing-su** [comment]
You can get a similar result by increasing the denoising strength to 1.0 and inputting the proper prompts. Try adjusting the dilation and mask blur values as well if needed.

**Comment by rbychn** [comment]
Is there a way to use this https://github.com/Mikubill/sd-webui-controlnet/discussions/1597 to remove items using adetailer? what would the workflow be?
