### ISSUE TITLE
[Bug]: Adetailer produces black images when used alongside ToMe.

### ISSUE THREAD

**Issue by vidiotgameboss** [Bing-su/adetailer#123]
### Describe the bug

1. Enable ToMe.
2. Generate once with adetailer
3. Try generating again. You will notice that depending on merge ratio, seed and model, the entire image outputs or masks are now black until the model is reloaded without ToMe being enabled.

### Full console logs

```Shell
None + Not entirely reproductible.
```

### List of installed extensions

adetailer
ToMe
controlnet

a bunch of irrelevant ones

**Comment by Bing-su** [comment]
1. What is ToMe?
2. Even if there are no errors, please post the entire console log.

**Comment by vidiotgameboss** [comment]
> 1. What is ToMe?

ToMe is [Token Merging](https://github.com/dbolya/tomesd) that a lot of people use, it by default is enabled on the high res pass only in webuis but some people have it enabled always.

> 2. Even if there are no errors, please post the entire console log.

It is not entirely reproductible unless using certain settings with certain seeds/models, I spoke more on it on [vlad](https://github.com/vladmandic/automatic/issues/1307). 

I believe it may have to do with ToMe optimizations being possibly applied to every model loaded (example in this case being the yolo/image detection models and controlnet models) which in turn starts producing either full black images, or black image masks (the mask inpaint turns entirely black). I imagine that upscaling models like LDSR would behave similar. 

Therefore it may be best to make sure these optimizations are disabled for these models.

**Comment by vidiotgameboss** [comment]
Fixed black image/NaN issues by turning on crossattention upcast and enabling tf32 and tf16 math ops.

**Comment by derekcbr** [comment]
> Fixed black image/NaN issues by turning on crossattention upcast and enabling tf32 and tf16 math ops.

Can not find the option automatic1111 settings. Can you clarify?
