### ISSUE TITLE
[Feature Request]: Adetailer with reference only (control network)

### ISSUE THREAD

**Issue by alien2327** [Bing-su/adetailer#127]
### Is your feature request related to a problem? Please describe.

Hi, recently I used Adetailer for my art work and I really impressed of this extention performance.

I also use reference only which is one of the great tool of control network, which is used for generating same character every run.

Adetailer has also control network function, but I feel that when detailing/fixing face, the generated face slightly (sometimes very) differece from what I expected.

### Describe the solution you'd like

So my idea is that, there is already control network in Adetailer, adding reference only for fixing face which is same at reference face image.

**Comment by Bing-su** [comment]
reference only처럼 전처리 모듈만 있는 추가하려면 입력으로 받아야 하는게 늘어나는데, 너무 번잡해져서 하고 싶지 않습니다. 컨트롤넷에 업로드한 이미지를 다시 참조하는건 지금 webui구조에서 굉장히 힘듭니다.

대신에, 프롬프트와 파라미터 조정으로 이 문제를 해결하는걸 좀 더 시도해봐주셨으면 좋겠습니다. 전 여전히 프롬프트만으로 이런 문제를 해결할 수 있다고 보고 있습니다.

**Comment by alien2327** [comment]
@Bing-su 
답변 감사합니다.
확실히 reference only 같은 기타 기능을 추가하게되면 지금처럼 심플하게 작동하기는 어렵겠네요.
말씀하신대로 프롬프트 부분에서 조금 더 궁리를 해봐야겠습니다.
