### ISSUE TITLE
(Inpainting) Output image always return the input one without changes

### ISSUE THREAD

**Issue by nnbt4** [Bing-su/adetailer#128]
I don't know if I'm missing something, but in inpainting my output image always returns the input one without the changes. 
The thing is, I see the change on the preview (though it stops nearly at 50% on the UI, but it does go to 100% on the terminal) and it doesn't even register it in my output folder. 
I have no errors on my terminal, I have tried different settings, different optimizations, live preview settings, different images, tried to disable all extensions...

BUT it works in text2img. I'm missing something for Inpainting?

**Comment by Raivshard** [comment]
I have the same issue. It's very frustrating
