### ISSUE TITLE
[Feature Request]: Allow per-face prompt inputs

### ISSUE THREAD

**Issue by entmike** [Bing-su/adetailer#131]
### Describe the solution you'd like

AfterDetailer works great!  It would be nice to be able to pass an array of text prompts for use cases where there is more than one face, but you do not want both faces to use the same prompt.

### Describe alternatives you've considered

Inpainting per-face is an alternative but it is a manual process versus the convenience of this addon.

**Comment by mistersquirrle** [comment]
Is this what you're looking for? https://github.com/Bing-su/adetailer/wiki/Advanced
You can use " [SEP] " and provide prompts for each found/processed face, though there's not a way to specifically say which applies to which. You can however change the processing order in the settings to Left -> Right, so it's consistent.
For example, here's handling 4+ faces:
`smiling, excited, hazel eyes, detailed eyes [SEP] shy, mouth closed, freckles, blue eyes, detailed eyes, earring [SEP] a woman with red eyes, looking away from viewer, embarrassed, detailed eyes [SEP] a woman with grey eyes, looking away from viewer, embarrassed, detailed eyes`

**Comment by entmike** [comment]
Thanks for the tip!!  I think this will work for my use case.  Is there a way to skip a face in the event I need to swap LORAs/Checkpoints and want to run it through a 2nd pass with different params?
