### ISSUE TITLE
[Feature Request]:  YOLO Face segmentation models?

### ISSUE THREAD

**Issue by mandal-rahul** [Bing-su/adetailer#139]
### Is your feature request related to a problem? Please describe.

It would be nice to have yolo segmentation models along with the detection models.

**Comment by Bing-su** [comment]
To my surprise, it was hard to find a dataset that only segmented faces, and there was no anime face dataset, so I didn't try.

Instead, try the `mediapipe_face_mesh` model. For non-anime figures, it should do what you want.
