### ISSUE TITLE
Can not work properly with controlnet

### ISSUE THREAD

**Issue by spldmanager** [Bing-su/adetailer#14]
I tried to use this + controlnet openpose to produce batchs of images ,but i found only the first image could be controlled by controlnet model, others were random poses.
I'm using controlnet 1.125  with model sd15_openpose

**Comment by Dawgmastah** [comment]
Noticed this as well, a workaround is to use batch size and not batch count, all will have the correct controlnet pose

**Comment by Bing-su** [comment]
What error messages do you see in the terminal?

**Comment by spldmanager** [comment]
> Noticed this as well, a workaround is to use batch size and not batch count, all will have the correct controlnet pose

15G vram will easily oom if using highres.fix and controlnet at same time with batch size more than 2

**Comment by spldmanager** [comment]
> What error messages do you see in the terminal?

no error message found, just can not
