### ISSUE TITLE
[Feature Request]: Apply different prompts for multiple faces

### ISSUE THREAD

**Issue by rackSD** [Bing-su/adetailer#147]
### Describe the solution you'd like

Is it possible to implement a feature to use different prompts for each face? Currently there is only one prompt that will be applied to all faces in the image. For example, Face 1 would be `green eyes, smiling`, and face 2 would be `red eyes, frown`.

Being able to auto inpaint different coloured eyes and facial expressions in one image would be great.

Thank you for this amazing extension.

**Comment by Bing-su** [comment]
Extensions like wildcards are applied to ad_prompt.
