### ISSUE TITLE
[Feature Request] Option to save image before applying adetailer

### ISSUE THREAD

**Issue by Kaiten10** [Bing-su/adetailer#15]
As the title says, would be great to have a setting similar to 'Settings>Image Settings>Save a copy of image before doing face restoration'.

When enabled, it will save a copy before applying the face restoration.
This is good for comparisons, especially in batch processing.
I'm aware of the 'save mask previews' setting, but it would be great to also have an option for it spit out a clean image for comparison.

Thanks!

**Comment by Bing-su** [comment]
I've added this feature, thanks.
