### ISSUE TITLE
[Feature Request]: allow set default value of settings

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#156]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bing-su/adetailer/assets/167966/bda4b7be-c81c-4264-bbad-6e9eae5b7943)

**Comment by Darkenlord1** [comment]
also it would be great to add settings to ui-config.json, like all default parameters (sampler, width/height all tumblers etc), or point it out if i just didnt found them

**Comment by Mistborn-First-Era** [comment]
I would like to second this request. I like to keep the "inpaint->Use seperate steps" checked off as well as lower the "ADetailer steps" a bit. I'll take a look around the files and see if I can figure it out
