### ISSUE TITLE
[Feature Request]: More than 2 model steps

### ISSUE THREAD

**Issue by kazuninishiki** [Bing-su/adetailer#157]
### Is your feature request related to a problem? Please describe.

Currently we are bound to have 2 sets of models running in sequential order which is great.  I'd love to have more than 2, the purpose is to run three different Adetailer model (The sequence I'd like to run with is: Person, then Face, then Hands.

**Comment by Bing-su** [comment]
![Cap 2023-06-26 09-46-24-701](https://github.com/Bing-su/adetailer/assets/37621276/cdfbd7cb-73b6-4cc8-b052-d8b5082a8008)
You already have that option.
