### ISSUE TITLE
[Bug]: create unusual photos

### ISSUE THREAD

**Issue by tranthai2k2** [Bing-su/adetailer#160]
### Describe the bug

i tried it on colab version of nocrypt and between the perfect images sometimes there are abnormal images created at first i think it's because lora after deleting lora the results still appear similar images
Here are some interspersed images I made

### Full console logs

```Shell
Version 2
```

**Comment by smstarrant** [comment]
I just did some testing and it seems to be an interaction with  sd-webui-neutral-prompt (https://github.com/ljleb/sd-webui-neutral-prompt.git).  Verified by disabling all extensions other that Adetailer and neutral prompt.  Also have to have batch count _and_ batch size greater than 1.
