### ISSUE TITLE
[Question] Outgoing Traffic  to google cloud servers on each use of Adetailer

### ISSUE THREAD

**Issue by neojam** [Bing-su/adetailer#163]
Why does Adetailer contact google cloud severs every time its used (via python.exe) ?
Any way to disable it?

IPs it tries to connect:
142.250.186.46
142.250.184.206
216.58.212.142
etc

I find it strange, because out of all my installed atomatic1111 extensions, Adetailer is the only one that does that.

**Comment by Bing-su** [comment]
It's going to communicate with the huggingface hub every time it starts up.

**Comment by Bing-su** [comment]
That part is in the adetailer code, and compares the detection model uploaded to huggingface with the model file you have locally. 

Since adetailer uses unsafe pickle load, I used this method for the integrity of the file.

**Comment by neojam** [comment]
That method seem to be questionable, since Adetailer still works (uses the local models anyway) when it can't access the internet to do the integrity-check of the models.

Why not provide safe model hashes with the adetailer code and do the check offline? 
Seem to be better than running models without any integrity check at all.

**Comment by thulle** [comment]
I found the --ad-no-huggingface startup flag during a network outage, it cut the startup time from 10+ minutes of waiting for timeouts connecting to huggingface to the regular 40 seconds.

**Comment by intoempty** [comment]
So in the meantime, perhaps just remove the remote check? I have to disable all python network activity when using adetailer because I don't like seeing all the traffic.
