### ISSUE TITLE
[Feature Request]: can i adjust order between hires.fix and adetailer

### ISSUE THREAD

**Issue by Zekiee** [Bing-su/adetailer#166]
### Is your feature request related to a problem? Please describe.

When I use txt2img, I will also use hires.fix. now I using adetailer, It seems adetailer is done in the end.

### Describe the solution you'd like

now the order is 
txtimg --> hires.fix --> adetailer.

I want to adjust order between hires.fix and adetailer, make it like 
txtimg  --> adetailer --> hires.fix

**Comment by Bing-su** [comment]
This seems simple but it's a task that will require rebuilding this project, sorry.

**Comment by tetsuoo-online** [comment]
I thought about that too, the alternative for me is to first make a good txt2img generation with ADetailer, then send that to img2img with TileDiffusion and TileControlNet. You could even add ADetailer again in that second process

**Comment by Zekiee** [comment]
> I thought about that too, the alternative for me is to first make a good txt2img generation with ADetailer, then send that to img2img with Tiled Diffusion and Tile ControlNet. You could even add ADetailer on top of it again

Thanks, Use img2imt and set Denoising strength near zero number can Approach what i need

**Comment by Zekiee** [comment]
> This seems simple but it's a task that will require rebuilding this project, sorry.

 I see, Thanks
