### ISSUE TITLE
[Question/Request] Apply face detailer and hand detailer at the same time?

### ISSUE THREAD

**Issue by hohohoman** [Bing-su/adetailer#17]
Would applying face detailer and hand detailer at the same time possible in one go using automatic1111?

**Comment by Bing-su** [comment]
It's possible. I think it would be nice to apply two models at the same time.

**Comment by 3305458q** [comment]
> It's possible. I think it would be nice to apply two models at the same time.

Can you tell me how to turn them on at the same time?

**Comment by 3305458q** [comment]
I figured out how. Just copy the adetailer folder inside the neural network client (specifically, in the extensions folder)

**Comment by Bing-su** [comment]
It's now really possible
