### ISSUE TITLE
[Feature Request]: Use adetailer in other frameworks

### ISSUE THREAD

**Issue by DearFloyd** [Bing-su/adetailer#170]
How can it be used under another framework, such as diffusers. I am using diffusers pipeline instead of webui for image generation. Can you give me some tips on how to add adetailer to diffusers pipeline? Thanks!

**Comment by philz1337** [comment]
Yes would be great

**Comment by Simi-pri** [comment]
This is an essential request for developers.

**Comment by Simi-pri** [comment]
For developers, this request holds great significance.

**Comment by Bing-su** [comment]
see: https://github.com/Bing-su/asdff

**Comment by wly-ai-bj** [comment]
> https://github.com/Bing-su/asdff

I have tried to use asdff, but it did not work for me. 

For example, I want to repair hand, but i get a person in the position of hand.

The pipeline I used was AdPipeline.
