### ISSUE TITLE
[Feature Request]: Lock the enabled state when Restart WebUI

### ISSUE THREAD

**Issue by petercham** [Bing-su/adetailer#175]
### Is your feature request related to a problem? Please describe.

1. Lock the enabled state of the plug-in when restarting the WebUI. 
2. When calling APIs such as t2i and i2i, you can call the configuration of the plug-in

### Describe the solution you'd like

You can refer to this plug-in：
https://github.com/hako-mikan/sd-webui-lora-block-weight.git

The Active State is locked。And when calling the T2i and I2i API, the configuration can be automatically called

**Comment by Bing-su** [comment]
Automatic1111's webui supports the feature to change setting defaults via the `ui-config.json` file, which also includes extensions.

I've written the entries in the `ui-config.json` file created by the adetailer in the [wiki](https://github.com/Bing-su/adetailer/wiki/ui-config.json), so please change the values you need.

**Comment by XiangjiBU** [comment]
> Automatic1111's webui supports the feature to change setting defaults via the `ui-config.json` file, which also includes extensions.
> 
> I've written the entries in the `ui-config.json` file created by the adetailer in the [wiki](https://github.com/Bing-su/adetailer/wiki/ui-config.json), so please change the values you need.

I changed ui-config.json, the state locked when use web ui, but it not work as API (start by --nowebui)
