### ISSUE TITLE
[Bug]: Changing the detection model while an image is generating applies to that generation

### ISSUE THREAD

**Issue by brknsoul** [Bing-su/adetailer#180]
### Describe the bug

I've clicked Generate, and my detection model is on mediapipe_full.
If, while that generation is running, I change the detection model to hand_yolov8n.pt, this change will apply to the currently running generation and start detecting hands, instead of faces.

I believe after hitting Generate, all settings should be 'locked in'.

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

Python 3.10.11 on Windows
Version: https://github.com/vladmandic/automatic/commit/0d3092c29279edb73b7bdca37872e5cb1c16852d Fri Jun 30 17:22:42 2023 -0400
Using DirectML Backend
Torch 2.0.0+cpu
Torch backend: DirectML (torch-directml 0.2.0.dev230426)
Torch detected GPU: AMD Radeon RX 6600 XT

https://github.com/vladmandic/automatic

### List of installed extensions

*Built-ins:*
a1111-sd-webui-lycoris
clip-interrogator-ext
LDSR
ScuNET
sd-dynamic-thresholding,
sd-extension-system-info
sd-webui-agent-scheduler
sd-webui-controlnet
seed_travel
stable-diffusion-webui-images-browser
SwinIR

a1111-sd-webui-tagcomplete
adetailer
Config-Presets
put extensions here.txt,
sd-dynamic-prompts
sd-webui-aspect-ratio-helper
stable-diffusion-webui-state
stable-diffusion-webui-two-shot
Styles-Editor

**Comment by Bing-su** [comment]
I see, fix it soon.
