### ISSUE TITLE
[Bug]: Wildcard prompts

### ISSUE THREAD

**Issue by endlessvn2604** [Bing-su/adetailer#192]
### Describe the bug

I use a wildcard in the main prompt and put a heavy weight, while leaving the ADetailer(AD) prompts empty. This will allow the main prompts to be reused in AD. 
It appears that AD using a random unit in the wildcard, rather than the random unit in the main prompt, that causes two values to be different and breaks the face (I'm using face yolo), and AD won't use Wildcard itself.
Additionally, for example, when I tried to include "(sweat)" in the main prompt and add other elements in the AD's prompt without mentioning "(sweat)", the generated image always have no sweat. Or anyone have trick that always keep the main prompt? I tried to reduce denoise, change AD's parameters and controlnet weight but no help...

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
no log
```

**Comment by Bing-su** [comment]
There was a mistake in applying the prompt. It should work as you intended. Please update ADetailer.

> Additionally, for example, when I tried to include "(sweat)" in the main prompt and add other elements in the AD's prompt without mentioning "(sweat)", the generated image always have no sweat.

This is the correct behavior.

**Comment by endlessvn2604** [comment]
Thanks for  your answer!

**Comment by endlessvn2604** [comment]
> There was a mistake in applying the prompt. It should work as you intended. Please update ADetailer.
> 
> > Additionally, for example, when I tried to include "(sweat)" in the main prompt and add other elements in the AD's prompt without mentioning "(sweat)", the generated image always have no sweat.
> 
> This is the correct behavior.


Thanks for your answer!
