### ISSUE TITLE
Api endpoints would be super awesome

### ISSUE THREAD

**Issue by webcoderz** [Bing-su/adetailer#197]
### Is your feature request related to a problem? Please describe.

This is a very useful tool , however most of my workflow is with the api, making some api endpoints to send a image to a detailer with required parameters would be super clutch

**Comment by Bing-su** [comment]
??

**Comment by webcoderz** [comment]
Fastapi endpoints available from the stable diffusion web ui api

**Comment by webcoderz** [comment]
should look pretty similar to rembg api here: https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/blob/master/scripts/api.py ,its pretty easy,  if you handle this side i will get the clientside into the sd-webui-api

**Comment by Bing-su** [comment]
So you're saying you need more api features than just putting `ADetailer` in `alwayson_scripts` and sending it?

**Comment by webcoderz** [comment]
no , just expose these methods as endpoints from the sd web ui --api as well as just UI [https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/wiki/API

**Comment by webcoderz** [comment]
Ha interesting, so I would basically just put this in as a payload like here in the always_on scripts param? https://github.com/mix1009/sdwebuiapi#lora-and-alwayson_scripts-example

**Comment by webcoderz** [comment]
this worked great thanks for showing me!

**Comment by Bing-su** [comment]
Thanks!
