### ISSUE TITLE
[Bug]: 컨트롤넷 모델을 사용할 경우 얼굴이 이상해질때가 있습니다.

### ISSUE THREAD

**Issue by DDaDaDak** [Bing-su/adetailer#198]
### Describe the bug

컨트롤넷 모델을 사용하면 얼굴 보정이 이상하게 될때가 있습니다.
예전에는 잘 됐었는데 최근에 갑자기 발생하기 시작한거 같습니다.
얼굴 크기가 안맞아서 턱이 짤린다거나
각도가 안맞아서 이마가 엄청 넓어진다거나 하는 식
컨트롤넷 모델 안쓰면 문제가 없습니다.
컨트롤넷 문제인지 A디테일러 문제인지 솔직히 잘 모르겠습니다.

아래는 증상 예시 이미지 링크입니다.
https://drive.google.com/file/d/1gHGBEW9gLe5Hn8DFyNUn0fCBuUlAMMTJ/view?usp=sharing
https://drive.google.com/file/d/1tl2-zwbuDag6vhU-_fqRG_a2-c15R6kv/view?usp=sharing
https://drive.google.com/file/d/10Yau4_T1dLj4y45GwMQZ9Z1obopgLzEe/view?usp=sharing
https://drive.google.com/file/d/1R5qF_-N3ZJWkvy_DbuGKnDe5Sc6eRIUX/view?usp=sharing

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
venv "H:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements

Launching Web UI with arguments: --xformers --autolaunch --lyco-dir=./models/Lora
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: H:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
[-] ADetailer initialized. version: 23.7.5, num models: 14
2023-07-10 12:53:34,617 - ControlNet - INFO - ControlNet v1.1.232
ControlNet preprocessor location: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-10 12:53:34,677 - ControlNet - INFO - ControlNet v1.1.232
```

**Comment by Bing-su** [comment]
보내주신 정보로는 뭐가 문제인지 알 수 없습니다. 지금도 denoising strength를 높이면 온갖 이상한 사진들을 만들어 낼 수 있습니다.

**Comment by DDaDaDak** [comment]
아 이미지에 EXIF만 냅두고 따로 적진 않았네요.

Steps: 50
Sampler: DPM++ 2M SDE Karras
CFG scale: 25
Seed: 2433437795
Size: 512x768
Model hash: 1fe2e88721
Model: sxhnxMIX-fp16-no_ema
Denoising strength: 0.4
RNG: CPU
ADetailer model: face_yolov8n.pt
ADetailer prompt: "(__random smile__:1.3), __random face__, best quality, ultra highres, ultra realistic, __random light__, extremely detailed, delicate skin texture, Korean beauty, black eyes, looking at viewer"
ADetailer negative prompt: "AS-Adult-neg, (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, monochrome, long lashes, mole"
ADetailer confidence: 0.7
ADetailer mask min ratio: 0.005, ADetailer dilate/erode: 4
ADetailer mask blur: 10
ADetailer denoising strength: 0.5
ADetailer inpaint only masked: True
ADetailer inpaint padding: 32
ADetailer use separate CFG scale: True
ADetailer CFG scale: 5.0
ADetailer ControlNet model: control_v11p_sd15_openpose_fp16 [73c2b67d]
ADetailer version: 23.7.5
Hires upscale: 2
Hires steps: 15
Hires upscaler: 4xBox
Lora hashes: "Jav_Remu_S_v1.5: 122818188ceb"
Dynamic thresholding enabled: True
Mimic scale: 9
Threshold percentile: 99.95
Mimic mode: Half Cosine Up
Mimic scale minimum: 5
CFG mode: Cosine Up
CFG scale minimum: 5, ControlNet 0: "preprocessor: openpose_full, model: control_v11p_sd15_openpose_fp16 [73c2b67d], weight: 1.0, starting/ending: (0.0, 1.0), resize mode: ResizeMode.INNER_FIT, pixel perfect: True, control mode: ControlMode.BALANCED, preprocessor params: (-1, -1, -1)"
Version: v1.4.0

**Comment by DDaDaDak** [comment]
> 보내주신 정보로는 뭐가 문제인지 알 수 없습니다. 지금도 denoising strength를 높이면 온갖 이상한 사진들을 만들어 낼 수 있습니다.

아 이미지에 EXIF만 냅두고 따로 적진 않았네요.

Steps: 50
Sampler: DPM++ 2M SDE Karras
CFG scale: 25
Seed: 2433437795
Size: 512x768
Model hash: 1fe2e88721
Model: sxhnxMIX-fp16-no_ema
Denoising strength: 0.4
RNG: CPU
ADetailer model: face_yolov8n.pt
ADetailer prompt: "(random smile:1.3), random face, best quality, ultra highres, ultra realistic, random light, extremely detailed, delicate skin texture, Korean beauty, black eyes, looking at viewer"
ADetailer negative prompt: "AS-Adult-neg, (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, monochrome, long lashes, mole"
ADetailer confidence: 0.7
ADetailer mask min ratio: 0.005, ADetailer dilate/erode: 4
ADetailer mask blur: 10
ADetailer denoising strength: 0.5
ADetailer inpaint only masked: True
ADetailer inpaint padding: 32
ADetailer use separate CFG scale: True
ADetailer CFG scale: 5.0
ADetailer ControlNet model: control_v11p_sd15_openpose_fp16 [73c2b67d]
ADetailer version: 23.7.5
Hires upscale: 2
Hires steps: 15
Hires upscaler: 4xBox
Lora hashes: "Jav_Remu_S_v1.5: 122818188ceb"
Dynamic thresholding enabled: True
Mimic scale: 9
Threshold percentile: 99.95
Mimic mode: Half Cosine Up
Mimic scale minimum: 5
CFG mode: Cosine Up
CFG scale minimum: 5, ControlNet 0: "preprocessor: openpose_full, model: control_v11p_sd15_openpose_fp16 [73c2b67d], weight: 1.0, starting/ending: (0.0, 1.0), resize mode: ResizeMode.INNER_FIT, pixel perfect: True, control mode: ControlMode.BALANCED, preprocessor params: (-1, -1, -1)"
Version: v1.4.0

**Comment by Bing-su** [comment]
제가 해봤을 땐 딱히 이상한 점이 없네요
