### ISSUE TITLE
[Feature Request]: a similar repo for diffusers users

### ISSUE THREAD

**Issue by alexblattner** [Bing-su/adetailer#199]
### Is your feature request related to a problem? Please describe.

I think that the A111 webui has a lot of bloat and prefer using the diffusers library. I also would like to use this extension, but am unsure how considering how big this is.

### Describe the solution you'd like

a new repo independent from A1111 that offers built in functions to use stuff. I just want to use this with huggingface's diffusers library.

### Describe alternatives you've considered

doing this myself.

### Additional context

I'm ready to pay for this if you want

**Comment by alexblattner** [comment]
@Bing-su I'll donate to you for this

**Comment by Bing-su** [comment]
Please don't. I need to get a job anyway. I think it might be better to wait until SDXL is released.

**Comment by alexblattner** [comment]
@Bing-su could you help me understand your code so I can do it myself at least?

**Comment by JemiloII** [comment]
i would appreciate this as well.

**Comment by Bing-su** [comment]
see: https://github.com/Bing-su/asdff

**Comment by JemiloII** [comment]
Thanks a bunch @Bing-su
