### ISSUE TITLE
Adetailer hanging on basic attempt

### ISSUE THREAD

**Issue by GuruVirus** [Bing-su/adetailer#20]
I have the latest version of SD and Adetailer.
I can't get it to run properly.
I restarted the webUI, restarted SD.
I enabled both settings for saving copies of mask and before-Adetailer.

I am using the default settings of SD.
SD Prompt: person (doesn't matter what I choose)
Adetailer prompt: face
Model: 8n (doesn't matter which I choose)
Adetailer enabled, doesn't matter what other settings (I have also tried checking Use Inpaint Width/height).
I get to 95%:
![image](https://user-images.githubusercontent.com/4285187/236521586-6e5bc9c2-219b-4007-90fa-fa712d7a895e.png)
In my console I have this (typically the middle bar shows as 95%, same as WebUI image above):
![image](https://user-images.githubusercontent.com/4285187/236521906-092ed8bf-70fc-45c0-a252-968c8e86d87f.png)
When I Ctrl + C to kill it, I get:
`Interrupted with signal 2 in <frame at 0x000001FFA0CE89B0, file 'c:\\webui\\webui.py', line 266, code wait_on_server>`

**Comment by 3305458q** [comment]
Yes! I have the same!
But i can use mediapipe. Yolo dosn't work.

**Comment by cosmicoxytocin** [comment]
> 

Interesting 🤔 
If mediapipe works and yolo doesn't try typing `pip show ultralytics`
And see what comes back. If nothing:
`pip install ultralytics`
This will install the latest version of ultralytics (needed for Yolo). v.8.0.87 is recommend in the install script but I've been using the latest version (8.0.92) with no issues, python 3.10

**Comment by 3305458q** [comment]
> > 
> 
> Interesting 🤔 If mediapipe works and yolo doesn't try typing `pip show ultralytics` And see what comes back. If nothing: `pip install ultralytics` This will install the latest version of ultralytics (needed for Yolo). v.8.0.87 is recommend in the install script but I've been using the latest version (8.0.92) with no issues, python 3.10

When I read your answer, I immediately installed. Then enter the command to check. This is what it shows (first screenshot).

![image](https://user-images.githubusercontent.com/132700603/236572253-2b329acd-e490-48b2-ad3c-88a2287474a6.png)

But Yolo still doesn't seem to turn on. Progress stops at 98%

![image](https://user-images.githubusercontent.com/132700603/236572661-5b0ca54b-e088-4745-969e-f4829c42b486.png)
![image](https://user-images.githubusercontent.com/132700603/236572716-a5201060-02ba-4389-b0e1-1b598662d104.png)

**Comment by Bing-su** [comment]
This is actually the same issue as your #8 issue. I've put off when this happens.
And I still don't know anything about it, sorry.

**Comment by Bing-su** [comment]
This only happens if you are a Windows user, have webui installed just below your C drive, and are not running as administrator.

**Comment by 3305458q** [comment]
I solved the problem. First, you have to use the pip install ultralytics command.
Second, you have to completely re-download webui into a new folder. Then download adetailer through the tab (as usual). Then controlnet. After this it works for me.

**Comment by Bing-su** [comment]
This issue will be fixed in the next release of `ultralytics`. Thanks.
