### ISSUE TITLE
[Feature Request]: Limit to one person and exclude grid

### ISSUE THREAD

**Issue by ema7569** [Bing-su/adetailer#200]
### Is your feature request related to a problem? Please describe.

Hello, 

after testing your extension what I find as improvement is an option to exclude grid from the adetailer process. because I not use grid and adetailer take long time to process them for nothing.

The second point is an option to limit the adetailer to work just on n characters. Principally the one that has the most large area. I think it's not really necessary to launch adetailer on all background random characters.

The last thing is to move the option to create a backup before processing on the main tab, where the generate button is, instead of settings tab.

And thank, your extension is really a diamond

**Comment by Bing-su** [comment]
1. if the grid is included in the processing, that's a bug.
2. I apologize for the lack of explanation. Try using `Mask min/max ratio` or the sorting options in the settings tab.

**Comment by ema7569** [comment]
I limited the options model to 1 and the sort area large to small but the inpaint process continue to inpaint thing like the painting on walls. The problem to do that manually is we not see the rectangles and need multiple retry. If you can, add a checkbox to inpaint just the first largest detected rectangle.

**Comment by Bing-su** [comment]
3. Try Quicksettings list
![Cap 2023-07-14 14-04-34-662](https://github.com/Bing-su/adetailer/assets/37621276/ae412f01-a0b5-4934-ad04-d184f3b37db0)

Consider using sort and `[SEP]`: https://github.com/Bing-su/adetailer/wiki/Advanced
