### ISSUE TITLE
[Bug]: adetailer not work when running as api (--nowebui)

### ISSUE THREAD

**Issue by XiangjiBU** [Bing-su/adetailer#201]
### Describe the bug

when I run stable-diffusion-webui using "python launch --nowebui" to use it as api,  adetailer not works.

Besides I already change value=True in ui.py , but it still not works
ad_enable = gr.Checkbox(
    label="Enable ADetailer",
    value=True,
    visible=True,
    elem_id=eid("ad_enable"),

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
python 3.10.6, running with stable-diffusion-webui using "python launch --nowebui"
```

**Comment by XiangjiBU** [comment]
I set true in ui-config.json 
"customscript/!adetailer.py/txt2img/Enable ADetailer/visible": true,

but still not work when use --nowebui

**Comment by le-khang** [comment]
Hi XiangjiBU is your After Detailer extension working right now with normal configuration (not running as api)? And which version is it? My v23.7.5 version isn't working. I have installed v23.5.19 which is released over 1 month ago and it doesn't work too.
![2023-07-13 07_47_28-Stable Diffusion](https://github.com/Bing-su/adetailer/assets/35536989/3f93fa58-a518-4fcf-84a8-314966a34f06)
![2023-07-13 07_40_42-adetailer - JupyterLab](https://github.com/Bing-su/adetailer/assets/35536989/fa1cff26-e9f7-4729-ad63-05ed1566b5f6)

**Comment by Bing-su** [comment]
The `ui-config.json` file is not used when requesting via the API. Same goes for other extensions. Instead, include `alwayson_scripts` in your request.
