### ISSUE TITLE
[Feature Request]: Choosing a different sampling method for ADetailer pass.

### ISSUE THREAD

**Issue by magpie514** [Bing-su/adetailer#206]
### Is your feature request related to a problem? Please describe.

Lately, I've been using sd-webui's feature of allowing changing sampling method for the hires step, using Euler A for the low-res step and 2M Karras for the hires step.

This method turns out to give pretty good results. But then I noticed the ADetailer step started to make faces look worse and hallucinating random details like fingers. It seems it is using the same sampling method as the low res step?

### Describe the solution you'd like

In this situation it'd be useful to allow selecting a different sampler from the Gradio widget, allowing using ancestral samplers for the low-res step and finish it up with non-ancestral ones like 2M Karras so it doesn't alter the finishing touches in undesirable ways.

**Comment by Bing-su** [comment]
I'll try it

**Comment by magpie514** [comment]
Thank you!

**Comment by magpie514** [comment]
Updated and tried the feature. Works entirely as expected, thank you so much for implementing it so quickly!
I'll close this request as it's a solved issue now.
