### ISSUE TITLE
[Feature Request]: support controlref controlnet preprocessor method

### ISSUE THREAD

**Issue by tip0un3** [Bing-su/adetailer#207]
Hello,

Is it possible to add ControlRef support? This ControlNet model is very powerful and allows you to achieve new things.

If it's not possible, is there an option to obtain the mask of an image? I'd like to use your mask templates for image batches.

Thanks in advance.

**Comment by Bing-su** [comment]
I can't find a controlnet model named ControlRef, is this an alias for something or is it privately deployed?

![Cap 2023-07-15 12-20-10-063](https://github.com/Bing-su/adetailer/assets/37621276/a8f23432-64ce-4efb-a945-0d3d85a1c3dc)
Try these options on `Saving images/grids`

**Comment by tip0un3** [comment]
> I can't find a controlnet model named ControlRef, is this an alias for something or is it privately deployed?

Ah yes indeed. I misspoke. I think its integration must be more complicated then. It's not a ControlNet model but a layer used as a preprocessor.

You can find a discussion on this subject here :
https://github.com/Mikubill/sd-webui-controlnet/discussions/1236

This preprocessor produces an image similar to a reference image. This is very effective for transferring styles or obtaining something close to a source image. It's like a "mini Lora".

Thanks for the options, I'll give it a try.
