### ISSUE TITLE
Yolo doesn't work

### ISSUE THREAD

**Issue by 3305458q** [Bing-su/adetailer#21]
Yolo dosn't work, but i can use mediapipe. 
Progress stops at 98%, and the progress in the interface just freezes.
![image](https://user-images.githubusercontent.com/132700603/236584022-cd99d0c0-10d4-4e60-a53c-f3e3e60b5a6b.png)
![image](https://user-images.githubusercontent.com/132700603/236584031-7330a188-dcd7-4175-ba19-a6dd313f99d9.png)

I also have ultralytics

![image](https://user-images.githubusercontent.com/132700603/236584057-ef4d9fc2-32ca-4dfe-8d92-70f456dd84f7.png)

But then again, mediapipe works as it should - it runs at the end of generation and improves the picture.
Whats wrong?

**Comment by Bing-su** [comment]
This is actually the same issue as #8. I've put off when this happens.
And I still don't know anything about it, sorry.

**Comment by Bing-su** [comment]
This only happens if you are a Windows user, have webui installed just below your C drive, and are not running as administrator.

**Comment by 3305458q** [comment]
I solved the problem. First, you have to use the `pip install ultralytics command`.
Second, you have to completely re-download webui into a new folder. Then download adetailer through the tab (as usual). Then controlnet. After this it works for me.
