### ISSUE TITLE
[Feature Request]:   How to use the api that comes with webui to call adetailer

### ISSUE THREAD

**Issue by baifagg** [Bing-su/adetailer#214]
### Is your feature request related to a problem? Please describe.

How to use the api that comes with webui to call adetailer, I need to be able to set adetailer on and off, use facial repair, set positive and negative prompts for facial repair, etc.
![image](https://github.com/Bing-su/adetailer/assets/51266591/02da9cb7-ce1a-44e7-9e38-111a8ac815b2)

**Comment by Bing-su** [comment]
Send a request to  `/sdapi/v1/txt2img` or `/sdapi/v1/img2img` with the title and args of the script you want in `alwayson_scripts` entry.

**Comment by baifagg** [comment]
Thanks ,you're great

**Comment by sumin7928** [comment]
How should I put it in alwayson_scripts? I would be grateful if you could give me an example.
