### ISSUE TITLE
[Feature Request]: Face/Subject alignment?

### ISSUE THREAD

**Issue by dchatel** [Bing-su/adetailer#215]
### Is your feature request related to a problem? Please describe.

Do you think it is possible to get face/subject alignment without too much work with the current implementation?

Sometimes, you can or want to produce an image where the face is either sideways or up-side-down, for example. SD is usually not very good at producing decent results in such setups.

**Comment by Bing-su** [comment]
Maybe try something like [sd-face-editor](https://github.com/ototadana/sd-face-editor)?
