### ISSUE TITLE
[Bug]: using ControlNet generates low quality image with artefacts and "wet" like look

### ISSUE THREAD

**Issue by dilectiogames** [Bing-su/adetailer#216]
### Describe the bug

With no control net works fine. with controlnet it creates a low quality inpaint of the face with "oiled" "wet" skin, the hair is blotchy.

example with control net:

https://i.imgur.com/yEHcip1.png

example with no control net. hair is ok, face is like it should

https://i.imgur.com/PCkUuf7.png

Want to add that it worked perfectly before updating, maybe one or two weeks ago I've did the previous update for all extensions (which worked)

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
no errors
```

### List of installed extensions

adetailer 	https://github.com/Bing-su/adetailer 	main 	a1032d89 	Tue Jun 20 14:38:19 2023
sd-webui-controlnet 	https://github.com/Mikubill/sd-webui-controlnet.git 	main 	098f6cd8 	Tue Jul 18 05:06:14 2023
sd-webui-lora-block-weight 	https://github.com/hako-mikan/sd-webui-lora-block-weight.git 	main 	58eebb45 	Fri Jul 14 10:36:49 2023

**Comment by Bing-su** [comment]
This happens when the face takes up a large percentage of the photo. Find the appropriate parameters. This is not a bug.

**Comment by dilectiogames** [comment]
No, this is not correct, I've generated images with higher face size with no problem. It worked fine till I've updated controlnet this week. Probably control net changed something and broke the inpaint You can check similar images I've generated where it worked fine at this link.

https://civitai.com/user/dilectiogames/images

for example this image is using Controlnet Version: v1.4.0 and ADetailer version: 23.6.3

https://civitai.com/images/1425265?period=AllTime&periodMode=published&sort=Newest&view=feed&username=dilectiogames&withTags=true

but this one is using controlnet Version: v1.4.1 and same ADetailer version: 23.6.3 and has the issue

https://civitai.com/images/1601542?period=AllTime&periodMode=published&sort=Newest&view=feed&username=dilectiogames&withTags=true

**Comment by dilectiogames** [comment]
after more investigations I've found out that the issue is not present on controlnet  v1.1.231 but shows up in the recent versions

at controlnet they said they have changed the API maybe this can help. I've posted there an example side by side :)

https://github.com/Mikubill/sd-webui-controlnet/issues/1802#issuecomment-1642851381
