### ISSUE TITLE
[Feature Request]: We trained a new face detection model (maybe better?)

### ISSUE THREAD

**Issue by narugo1992** [Bing-su/adetailer#220]
### Is your feature request related to a problem? Please describe.

Here: https://huggingface.co/deepghs/anime_face_detection

And this is the online demo: https://huggingface.co/spaces/deepghs/anime_object_detection

But only for anime faces.

### Describe the solution you'd like

Maybe add an option of it 😄

**Comment by Bing-su** [comment]
Thank you for your hard work. Put them in the `webui/models/adetailer` folder and you should be able to use them. In my opinion, the performance of the detection model is not important for this project.
