### ISSUE TITLE
[Bug]: Failed to load ADetailer version: 23.7.8

### ISSUE THREAD

**Issue by michaeltran33** [Bing-su/adetailer#221]
### Describe the bug

Failed to load ADetailer version: 23.7.8.
load webui-user. Error on console as below.

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --xformers --disable-safe-unpickle --disable-nan-check --api --no-half-vae
[-] ADetailer initialized. version: 23.7.8, num models: 9
*** Error loading script: ddetailer.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
        from mmdet.core import get_classes
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
        from .bbox import *  # noqa: F401, F403
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
        from .samplers import (BaseSampler, CombinedSampler,
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
        from .score_hlr_sampler import ScoreHLRSampler
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
        from mmcv.ops import nms_match
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
        from .active_rotated_filter import active_rotated_filter
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
        ext_module = ext_loader.load_ext(
      File "D:\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
        ext = importlib.import_module('mmcv.' + name)
      File "C:\Python\Python312\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

---
2023-07-21 08:33:59,017 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-21 08:33:59,081 - ControlNet - INFO - ControlNet v1.1.233
2023-07-21 08:33:59,237 - roop - INFO - roop v0.0.2
2023-07-21 08:33:59,238 - roop - INFO - roop v0.0.2
Loading weights [792175a39f] from D:\stable-diffusion-webui\models\Stable-diffusion\ace_s.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
load Sadtalker Checkpoints from D:\stable-diffusion-webui\extensions\SadTalker\checkpoints
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\stable-diffusion-webui\models\VAE\kl-f8-anime2.ckpt
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(33): 512speedpainter, advntr, aid291, an6, AS-YoungerV2, AS-YoungestV2, AS-YoungV2-neg, bad-hands-5, bad_prompt_version2-neg, badv5, charturner, charturnerv2, CLASSICSTYLE, Clutter-Home, Clutter-Mechanical, corneo_nipple_rings, CRN1.2-neg, deformityv6, EasyNegative, evreka15, kidbooks, kkw-medieval, MAXFIELDPARRISH, negative_hand-neg, NegfeetV2, ng_deepnegative_v1_75t, quimbystyle, rzvice15, southofthebordersd15, Style-Renaissance, style-sylvamagic, tangbohu-buff, verybadimagenegative_v1.3
Model loaded in 2.8s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 0.4s, apply half(): 0.2s, load VAE: 0.2s, move model to device: 1.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.0s (import torch: 1.8s, import gradio: 0.4s, import ldm: 0.2s, other imports: 0.5s, setup codeformer: 0.1s, load scripts: 4.5s, create ui: 4.2s, gradio launch: 0.2s).
preload_extensions_git_metadata for 33 extensions took 1.69s
```

### List of installed extensions

<html>
<body>

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
OneButtonPrompt | https://github.com/AIrjen/OneButtonPrompt | main | f3164248 | Tue Jul 18 18:43:32 2023 | unknown
SD-CN-Animation | https://github.com/volotat/SD-CN-Animation.git | main | 2e257bbf | Tue May 30 16:49:03 2023 | unknown
SD-WebUI-BatchCheckpointPrompt | https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt | main | aeb3d75a | Mon Jun 19 21:22:38 2023 | unknown
SadTalker | https://github.com/OpenTalker/SadTalker.git | main | ae0b2635 | Mon Jul 3 05:48:35 2023 | unknown
a1111-mini-paint | https://github.com/0Tick/a1111-mini-paint | main | 038d5731 | Wed May 24 21:31:35 2023 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | 8e97bf54 | Sun Jul 9 07:44:58 2023 | unknown
adetailer | https://github.com/Bing-su/adetailer.git | main | b040a628 | Thu Jul 20 02:01:32 2023 | unknown
canvas-zoom | https://github.com/richrobber2/canvas-zoom.git | main | 88350430 | Thu Jul 20 21:40:35 2023 | unknown
ddetailer | https://github.com/dustysys/ddetailer.git | master | 22a17414 | Mon Nov 28 09:33:31 2022 | unknown
openpose-editor | https://github.com/fkunn1326/openpose-editor.git | master | d74fdd72 | Tue May 2 09:49:03 2023 | unknown
sd-dynamic-thresholding | https://github.com/mcmonkeyprojects/sd-dynamic-thresholding | master | 27700fdd | Mon Jul 17 02:11:02 2023 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 098f6cd8 | Tue Jul 18 05:06:14 2023 | unknown
sd-webui-inpaint-anything | https://github.com/Uminosachi/sd-webui-inpaint-anything.git | main | 6f5d4746 | Fri Jun 9 07:05:00 2023 | unknown
sd-webui-mov2mov | https://github.com/Scholar01/sd-webui-mov2mov | master | 0ba11a1a | Wed Apr 19 08:44:24 2023 | unknown
sd-webui-roop | https://github.com/s0md3v/sd-webui-roop | main | e6333fbe | Fri Jul 7 09:22:59 2023 | unknown
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything.git | master | 780fc495 | Tue Jun 13 12:11:35 2023 | unknown
sd-webui-supermerger | https://github.com/hako-mikan/sd-webui-supermerger.git | main | 7398bd8d | Tue May 23 15:57:48 2023 | unknown
sd-webui-text2video | https://github.com/kabachuha/sd-webui-text2video.git | main | 8f0af8c9 | Fri Jul 14 12:41:05 2023 | unknown
sd-webui-xldemo-txt2img | https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img.git | main | e193c1c1 | Mon Jul 17 00:58:40 2023 | unknown
sd_dreambooth_extension | https://github.com/d8ahazard/sd_dreambooth_extension | main | 926ae204 | Fri Mar 31 15:12:45 2023 | unknown
stable-diffusion-webui-images-browser | https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git | main | 66827337 | Thu Jul 20 05:20:39 2023 | unknown
stable-diffusion-webui-instruct-pix2pix | https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix.git | main | 620ec642 | Fri Jan 27 21:20:50 2023 | unknown
stable-diffusion-webui-metadata-marker | https://github.com/new-sankaku/stable-diffusion-webui-metadata-marker.git | main | 8f0a24f9 | Sat May 20 18:36:02 2023 | unknown
stable-diffusion-webui-model-toolkit | https://github.com/arenasys/stable-diffusion-webui-model-toolkit.git | master | 4d8fea77 | Sun May 14 09:09:42 2023 | unknown
stable-diffusion-webui-rembg | https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git | master | 3d9eedbb | Sun Jun 4 13:35:24 2023 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | c99f382b | Tue Jun 13 04:29:35 2023 | unknown
LDSR | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
Lora | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
ScuNET | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
SwinIR | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
canvas-zoom-and-pan | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
extra-options-section | built-in | None |   | Thu Jul 20 22:36:51 2023 |  
prompt-bracket-checker

</body>
</html>Extension	URL	Branch	Version	Date	Update
OneButtonPrompt	https://github.com/AIrjen/OneButtonPrompt	main	[f3164248](https://github.com/AIrjen/OneButtonPrompt/commit/f3164248cfe07a163b24018ef970dabbf7956422)	Tue Jul 18 18:43:32 2023	unknown
SD-CN-Animation	https://github.com/volotat/SD-CN-Animation.git	main	[2e257bbf](https://github.com/volotat/SD-CN-Animation/commit/2e257bbfc3b76fb1323f7b22f820981c1b9f56b2)	Tue May 30 16:49:03 2023	unknown
SD-WebUI-BatchCheckpointPrompt	https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt	main	[aeb3d75a](https://github.com/h43lb1t0/SD-WebUI-BatchCheckpointPrompt/commit/aeb3d75a39580f08a26105bf6a453a3327f5ae78)	Mon Jun 19 21:22:38 2023	unknown
SadTalker	https://github.com/OpenTalker/SadTalker.git	main	[ae0b2635](https://github.com/OpenTalker/SadTalker/commit/ae0b26359d44c9379450a8e02a38b45eeec15549)	Mon Jul 3 05:48:35 2023	unknown
a1111-mini-paint	https://github.com/0Tick/a1111-mini-paint	main	[038d5731](https://github.com/0Tick/a1111-mini-paint/commit/038d5731baa599c4e8895d91deba4be4769e8c54)	Wed May 24 21:31:35 2023	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git	main	[8e97bf54](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/8e97bf54867c25d00fc480be1ab4dae5399b35ef)	Sun Jul 9 07:44:58 2023	unknown
adetailer	https://github.com/Bing-su/adetailer.git	main	[b040a628](https://github.com/Bing-su/adetailer/commit/b040a628dc1501a4c8d5b17423d96c77ef15f72e)	Thu Jul 20 02:01:32 2023	unknown
canvas-zoom	https://github.com/richrobber2/canvas-zoom.git	main	[88350430](https://github.com/richrobber2/canvas-zoom/commit/883504305f039e91a5c48ab9d23737a069ac73b1)	Thu Jul 20 21:40:35 2023	unknown
ddetailer	https://github.com/dustysys/ddetailer.git	master	[22a17414](https://github.com/dustysys/ddetailer/commit/22a17414bbca1fa4681d427b8aae5f970d17e896)	Mon Nov 28 09:33:31 2022	unknown
openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[d74fdd72](https://github.com/fkunn1326/openpose-editor/commit/d74fdd7242cefeaf7b5ce0e3fb04d48e11baaa0d)	Tue May 2 09:49:03 2023	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding	master	[27700fdd](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/27700fddf866e0f0e1f13e9fb4a1dead326d43d3)	Mon Jul 17 02:11:02 2023	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[098f6cd8](https://github.com/Mikubill/sd-webui-controlnet/commit/098f6cd887ac5f6f5f0e7cc9d81460095d2be012)	Tue Jul 18 05:06:14 2023	unknown
sd-webui-inpaint-anything	https://github.com/Uminosachi/sd-webui-inpaint-anything.git	main	[6f5d4746](https://github.com/Uminosachi/sd-webui-inpaint-anything/commit/6f5d47460a7464c74593ae7b3a0ad84f6dd2dafe)	Fri Jun 9 07:05:00 2023	unknown
sd-webui-mov2mov	https://github.com/Scholar01/sd-webui-mov2mov	master	[0ba11a1a](https://github.com/Scholar01/sd-webui-mov2mov/commit/0ba11a1a759b724a021ac1dc6829a8f59b100f9c)	Wed Apr 19 08:44:24 2023	unknown
sd-webui-roop	https://github.com/s0md3v/sd-webui-roop	main	[e6333fbe](https://github.com/s0md3v/sd-webui-roop/commit/e6333fbe5a0f3e6a515852388151f1db2315c45d)	Fri Jul 7 09:22:59 2023	unknown
sd-webui-segment-anything	https://github.com/continue-revolution/sd-webui-segment-anything.git	master	[780fc495](https://github.com/continue-revolution/sd-webui-segment-anything/commit/780fc495b47df3bd03ff62dffcd49d81abae9fa5)	Tue Jun 13 12:11:35 2023	unknown
sd-webui-supermerger	https://github.com/hako-mikan/sd-webui-supermerger.git	main	[7398bd8d](https://github.com/hako-mikan/sd-webui-supermerger/commit/7398bd8d5b16330c45e0ad24507bf2d4abbd18b1)	Tue May 23 15:57:48 2023	unknown
sd-webui-text2video	https://github.com/kabachuha/sd-webui-text2video.git	main	[8f0af8c9](https://github.com/kabachuha/sd-webui-text2video/commit/8f0af8c95a3c3a3af09c63cbdbdacc34b7a45f8d)	Fri Jul 14 12:41:05 2023	unknown
sd-webui-xldemo-txt2img	https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img.git	main	[e193c1c1](https://github.com/lifeisboringsoprogramming/sd-webui-xldemo-txt2img/commit/e193c1c1d063bc68974c8d5644ab208c12a1b056)	Mon Jul 17 00:58:40 2023	unknown
sd_dreambooth_extension	https://github.com/d8ahazard/sd_dreambooth_extension	main	[926ae204](https://github.com/d8ahazard/sd_dreambooth_extension/commit/926ae204ef5de17efca2059c334b6098492a0641)	Fri Mar 31 15:12:45 2023	unknown
stable-diffusion-webui-images-browser	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git	main	[66827337](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/66827337d7688b4255b9abb25edcc21b4f3ce913)	Thu Jul 20 05:20:39 2023	unknown
stable-diffusion-webui-instruct-pix2pix	https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix.git	main	[620ec642](https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix/commit/620ec642c874a7ecb79e816f2d43f0f0d3b1caac)	Fri Jan 27 21:20:50 2023	unknown
stable-diffusion-webui-metadata-marker	https://github.com/new-sankaku/stable-diffusion-webui-metadata-marker.git	main	[8f0a24f9](https://github.com/new-sankaku/stable-diffusion-webui-metadata-marker/commit/8f0a24f9894f6f4557e26d765b562900d9d4e56d)	Sat May 20 18:36:02 2023	unknown
stable-diffusion-webui-model-toolkit	https://github.com/arenasys/stable-diffusion-webui-model-toolkit.git	master	[4d8fea77](https://github.com/arenasys/stable-diffusion-webui-model-toolkit/commit/4d8fea77dba5643439691c1c6b003db4d330ff0b)	Sun May 14 09:09:42 2023	unknown
stable-diffusion-webui-rembg	https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg.git	master	[3d9eedbb](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg/commit/3d9eedbbf0d585207f97d5b21e42f32c0042df70)	Sun Jun 4 13:35:24 2023	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[c99f382b](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/c99f382b31509b87b4d512e70e9caf08ae7a079f)	Tue Jun 13 04:29:35 2023	unknown
LDSR	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
Lora	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
ScuNET	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
SwinIR	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
extra-options-section	[built-in](http://127.0.0.1:7860/)	None		Thu Jul 20 22:36:51 2023	
prompt-bracket-checker

**Comment by Bing-su** [comment]
No, you failed to load ddetailer.
