### ISSUE TITLE
[Feature Request/NSFW]: Is it possible to fix genitals?

### ISSUE THREAD

**Issue by narugo1992** [Bing-su/adetailer#222]
### Is your feature request related to a problem? Please describe.

Well, as the title.

We have an object detection [model](https://huggingface.co/deepghs/anime_censor_detection/tree/main/censor_detect_v1.0_s) and an [online demo](https://huggingface.co/spaces/deepghs/anime_object_detection) for this.

### Describe the solution you'd like

Like what `adetailer` does to faces and hands.

**Comment by Bing-su** [comment]
똑같이 `webui/models/adetailer` 폴더에 모델을 넣고 사용해주세요.
