### ISSUE TITLE
[Bug]: adetailer v7.2버전 이후로 lycoris가 적용되지 않습니다.(Since adetailer v7.2, lycoris is not applied.)

### ISSUE THREAD

**Issue by chudesad** [Bing-su/adetailer#224]
### Describe the bug

lycoris v7.2버전 이후로 lycoris를 adetailer 창에 넣으면 적용되지않습니다. lora는 됩니다. 저만 그렇습니까? 저는 webui 최신버전을 사용하고 있습니다. generate할 때 에러 메세지는 뜨지 않습니다. 7.2이전 버전은 잘 됩니다. 저는 코랩을 사용하고 있습니다.

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
[-] ADetailer initialized. version: 23.7.2, num models: 9
```

**Comment by Bing-su** [comment]
잘 모르겠네요

**Comment by chudesad** [comment]
> 

adetailer에 리코리스를 사용해보신적 있습니까?
