### ISSUE TITLE
[Bug]: When adetailer is installed, webUI cannot be started

### ISSUE THREAD

**Issue by kohxtpbb250** [Bing-su/adetailer#226]
### Describe the bug

I am using the Voldemort version of Paperspace, and after installing ADetailer and restarting WebUI, I get an error when I run "Launch the WebUI" and WebUI itself becomes unusable. Is there any way to use ADetailer?
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
/storage/stable-diffusion/stable-diffusion-webui
Traceback (most recent call last):
File "/storage/stable-diffusion/stable-diffusion-webui/webui.py", line 14, in <module>
from fastapi import FastAPI, Response
File "/usr/local/lib/python3.10/dist-packages/fastapi/__init__.py", line 7, in <module>
from .applications import FastAPI as FastAPI
File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 15, in <module>
from fastapi import routing
File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 22, in <module>
from fastapi import params
File "/usr/local/lib/python3.10/dist-packages/fastapi/params.py", line 4, in <module>
from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.10/dist-packages/pydantic/fields.py)

### The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.

```Shell
Python3.10
```

### List of installed extensions

controlnet

**Comment by xydreen** [comment]
I had a similar issue today which was resolved with updating stable diffusion.

Since I installed via git originally (on linux), all I had to do was:

1.) Close A1111
2.) Enter stable-diffusion-webui directory
3.) Run: git pull
4.) Start A1111

Problem resolved.

**Comment by kekewind** [comment]
I had a similar issue today which was resolved :
https://huggingface.co/Bingsu/adetailer/tree/main ，
Put all the models in this directory:  
\stable-diffusion-webui-master\models\adetailer-main ,
 just ok

**Comment by kohxtpbb250** [comment]
> 今日も同様の問題が発生しましたが、安定した拡散を更新することで解決されました。
> 
> 私はもともと git 経由で (Linux 上で) インストールしたので、私がしなければならなかったのは次のことだけでした。
> 
> 1.) A1111 を閉じます。 2.) 安定した拡散 webui ディレクトリに入ります。 3.) git pull を実行します 。 4.) A1111 を起動します。
> 
> 問題は解決しました。

Thanks for the reply! But WebUI could not be activated.

**Comment by kohxtpbb250** [comment]
> 今日も同様のことが発生しましたが、安定した拡散を更新することで解決されました。
> 
> 私は最初 git 途中で (Linux 上で) インストールしたので、私がしなければならなかったのは次のことだけでした。
> 
> 1.) A1111 を閉じます。 2.) 安定した拡散 webui ディレクトリに入ります。 3.) git pull を実行します 。 4.) A1111 を起動します。
> 
> 問題は解決しました。

**Comment by kohxtpbb250** [comment]
> I had a similar issue today which was resolved with updating stable diffusion.
> 
> Since I installed via git originally (on linux), all I had to do was:
> 
> 1.) Close A1111 2.) Enter stable-diffusion-webui directory 3.) Run: git pull 4.) Start A1111
> 
> Problem resolved.

Thanks for the reply! But WebUI could not be activated.
