### ISSUE TITLE
[Bug]: latest version of controlnet and the inpaint is bugged

### ISSUE THREAD

**Issue by tip0un3** [Bing-su/adetailer#228]
### Describe the bug

I use adetailer a lot. I noticed a problem with Tile ControlNet since version v1.1.232, so I stayed with version ControlNet v1.1.231.
Open issue : https://github.com/Mikubill/sd-webui-controlnet/issues/1802
I've created an example for comparison. I use it for example to modify a background and an outfit. I use adetailer for an auto mask on the face and then reverse the mask with a Tile treatment. This makes it easy to change clothes and background without changing the face.

That's the kind of result I get :
![0](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/e5957e5f-583e-4213-a35f-a267590791fa)
Original image

![1](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/9f5abd47-51e0-496a-b755-af6aa3f23cf5)
Tile ControlNet v1.1.231 adetailer (resultat good)

![2](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/5d235280-66a5-4a32-aa7c-eac16228e9f2)
Tile ControlNet v1.1.232 adetailer (the result is not good on clothes)

The difference is truly striking, yet the settings are exactly the same. I don't know what it's due to.
Tile's behavior when it comes to modifying clothes has been like this ever since.
The behavior of the 2 versions on the various ControlNet seems to be quite different...
Maybe something in adetailer with this update is no longer working?

### IMG2IMG parameters :

```Shell
Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 2373507959, Size: 576x1024, Model hash: 107d2a241b, Model: realistic_cyberrealisticv31_bakedvae, Denoising strength: 0, Clip skip: 2, ADetailer model: face_yolov8s.pt, ADetailer prompt: "masterpiece, absurdres, best quality, raw photography, (highres), 4k, digital art,\n(realistic lighting, cinematic lighting, realistic shadow, particles, depth of field, bloom),\n1girl, 20 years old, brown hair, huge breasts, (sexy purple bikini:1.5),\n(beach and sea in the background)", ADetailer negative prompt: "bad-hands-5, bad_prompt_version2, easynegative, Unspeakable-Horrors-Composition-4v, 2girls, loli, kid, young, (worst quality:1.4), (low quality:1.4), lowres, text, logo, normal quality, simple background, jpeg artifacts, cropped, signature, watermark, username, artist name", ADetailer confidence: 0.3, ADetailer dilate/erode: -8, ADetailer mask merge/invert: Merge and Invert, ADetailer mask blur: 4, ADetailer denoising strength: 1.0, ADetailer inpaint only masked: True, ADetailer inpaint padding: 32, ADetailer ControlNet model: control_v11f1e_sd15_tile [a371b31b], ADetailer version: 23.7.9, Noise multiplier: 1.05, ControlNet 0: "preprocessor: None, model: control_v11f1e_sd15_tile [a371b31b], weight: 1.0, starting/ending: (0.0, 1.0), resize mode: ResizeMode.INNER_FIT, pixel perfect: True, control mode: ControlMode.BALANCED, preprocessor params: (-1, -1, -1)", Version: v1.4.1
```

**Comment by DemitriLatet** [comment]
Same problem: [-] ADetailer: nothing detected on image 1 with 2nd settings.
