### ISSUE TITLE
[Feature Request]: Transfer prompt to adetailer when theres no prompt filled into adetailer 

### ISSUE THREAD

**Issue by 2blackbar** [Bing-su/adetailer#229]
### Is your feature request related to a problem? Please describe.

Can You make it so where you dont fill the prompt then it will transfer over original prompt from above ? The one used to generate the image.
Or maybe some tick box /option to transfer it 
It will save time

**Comment by Chubbly** [comment]
This is exactly how it currently works and how it has worked for a while. What version of Adetailer are you on? I am on v23.7.9, which I believe is the latest.

If it's not working for you, it might be bug.
