### ISSUE TITLE
[Question] Parameter description

### ISSUE THREAD

**Issue by 3305458q** [Bing-su/adetailer#23]
Hi. Thank you for the very cool extension, it helps just unreal!

But I don't fully understand what each slider is responsible for.
![image](https://user-images.githubusercontent.com/132700603/236624468-781188f2-5ddf-4bcd-9063-bce3d6c8e58b.png)

Can you please describe each function briefly and for the dumb ones. A couple of words would be enough. Or, even better, release an update where this explanation pops up when you point your cursor?
I don't really understand neural network theory, but I wish I understood what I was poking at. XD
If it's not too much trouble for you, of course.
(Sorry for the bad English)

**Comment by Bing-su** [comment]
Confidence threshold: In the case of a face, there is a probability value that when the detection model detects a region, it is confident that it is a face. This is an option to only detect areas where this value is above that number %.

erosion / dilation: see [opencv example](https://docs.opencv.org/3.4/db/df6/tutorial_erosion_dilatation.html). Here we simply enlarge or reduce the detected masks.

x, y offset: Move the detected masks horizontally, vertically.

mask blur: mask blur on the inpaint tab. Applies a gaussian blur of that number to the mask. https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/1526

denoising strength: img2img denoising strength.

Inpaint ~ padding pixels: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4637

controlnet weight: https://github.com/Mikubill/sd-webui-controlnet#weight-and-guidance-strengthstartend
