### ISSUE TITLE
[Bug]: Strange bug, where AND operator gets ignored in consecutive batches after ADetailer is triggered.

### ISSUE THREAD

**Issue by Nrgte** [Bing-su/adetailer#234]
### Describe the bug

So when I use the AND operator in a prompt, the first batch runs absolutely normal. But if ADetailer inpaints something in the first batch, all consecutive batches will ignore everything after the first AND operator. If I disable ADetailer or ADetailer doesn't inpaint anything during the first batch, all consecutive batches use the AND operator correctly.

Prompt: "a rainbow AND a woman in a park"
Batch Count: 2
Batch Size: 1

Image 1: https://i.imgur.com/NZaV1Mh.png
ADetailer found a face and inpainted it.

Image 2: https://i.imgur.com/0uRnE69.png

Model used in this case is experience_80. But as far as I can tell the issue appears with all models. Images inside the same batch do not show this issue. It only starts at the next batch.

ADetailer is at commit: b040a62 (Version v23.7.8)
https://github.com/Bing-su/adetailer/commit/b040a628dc1501a4c8d5b17423d96c77ef15f72e

Thanks!

### Screenshots

https://i.imgur.com/NZaV1Mh.png

https://i.imgur.com/0uRnE69.png

### Console logs, from start to end.

```Shell
There are no error in the log.
```

### List of installed extensions

No error in the logs.

**Comment by Bing-su** [comment]
저는 문제없이 잘되는군요.

**Comment by Nrgte** [comment]
> 저는 문제없이 잘되는군요.

Okay, I've managed to isolate the issue. It only seems to occur if the Neutral Prompt Extension is enabled and ADetailer is triggered in the first batch.

https://github.com/ljleb/sd-webui-neutral-prompt

I'm not sure whether this is a bug in ADetailer or in Neutral Prompt now.
