### ISSUE TITLE
[Feature Request]: support `{prompt}` in ADetailer prompt

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#235]
### Is your feature request related to a problem? Please describe.

i wanna keep main prompt without keep ADetailer prompt empty, but also add ADetailer only prompt

because when use face lora without main prompt or lora keyword in ADetailer prompt, the face is not as expected

### Describe the solution you'd like

add `{prompt}` like styles do

**Comment by Danamir** [comment]
Great idea. I added a small PR #243 to this end.
