### ISSUE TITLE
[Bug]: Adtailer not working after the 1.5.1 Automatic 1111 updated

### ISSUE THREAD

**Issue by cpy-ai** [Bing-su/adetailer#239]
### Describe the bug

The extension was working normally before updating to version 1.5.1 of Automatic 1111. However, after the update, it still works without any error logs but it doesn’t seem to apply any change to the image. The version of Adetailer extension is [a71f0e2b]

### Console logs, from start to end.

```Shell
N/A
```

**Comment by Nozownik** [comment]
I have the same problem.

**Comment by Wacheee** [comment]
I have the same issue, but in the console i have this error:
![image](https://github.com/Bing-su/adetailer/assets/77031418/407fd0d6-113d-48c0-8ba6-183cafcf181a)

**Comment by ArtificialOtaku** [comment]
In my case, the Adetailer tab won't even show anywhere inside the WeUI, even though I have the latest build from July 28.

**Comment by Wacheee** [comment]
> I have the same issue, but in the console i have this error: ![image](https://user-images.githubusercontent.com/77031418/256762850-407fd0d6-113d-48c0-8ba6-183cafcf181a.png)

I solve it, i desable all plugins and activated only Adetailer, now is working good. I dont know wich plugin was causing the issue yet

**Comment by ArtificialOtaku** [comment]
So, it's Adetailer but no other extensions active? Doesn't sound like a practical solution.
