### ISSUE TITLE
How to use properly?

### ISSUE THREAD

**Issue by yungyarko** [Bing-su/adetailer#25]
I have this installed, but I have no idea how to use it properly. Can you explain?

**Comment by aimarxjg** [comment]
使用方法：安装好插件它就出现SEED下方，勾选开启，并且选择模型，下面也要选“INPOINT“，还有选择“CON V11p SD15“（所有模式通用）
红色脸部追踪框：在SD的 总设置 里面找到它 勾选开启，这样能在生成图片的 文件夹 里面看到2张相同的图片，其中1张有脸部红框，否则看不到。

**Comment by Bing-su** [comment]
Sorry about that. It's hard to write instructions...

**Comment by yungyarko** [comment]
> 使用方法：安装好插件它就出现SEED下方，勾选开启，并且选择模型，下面也要选“INPOINT“，还有选择“CON V11p SD15“（所有模式通用） 红色脸部追踪框：在SD的 总设置 里面找到它 勾选开启，这样能在生成图片的 文件夹 里面看到2张相同的图片，其中1张有脸部红框，否则看不到。

Thanks for the help! I appreciate it.

**Comment by yungyarko** [comment]
> 使用方法：安装好插件它就出现SEED下方，勾选开启，并且选择模型，下面也要选“INPOINT“，还有选择“CON V11p SD15“（所有模式通用） 红色脸部追踪框：在SD的 总设置 里面找到它 勾选开启，这样能在生成图片的 文件夹 里面看到2张相同的图片，其中1张有脸部红框，否则看不到。

In the inpaint model selection, it says none. Is there any reason as to why?

**Comment by Bing-su** [comment]
[Mikubill/sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) must be installed, and the inpaint model must exist in the controlnet model path.

**Comment by yanjingwyj** [comment]
> 使用方法：安装好插件它就出现SEED下面，勾选开启，并选择模型，下面也要选“INPOINT”，还有选“CON V11p SD15”（所有模式通用）红色面部追踪框：在SD 的总设置里面找到它勾选开启，这样能在生成图片的文件里面夹看到2张相同的图片，其中1张有脸部红框，否则看不到。

红色面部追踪框,这个具体在哪里设置？“CON V11p SD15”（所有模式通用）这个在哪里？
