### ISSUE TITLE
[Feature Request]: xyz add `enable` control

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#251]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Bing-su/adetailer/assets/167966/1e65aef5-5dad-41d7-89c9-c57a9b450581)

like controlnet do
can control enable or disable in xyz

**Comment by Bing-su** [comment]
`ad_model`을 `None`으로 설정하면 비활성화되기 때문에 따로 해당 옵션을 만들지는 않았습니다.

**Comment by bluelovers** [comment]
didn't have `2nd` in xyz
