### ISSUE TITLE
Using adetailer for just 1 person in crowded place

### ISSUE THREAD

**Issue by daffatahtaa** [Bing-su/adetailer#257]
### Question

Hello,

I've been enjoying using this extension for a while but when I tried to use adetailer for a subject in crowded place e.g. bustling market, etc some or all of the face in the background is being affected even more if I'm using LoRa. Is there some settings I need to change? I'm trying to avoid using inpainting to make faster workflow.

Here I gave you some example picture:
![00607-608098195-intricate full body shot of seoulasuna wearing a sleeveless turtleneck and a brown coat, looking at viewer, BREAK one hand holdi](https://github.com/Bing-su/adetailer/assets/43267539/ab1f14e5-dcfa-465f-add5-846445b08c26)

**Comment by Bing-su** [comment]
Mask min ratio 옵션을 0.01 이상으로 설정해보세요

**Comment by daffatahtaa** [comment]
Thanks! will try that later
