### ISSUE TITLE
[Feature Request]: composable Lora and latent couple extensions

### ISSUE THREAD

**Issue by meanin2** [Bing-su/adetailer#261]
### Is your feature request related to a problem? Please describe.

It would be great too be able to use adetailer with multiple faces created with composable Laura latent coupling extensions. Right now adetailer will just choose one Lora for both faces

### Additional context

I want to be able to create coherent pictures with multiple subjects. I usually use adetailer for faces.

Best case scenario would be to take the latent couple extension and the composable Laura extension into account when adetailer

**Comment by Bing-su** [comment]
각 객체에 대해 인페인팅을 독립적으로 실행하므로 그런 확장은 의미가 없습니다. 오히려 `[SEP]` 문법(https://github.com/Bing-su/adetailer/wiki/Advanced)이 더 도움이 되실겁니다.
