### ISSUE TITLE
[Feature Request]: on/off 기능 밖으로 꺼내는건

### ISSUE THREAD

**Issue by ThisisLandu** [Bing-su/adetailer#266]
### Describe the solution you'd like

현재 adetailer를 사용하려면
adetailer 탭을 클릭한 후 on/off 해야하는데

adetailer 설정 건드리지 않고,
아래 컨트롤넷이나 다른 extension을 사용할경우, 스크롤을 해야하는 번거로움이 있습니다.

그래서 on/off 기능을 탭 밖으로 꺼내는 기능 추가하면 좋을것 같읍니다
(예시: dynamic thresholding: <https://github.com/mcmonkeyprojects/sd-dynamic-thresholding>))

**Comment by Bing-su** [comment]
공감은 합니다만... 굳이? 라는 생각입니다. 항상 사용하신다면 ui-config.json파일을 수정해서 enabled의 기본값을 true로 하시는 것도 괜찮습니다.

**Comment by ThisisLandu** [comment]
> 공감은 합니다만... 굳이? 라는 생각입니다. 항상 사용하신다면 ui-config.json파일을 수정해서 enabled의 기본값을 true로 하시는 것도 괜찮습니다.

답변감사합니다
현재 얼굴로라 사용해서 뽑아내고 있는데, 이중 몇개는 잘 작동하는데 몇개는 adetailer가 필수입니다.(adetailer없으면 뭉개짐)
그런데 adetailer 사용시 소요시간이 약 2배정도 늘어나는..... 상황이여서
특정 얼굴로라 사용시 쉽게 on/off 됬으면 좋겠읍니다 ㅠㅠ
