### ISSUE TITLE
I need help with documentation for api use

### ISSUE THREAD

**Issue by muunkky** [Bing-su/adetailer#270]
### Question

I've been at this for a while now. The fastapi documentation is a bit thin and I can't find where the list of parameters to pass to alwayson. Any chance we can get more detail on what goes into these? 

**what I'm passing to the WebUIApi.txt2img()**

alwayson_scripts = {
                                "adetailer": {
                                    "args": [True,"face_yolov8n.pt"]
                                } }
                               
**Here's what I get from the api documentation...**

/sdapi/v1/script-info
...
[
  {
    "name": "adetailer",
    "is_alwayson": true,
    "is_img2img": false,
    "args": [
      {
        "label": "Enable ADetailer",
        "value": false,
        "minimum": null,
        "maximum": null,
        "step": null,
        "choices": null
      },
      {
        "label": "",
        "value": {},
        "minimum": null,
        "maximum": null,
        "step": null,
        "choices": null
      },
      {
        "label": "",
        "value": {},
        "minimum": null,
        "maximum": null,
        "step": null,
        "choices": null
      }
    ]
  },

**Comment by honestabelink** [comment]
@muunkky

Class Definition
https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/adetailer/args.py#L39

If your assumptions on passing args into the script are correct, then it looks like this is the ordering,
https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/adetailer/args.py#L185

Though the args are defined by the gradio definitions by ui function : 

UI function for adetailer : 

https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/scripts/!adetailer.py#L114

Construction of args list from script runner, again args are auto built by gradio definition : 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/68f336bd994bed5442ad95bad6b6ad5564a5409a/modules/scripts.py#L388

You're probably at this point most interested in where the postprocess function is called and how the args get passed through.
What is interesting is that args are just grabbed by slicing the current args array.

`script_args = p.script_args[script.args_from:script.args_to]`

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/68f336bd994bed5442ad95bad6b6ad5564a5409a/modules/scripts.py#L547

Overall I don't see the bug as to why !After Detailer does report to you the args when you call `/sdapi/v1/script-info`

I didn't check your way of passing in args, for the moment I'll just assume that it's correct ;)

```
alwayson_scripts = {
"adetailer": {
"args": [True,"face_yolov8n.pt"]
} }
```

So I guess give it a whirl and let me know if you need more assistance.

Print out of some random image that had !After Detailer args preset, just so you can have default values... :

```
# YOU probably also need a Boolean here at the top like you have, it's kinda a separate???
ad_model: face_yolov8n.pt
ad_prompt:
ad_negative_prompt:
ad_confidence: 0.3
ad_mask_min_ratio: 0.0
ad_mask_max_ratio: 1.0
ad_dilate_erode: 4
ad_x_offset: 0
ad_y_offset: 0
ad_mask_merge_invert: None
ad_mask_blur: 4
ad_denoising_strength: 0.4
ad_inpaint_only_masked: True
ad_inpaint_only_masked_padding: 32
ad_use_inpaint_width_height: False
ad_inpaint_width: 512
ad_inpaint_height: 512
ad_use_steps: False
ad_steps: 28
ad_use_cfg_scale: False
ad_cfg_scale: 7.0
ad_use_sampler: False
ad_sampler: Euler a
ad_use_noise_multiplier: False
ad_noise_multiplier: 1.0
ad_use_clip_skip: False
ad_clip_skip: 1
ad_restore_face: False
ad_controlnet_model: None
ad_controlnet_module: None
ad_controlnet_weight: 1.0
ad_controlnet_guidance_start: 0.0
ad_controlnet_guidance_end: 1.0
is_api: False
ad_model: None
ad_prompt:
ad_negative_prompt:
ad_confidence: 0.3
ad_mask_min_ratio: 0.0
ad_mask_max_ratio: 1.0
ad_dilate_erode: 4
ad_x_offset: 0
ad_y_offset: 0
ad_mask_merge_invert: None
ad_mask_blur: 4
ad_denoising_strength: 0.4
ad_inpaint_only_masked: True
ad_inpaint_only_masked_padding: 32
ad_use_inpaint_width_height: False
ad_inpaint_width: 512
ad_inpaint_height: 512
ad_use_steps: False
ad_steps: 28
ad_use_cfg_scale: False
ad_cfg_scale: 7.0
ad_use_sampler: False
ad_sampler: Euler a
ad_use_noise_multiplier: False
ad_noise_multiplier: 1.0
ad_use_clip_skip: False
ad_clip_skip: 1
ad_restore_face: False
ad_controlnet_model: None
ad_controlnet_module: None
ad_controlnet_weight: 1.0
ad_controlnet_guidance_start: 0.0
ad_controlnet_guidance_end: 1.0
is_api: False
```
Ordering again is found here

https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/adetailer/args.py#L185

Again feel free to message back :)
Good luck

One last note, it looks like the loader for !After Detailer args is looking for a dict... I don't know if this is normal or not. But  you might wind up in a place where you do actually need to pass in a dict { ad_model: face_yolov8n.pt, ad_prompt: null, ... etc } over the api.
IDK :)

https://github.com/Bing-su/adetailer/blob/f18e00b40826381352ab9d7ca75f7af85065a31b/scripts/!adetailer.py#L176

I'd run a debugger and set some breakpoints and inspect what is going on. Or even just a some print statements on those script args.

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/wiki/API
