### ISSUE TITLE
mask 저장 옵션 여부?

### ISSUE THREAD

**Issue by ThisisLandu** [Bing-su/adetailer#274]
### Question

덕분에 재미 붙이고 잘 사용하고 있습니다
그런데 마스크가 같이 저장되는데 혹시 끄는 옵션(마스크 저장 안되게)이 있나요?
ui-config.json 랑 web ui setting - adetailer 옵션 다 찾아봤는데 해당하는 옵션이 없는것같아 질문드립니다

**Comment by Bing-su** [comment]
파일이름에 -ad가 들어가지 않는 마스크는 adetailer 옵션이 아니라 webui 자체 옵션입니다. 지금 테스트를 할 수 없어 옵션 위치를 확인해드릴 수가 없네요...
