### ISSUE TITLE
[Feature Request]: medvram

### ISSUE THREAD

**Issue by joneschunghk** [Bing-su/adetailer#277]
### Is your feature request related to a problem? Please describe.

I am getting OOM error when using adetailer on sdxl model

### Describe the solution you'd like

Do you have plans to release a medvram version?

**Comment by Bing-su** [comment]
해당 옵션은 이미 있습니다.

https://github.com/Bing-su/adetailer/blob/22602536535f850dae19fb4886e0dc8febf88f09/scripts/!adetailer.py#L221-L232

그리고 ultralytics 모델들은 vram 사용량이 매우 적은편이라 별로 도움은 안되실겁니다.
