### ISSUE TITLE
[Feature Request]: Possibility to change order of models

### ISSUE THREAD

**Issue by procule** [Bing-su/adetailer#279]
### Is your feature request related to a problem? Please describe.

When using multiple models, they are run from the 1st to the last.
If you want to change that order, e.g. run `face` configured on _1st_ after `person` configured on _2nd_, you currently need to note all the settings and rewrite them properly. 

### Describe the solution you'd like

It would be nice to be able to **drag and drop** the model buttons to re-order them. e.g. Dragging _1st_ to _3rd_ or the other way around

### Additional context

![image](https://github.com/Bing-su/adetailer/assets/152512/d22a9376-1bd8-4362-84e0-a1385c84645c)

**Comment by Bing-su** [comment]
자바스크립트가 필요한 기능은 제가 만들 수 없습니다
