### ISSUE TITLE
安装了adetailer，在图生图和文生图上面都不显示选项

### ISSUE THREAD

**Issue by tim9292654** [Bing-su/adetailer#28]
![Snipaste_2023-05-08_12-17-13](https://user-images.githubusercontent.com/29449662/236732770-e3a1f9c8-bc49-4016-ad76-03eabf5ef80a.png)
![Snipaste_2023-05-08_12-17-39](https://user-images.githubusercontent.com/29449662/236732775-5f702aa5-3137-4447-89cc-b0da5d38f5b1.png)
![Snipaste_2023-05-08_12-16-39](https://user-images.githubusercontent.com/29449662/236732780-f3d726f8-d946-421e-b07d-6d8560188176.png)
看了后台没有显示错误

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/blob/5a535d7460face5e9b3bf333aecf2f3034687f7b/scripts/!adetailer.py#L48C7-L50

the above text is output when it begins. please check it out.

**Comment by tim9292654** [comment]
已经解决了，需要修改common.py文件，把模型文件改成自己本机模型路径地址，不能用\，要使用/。

**Comment by Bing-su** [comment]
Is huggingface blocked in China?
