### ISSUE TITLE
[Bug]: ADetailer still runs even if skipped

### ISSUE THREAD

**Issue by elistys** [Bing-su/adetailer#284]
### Describe the bug

When I presented the problem at AUTOMATIC1111, I was guided here, so I will write it here.[#12658](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12658)

Even if I press the skip button during batch generation, the generation will stop,If a face is detected at that stage, ADetailer(mediapipe_face_full) will The process continues to the end without stopping.

Under the same conditions, if I press the interrupt button instead of skip, ADetailer will not run.

・ADetailer:v23.7.10
・webui:v1.5.1
・Python 3.10.x
・M2 Mac OS 13.5

### Console logs, from start to end.

```Shell
[If not detected]
 28%|████████████▎                               | 7/25 [00:34<01:28,  4.92s/it]
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[-] ADetailer: nothing detected on image 1 with 1st settings.

[if detected]
 52%|██████████████████████▎                    | 13/25 [00:54<00:50,  4.22s/it]
mediapipe: 1 detected.
100%|█████████████████████████████████████████████| 8/8 [00:12<00:00,  1.56s/it]
```

### List of installed extensions

adetailer
sd-webui-controlnet

**Comment by ArnoldDCoy** [comment]
That's more a lack of a feature than a bug.

**Comment by ArnoldDCoy** [comment]
A workaround I found is using 'Generate forever', and skipping with the "Interrupt" button instead.
