### ISSUE TITLE
How to use adetailer with SDXL diffusers?

### ISSUE THREAD

**Issue by putuoka** [Bing-su/adetailer#285]
### Question

https://colab.research.google.com/github/minimaxir/sdxl-experiments/blob/main/sdxl_image_generation.ipynb

i tried like this but isn't working

```

refiner = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    text_encoder_2=base.text_encoder_2,
    vae=base.vae,
    torch_dtype=torch.float16,
    custom_pipeline="Bingsu/adsd_pipeline",
    use_safetensors=True,
    variant="fp16",
)

```

**Comment by Bing-su** [comment]
SDXL은 지원하지 않습니다.

**Comment by putuoka** [comment]
> SDXL은 지원하지 않습니다.

but why can automatic111 use it on sdxl?

하지만 왜 automatic111이 sdxl에서 사용할 수 있습니까?

**Comment by elcolie** [comment]
This is a good question. Re-open it.
