### ISSUE TITLE
Adetailer not working with Asian lora model ?

### ISSUE THREAD

**Issue by AIrtistry** [Bing-su/adetailer#286]
### Question

I try to use adetailer with an asian lora model for be able to reproduce accuracy his face even in mid body / full body shot.

Thing is when I use adetailer with only the lora of my asian model, it's transform the initial subject ( asian ) to an western girl.

Adetailer seems to work fine with western subject but not really with asian ones, any solutions? Thanks

**Comment by k52252467** [comment]
The latest version doesn't seem to be able to make lora perform as well as the previous version, even if I use a weight of 1.2, it's the same, almost only the same face is generated, lora seems to have no effect

**Comment by AIrtistry** [comment]
> The latest version doesn't seem to be able to make lora perform as well as the previous version, even if I use a weight of 1.2, it's the same, almost only the same face is generated, lora seems to have no effect

hope they will fix it soon

**Comment by k52252467** [comment]
> > The latest version doesn't seem to be able to make lora perform as well as the previous version, even if I use a weight of 1.2, it's the same, almost only the same face is generated, lora seems to have no effect
> 
> hope they will fix it soon

I seem to have found the key. Try to delete the lycoris plug-in. In the latest version of Stable Diffusion (1.5.2), lycoris has been integrated into lora. If you use lycoris and still have problems using lora, please use <lyco :Modelxxx:0.5> to <lora:Modelxxx:0.5>, or don't use any lycoris, this is the way I found so far
