### ISSUE TITLE
Does not work with HiRes Fix if not inpainting at full resolution

### ISSUE THREAD

**Issue by williamkmlau** [Bing-su/adetailer#29]
AD works fine with HiRes fix if "Inpaint at full resolution" is checked.

But if "Inpaint at full resolution" is unchecked, the original low res image (before hi res fix is applied) is returned as final result

### **AD Preview Img (1024 x 1360)**

![00070-2632610465-ad-preview](https://user-images.githubusercontent.com/34730446/236886717-a28df007-7427-492e-a8e8-d307b25cb97a.png)

### **AD Before Img (1024 x 1360)**

![00071-2632610465-ad-before](https://user-images.githubusercontent.com/34730446/236886723-a389416b-1e83-4ac2-b602-9bf9caaa4ac0.png)

### **Final Img (512 x 680)**

![00072-2632610465](https://user-images.githubusercontent.com/34730446/236886728-a33abe81-81e9-4ee7-bc90-77fccd7f83c3.png)

**Comment by Bing-su** [comment]
If you don't use `Inpaint at full resolution`, it will resize to the input resolution, or if you use `use separate width/height`, it will resize to that resolution and then inpaint. 
Your image is not the image before the hires fix, but a resized version of that image. 
I was aware of this issue, but it's my fault for not explaining the usage properly, my apologies.

**Comment by williamkmlau** [comment]
> If you don't use `Inpaint at full resolution`, it will resize to the input resolution, or if you use `use separate width/height`, it will resize to that resolution and then inpaint. Your image is not the image before the hires fix, but a resized version of that image. I was aware of this issue, but it's my fault for not explaining the usage properly, my apologies.

But `use separate width/height` limits to 1024x1024 max, which makes most cases in Hi Res fix unusable

**Comment by Bing-su** [comment]
You can adjust that value by modifying your `ui-config.json` file.
