### ISSUE TITLE
[Feature Request]: Select or keep checkpoint of hi-res fix pass, or any checkpoint to Adetailer

### ISSUE THREAD

**Issue by Panchovix** [Bing-su/adetailer#290]
### Is your feature request related to a problem? Please describe.

Hi there, since Auto1111 webui added a way to select a checkpoint for hi-res fix, and when using Adetailer, the inpainting will be done with the first checkpoint select, and not the hi-res fix checkpoint choosen.

### Describe the solution you'd like

I would like to be able to select a checkpoint, as you can choose a sampler now, for the detailer inpainting.

### Describe alternatives you've considered

Another way would may be to use the hi-res fix checkpoint (like with a toggle?), and if it's disabled (by default), it uses the firstpass checkpoint.

### Additional context

Mostly the idea came from the hi-res fix checkpoint selection, and since as for now, it uses the firstpass checkpoint, I would like to be able to use either the hi-res fix pass checkpoint, or any checkpoint as the hi-res fix pass.

![image](https://github.com/Bing-su/adetailer/assets/19153797/0114eaa1-ff08-410e-b42c-99c0c756c377)

**Comment by Diamond-Shark-art** [comment]
Yes, i asked this last week too, https://github.com/Bing-su/adetailer/discussions/276

Playing with A1111 RC 1.6, using a anime checkpoint, a photorealistic for hires, and i ended with a photorealist image with anime faces lol.

**Comment by Panchovix** [comment]
Solved (added) by https://github.com/Bing-su/adetailer/commit/9f83506c35fb05c052415b4cdcee92f0369b9330

Thanks @Bing-su !
