### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [Bing-su/adetailer#294]
### Is your feature request related to a problem? Please describe.

Could we get a check box selection to choose if the Adetailer prompt/neg prompt gets 

Appended to the main prompt:
Addition

Replaces the main prompt:
Replacement

please ? <3

### Describe the solution you'd like

Check box selection

[X] append [ ] replace

**Comment by Bing-su** [comment]
얼마전에 `[PROMPT]` 키워드를 넣었습니다.
```
[PROMPT], some, ...
```
이런 식으로 프롬프트를 작성해보세요

**Comment by PurpleBlueAloeVera** [comment]
Thanks ! And sorry, I didn't notice this feature!
