### ISSUE TITLE
Unlink width/height when inpaint at full resolution is enabled

### ISSUE THREAD

**Issue by catboxanon** [Bing-su/adetailer#3]
Currently, the img2img process always uses the same width/height as the txt2img process:
https://github.com/Bing-su/adetailer/blob/6cc6dbea89b68705bc43a19f5c740662991ea3e9/scripts/!adetailer.py#L398-L399

When the `Inpaint at full resolution` option is enabled, this probably should instead be unlinked and be controllable by the user, as quite often the purpose of using that option in img2img normally is to allow for inpainting at a much higher resolution that differs from the source image, such as `768x768`, or even beyond that, as the image gets cropped to the masked area and upscaled, and then denoised. This is especially useful if running this extension with hires fix, as we may want to inpaint at a much higher resolution than what was the resolution pre-hires fix.

**Comment by Bing-su** [comment]
Close as #3. Thanks!
