### ISSUE TITLE
[Question] - LORA and TI

### ISSUE THREAD

**Issue by entmike** [Bing-su/adetailer#30]
Just a question, but does the prompt during the AD pass take into account TI embedding and LORA placeholder texts?

**Comment by Bing-su** [comment]
Yes, things like wildcards and dynamic prompts also apply. However, there are issues with making them visible in the exif, so I didn't do that.

**Comment by entmike** [comment]
Thanks!  Confirmed last night it worked.  I came back here to say the same.
