### ISSUE TITLE
ADetailer crashing AUDIO in Windows[Bug]: 

### ISSUE THREAD

**Issue by Adzido** [Bing-su/adetailer#300]
### Describe the bug

Every time the entire UI loads and there is a moment of loading ADetailer interrupts my audio on Discord, the video on YT crashes. The sound crashes for moments. To hear someone on Discord again I need to exit and connect to the channel, a nuisance. Anyone know what the issue is? How is this even possible if it's nothing related to sound? I have HyperX headphones and their software, but for the test I also took other headphones and it is exactly the same.

### Console logs, from start to end.

```Shell
Nothing, no logs. Just crash.
```

**Comment by Bing-su** [comment]
Well, I don't know, mediapipe seems to have something to do with it, but it only seems to be happening to a few users.

**Comment by clacheek** [comment]
I'm having the same issue, it's been months now, thought it was only me
