### ISSUE TITLE
Flow of what happens with ADetailer

### ISSUE THREAD

**Issue by landmann** [Bing-su/adetailer#301]
### Question

Hello!

I know roughly that ADetailer finds a face and does inpainting on the face. But does anyone know exactly the steps that happen when a user uses adetailer?

Does adetailer find a face and zooms into the square and inpaints the square ONLY, or does it use the whole image?

Any tips appreciated 🙏

**Comment by Bing-su** [comment]
You're correct. It depends on the inpaint option whether it paints just that rectangle or the entire image.
