### ISSUE TITLE
Unable to launch WebUI after install ADetailer

### ISSUE THREAD

**Issue by FoxMP** [Bing-su/adetailer#302]
### Describe the bug

Currently, my SD folder contain too many extensions so i thought this may cause many unexpected conflicts with ADetailer.

So I start fresh with a completely new SD installation (v1.6.0 as of today), put it in another place, left only ADetailer install, still cause WebUI to freeze and close with the following text : "Press any key to continue ..."

![2023-08-31 21_54_32](https://github.com/Bing-su/adetailer/assets/70951466/a0fe4141-393e-47ab-8083-6e53f9363640)

If I go to extensions folder then delete "adetailer", after that everything work fine.

### Console logs, from start to end.

```Shell
venv "D:\xxx\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --autolaunch
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Press any key to continue . . .
```

### List of installed extensions

ADetailer

![image](https://github.com/Bing-su/adetailer/assets/70951466/6b1fef04-55d9-43e5-a41e-a335b4d2d111)

**Comment by duanlanqunshan** [comment]
一样的问题，求大佬解答

**Comment by tomtangtrp** [comment]
I have the exact same problem as well.

**Comment by seacurve** [comment]
I have same problem, any help?

**Comment by seacurve** [comment]
> I have same problem, any help?

its work :D, after upgrade Python 3.10.6 ---> 3.10.11 from Microsoft store

**Comment by tomtangtrp** [comment]
> > I have same problem, any help?
> 
> its work :D, after upgrade Python 3.10.6 ---> 3.10.11 from Microsoft store

I have 3.10.11 installed from python official, but still have the same problem. Does it have to be installed from Microsoft sotre?

**Comment by duanlanqunshan** [comment]
有人能解决这个问题了吗
