### ISSUE TITLE
[Feature Request]: Choose which Checkpoint adetailer uses

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [Bing-su/adetailer#306]
### Is your feature request related to a problem? Please describe.

Basically, with the new implementations of WEBUI. There's the HiresFIX in which we can pick a second model for the second pass.
It's an awesome feature, but unfortunately, if used with Adetailer, adetailer will inpaint with the first pass model... Which is a shame

### Describe the solution you'd like

Checkpoint selector for Adetailer

**Comment by 2blackbar** [comment]
That would be neat

**Comment by PurpleBlueAloeVera** [comment]
NEAT. The feature has been added. Thank you Boss ! <3

**Comment by PurpleBlueAloeVera** [comment]
![test](https://media.discordapp.net/attachments/1132672845558857879/1148016035769897030/25819-20230904000540.png?width=520&height=676)

This, is what I wanted. Thank you so much! It's freakin awesome <3
