### ISSUE TITLE
[Feature Request]: Vary seed in adetailer process to create multiple variations in txt2img

### ISSUE THREAD

**Issue by catboxanon** [Bing-su/adetailer#309]
### Is your feature request related to a problem? Please describe.

I would like there to be a way to create multiple variations in txt2img of the adetailer result.

### Describe the solution you'd like

A new option within adetailer, perhaps completely outside the separate model tabs, that would allow choosing how many variations to return in the UI. I haven't verified yet but I believe this is already doable in img2img just by setting the batch count, so the option might only be needed in the txt2img tab.

### Describe alternatives you've considered

As mentioned above, I believe the only way to do this currently would be taking the image into img2img and using the batch count there. I would like this to be possible in txt2img as well, but if it's not desirable that's understandable.

### Additional context

I believe this could be done by running the main processing that's done [here](https://github.com/Bing-su/adetailer/blob/451b098529004406a15408468fdf03975ef783cc/scripts/!adetailer.py#L386) in a loop and incrementing the seed? Basically it should be done without needing to process the whole txt2img flow for each variation.

I'm not as familiar with this part of the code currently so if I were to try making a PR for this it may be a while.

**Comment by Bing-su** [comment]
Well, If you've reached the stage where you want multiple variations based on a seed, it means that you only want to change some of the specific images that the adetailer detects based on the seed.
I think you'd really be better to send it to img2img to handle this step.
