### ISSUE TITLE
When using alwayson_scripts controlnet and  After Detailer together, the API does not return the ControlNet processed image

### ISSUE THREAD

**Issue by entmike** [Bing-su/adetailer#31]
When using alwayson_scripts `controlnet` and  `After Detailer` together, the API does not return the ControlNet processed image.  The final image returns, however the canny/depth/pose reference image is not returned.

EDIT:  I might have answered my own question, I see additional settings in the A1111 Settings:

- `ad_save_previews`
- `ad_save_images_before`

I'll see if these change the expected behavior.

EDIT 2: Nope, unfortunately the API still only returns the final image.

**Comment by Bing-su** [comment]
Well, do you have the same problem when applying controlnet alone?

**Comment by Bing-su** [comment]
I've just added an option to run only selected scripts.

**Comment by entmike** [comment]
> Well, do you have the same problem when applying controlnet alone?

No, if I run without After Detailer, I get the processed CN image (depth/canny/pose) and the final generated image in the response payload from the API call.

**Comment by entmike** [comment]
> I've just added an option to run only selected scripts.

Hmm, I think that I might not be explaining my problem correctly, so I will post a complete example API call later today, but basically I was After Detailer to run along with the controlnet script (and this works GREAT!) but I still wish to have the ControlNet processed image included (which does when i run controlnet by itself, it returns an array of 2 images - the processed canny/depth/pose reference image and the final output image.)

Thanks again for all the helpful replies and I'll get a better example posted if that helps.
