### ISSUE TITLE
[Bug]: preview mask only show 1st mode

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#313]
### Describe the bug

https://civitai.com/models/138918/adetailer-after-detailer-female-breast-model

expected: show 2 mask mark at same time

### Screenshots

![20230903_023926-geminixMix_v20-20-1467502183-ad-preview](https://github.com/Bing-su/adetailer/assets/167966/c21a1439-0cb2-4242-8c80-35921c3e9b6a)

![20230903_024005-geminixMix_v20-20-1467502183-ad-preview](https://github.com/Bing-su/adetailer/assets/167966/a7efb792-614f-495f-bec4-a715abae1ccd)

### Console logs, from start to end.

```Shell
.
```

**Comment by Bing-su** [comment]
각 단계별로 보여주는게 의도입니다.
