### ISSUE TITLE
[Bug]: Changes to face are not saved in the final image.

### ISSUE THREAD

**Issue by meticulous22** [Bing-su/adetailer#315]
### Describe the bug

Not sure if I'm just misunderstanding something, but I see ADetailer create/apply mask/changes in the preview, but the they are not applied/saved to the final image? (I have verified that 'Save images before ADetailer' is not checked).

See the screen shots, before, during, and after.

### Screenshots

![face1](https://github.com/Bing-su/adetailer/assets/94130560/5f02bf06-8e85-4331-8727-e4acb95e4549)
![face2](https://github.com/Bing-su/adetailer/assets/94130560/b3f9c806-8817-4ad2-9307-e491034a1c01)
![face3](https://github.com/Bing-su/adetailer/assets/94130560/2e018d24-2b47-4892-b7d1-596cd90c89a0)

### Console logs, from start to end.

```Shell
Startup time: 2.1s (list SD models: 0.3s, load scripts: 1.3s, create ui: 0.3s).
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:13<00:00,  1.85it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:12<00:00,  1.94it/s]
0: 640x384 1 face, 7.0ms
Speed: 2.0ms preprocess, 7.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:10<00:00,  1.75it/s]
mediapipe: 1 detected.
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:10<00:00,  1.69it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:39<00:00,  1.57s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:12<00:00,  1.95it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:12<00:00,  1.95it/s]
0: 640x384 1 face, 7.0ms
Speed: 2.0ms preprocess, 7.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:09<00:00,  1.96it/s]
mediapipe: 1 detected.
100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:09<00:00,  1.95it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:36<00:00,  1.44s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:36<00:00,  1.95it/s]
```

### List of installed extensions

Disabled all but ADetailer and built in

**Comment by songib** [comment]
My A detailer always gets stuck after the last update on directML, I can't go for model number 4 atm, and I need to restart the command prompt. I can't use it. xd
For just one model active was fine.
Should I delete my venv folder or just wait for update? (Sometimes it's fix stuff)

**Comment by Kenneth-boop** [comment]
I am having a simmilar problem as songib, but I can't seem to use the "hand_yolo8n.pt" model, I am able to use 4 or more models but Automatic1111 seems to freeze when using the hands model and I have to restart the GUI and the webui-user.bat file. The console doesn't show any error or message, it just freezes the progress bar.

I am using Automatic1111 1.6.0 and Adetailer 23.9.1

**Comment by songib** [comment]
@Kenneth-boop I think that's the problem atm. I use a double model to inpaint the background aswell (person1-person2-hand-face) person1 for inpaint the background at higher resolution. I'm stuck at the 4th model idk because the hand or not, didn't test it atm.

**Comment by Kenneth-boop** [comment]
@songib let's hope for a quick fix.

**Comment by songib** [comment]
@Kenneth-boop y hopefully. atm I switch a different models to work with 4 models at the same time.

**Comment by Fully-Automatix** [comment]
Getting the same in Automatic1111. Updated A1111 and Adetailer from A1111. Still the same, Final image is unfortunately back to original.

Stumbled on a semi-work around:
Use 2 Adetailer models + "Save mask previews"
The preview for the 2nd model carries the changes from the 1st.
e.g. face_yolov8s followed by hand_yolov8n.
the preview for the hand_yolov8n has the face_yolov8s results.

The detection Grid is there of course. Would take a little work to remove.
