### ISSUE TITLE
[Feature Request]: Invert Selection

### ISSUE THREAD

**Issue by Wavuwavu** [Bing-su/adetailer#317]
I think it would be cool if you could reverse the selection of the inpaint.
For example: Person detection + reverse selection + separate checkpoint that does nice scenery = It would automatically inpaint everything but the detected person with a nice background.

In normal img2img inpaint mode this feature is called "Inpaint not masked" but I would like it automatic, thank you.

**Comment by Wavuwavu** [comment]
This already is a feature I'm blind lmao

**Comment by 4lt3r3go** [comment]
> This already is a feature I'm blind lmao

what? were? i'm looking for exactly this but can't find were is this feature?
i need to apply adetailer on a batch of images and inpaint everywere but not the face
how can i do that?
