### ISSUE TITLE
[Feature Request]: Very important buttons to make workflow easier

### ISSUE THREAD

**Issue by PurpleBlueAloeVera** [Bing-su/adetailer#320]
### Is your feature request related to a problem? Please describe.

Often I'm having troubles with using different settings and having to replace them in ALL my Adetailer tabs.

### Describe the solution you'd like

[Apply to all tabs] button 

Which applies the current tab's settings to ALL the other adetailer tabs.

[Reset tabs] button

Resets all tabs to default (Without having to reset the whole webui page..

[Switch tab x and tab x] buttons

Being able to switch the settings between tabs

### Describe alternatives you've considered

I know that there's config setting extensions out there. But that's not what I'm asking. Those should be specific to Adetailer to make the workflow easier. <3

**Comment by Bing-su** [comment]
만들기 힘드러욧
