### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by MysteryManTK** [Bing-su/adetailer#321]
### Question

This is an error message for the console:
[-] ADetailer: Failed to load model 'face_yolov8n.pt' from huggingface
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000013B55D947F0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Bingsu/adetailer/resolve/main/face_yolov8s.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000013B55D947F0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt

I do not understand, but according to my guess may need to download the model but the connection to the website timeout, I have the need to download the model itself, and put it in the specified location, in the webui this function is actually normal to use, but every time it starts to detect and then this error will appear, what should I do

I computer beginners, I hope the author can say some easy to understand, thank you

**Comment by Bing-su** [comment]
I fixed this a long time ago, what version are you using?

**Comment by wbzy00** [comment]
Use --ad-no-huggingface command line arg.

**Comment by hucaixue** [comment]
Same problem, how to add the arg?

**Comment by wbzy00** [comment]
> Same problem, how to add the arg?

It's in the webui-user.bat file within the SD folder. Append it after "set COMMANDLINE_ARGS=" along with other args if any.

**Comment by hucaixue** [comment]
thanks!

**Comment by hucaixue** [comment]
It doesn't work, same problem!

**Comment by MysteryManTK** [comment]
Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service

**Comment by wbzy00** [comment]
> Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service

What launcher? The webui-user.bat file? There seems to be no proxy related args for the WebUI.

**Comment by MysteryManTK** [comment]
> > Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service感谢作者，可以，顺便说一下，如果以上参数无法解决，并且您有代理，也可以尝试通过启动器的代理服务连接到模型下载网站
> 
> What launcher? The webui-user.bat file? There seems to be no proxy related args for the WebUI.什么启动器？webui-user.bat 文件？WebUI 似乎没有与代理相关的参数。

How to say, it is similar to the whole package, or the one-click launcher software, is done by some authors for the convenience of beginners in this area, it does not need to configure a variety of environments to smoothly start the webui, and it also contains all the webui files, but because of our country's problems, There are many websites that can not be accessed through the normal way, so the author in this launcher in order to facilitate our access to some external networks have added proxy Settings

**Comment by wbzy00** [comment]
> > > Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service感谢作者，可以，顺便说一下，如果以上参数无法解决，并且您有代理，也可以尝试通过启动器的代理服务连接到模型下载网站
> > 
> > 
> > What launcher? The webui-user.bat file? There seems to be no proxy related args for the WebUI.什么启动器？webui-user.bat 文件？WebUI 似乎没有与代理相关的参数。
> 
> How to say, it is similar to the whole package, or the one-click launcher software, is done by some authors for the convenience of beginners in this area, it does not need to configure a variety of environments to smoothly start the webui, and it also contains all the webui files, but because of our country's problems, There are many websites that can not be accessed through the normal way, so the author in this launcher in order to facilitate our access to some external networks have added proxy Settings

Ahh, I see. Some third party custom launcher. Probably 秋叶启动器, I guess.

**Comment by wbzy00** [comment]
> > > > > Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service感谢作者，可以，顺便说一下，如果以上参数无法解决，并且您有代理，也可以尝试通过启动器的代理服务连接到模型下载网站
> > > > 
> > > > 
> > > > What launcher? The webui-user.bat file? There seems to be no proxy related args for the WebUI.什么启动器？webui-user.bat 文件？WebUI 似乎没有与代理相关的参数。
> > > 
> > > 
> > > How to say, it is similar to the whole package, or the one-click launcher software, is done by some authors for the convenience of beginners in this area, it does not need to configure a variety of environments to smoothly start the webui, and it also contains all the webui files, but because of our country's problems, There are many websites that can not be accessed through the normal way, so the author in this launcher in order to facilitate our access to some external networks have added proxy Settings
> > 
> > 
> > Ahh, I see. Some third party custom launcher. Probably 秋叶启动器, I guess.
> 
> Yes, because at first I did not know that you can set a proxy in the launcher, so I came here to ask, and then I accidentally found, and then tried it, and found that you can connect, and then successfully checked the model, and then the error is not, which for a new MOE, like found a new continent.

How do you set the proxy? Like, put the "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt" in some white list?

**Comment by MysteryManTK** [comment]
> > > > > > Thanks to the author, can, by the way, if the above parameters can not be solved, and you have a proxy, you can also try to connect to the model download website through the launcher's proxy service感谢作者，可以，顺便说一下，如果以上参数无法解决，并且您有代理，也可以尝试通过启动器的代理服务连接到模型下载网站
> > > > > 
> > > > > 
> > > > > What launcher? The webui-user.bat file? There seems to be no proxy related args for the WebUI.什么启动器？webui-user.bat 文件？WebUI 似乎没有与代理相关的参数。什么启动器？webui-user.bat 文件？WebUI似乎没有与代理相关的参数。什么启动器？webui-user.bat 文件？WebUI 似乎没有与代理相关的参数。
> > > > 
> > > > 
> > > > How to say, it is similar to the whole package, or the one-click launcher software, is done by some authors for the convenience of beginners in this area, it does not need to configure a variety of environments to smoothly start the webui, and it also contains all the webui files, but because of our country's problems, There are many websites that can not be accessed through the normal way, so the author in this launcher in order to facilitate our access to some external networks have added proxy Settings怎么说呢，它类似于整个包，或者一键启动软件，是一些作者为了方便这方面的初学者而做的，它不需要配置各种环境就可以顺利启动webui，而且还包含了所有的webui文件，但是因为我国的问题， 有很多网站无法通过正常方式访问，所以笔者在这个启动器中为了方便我们访问一些外部网络而添加了代理设置
> > > 
> > > 
> > > Ahh, I see. Some third party custom launcher. Probably 秋叶启动器, I guess.啊，我明白了。一些第三方自定义启动器。大概是秋叶启动器，我猜。
> > 
> > 
> > Yes, because at first I did not know that you can set a proxy in the launcher, so I came here to ask, and then I accidentally found, and then tried it, and found that you can connect, and then successfully checked the model, and then the error is not, which for a new MOE, like found a new continent.是的，因为一开始我不知道你可以在启动器中设置代理，所以我来这里问一下，后来我无意中发现了，然后尝试了一下，发现可以连接，然后成功检查了模型，然后错误就不行了，这对于一个新的MOE，就像发现了一个新的大陆。
> 
> How do you set the proxy? Like, put the "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt" in some white list?如何设置代理？比如，把“https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt”放在一些白名单中？

In the launcher, locate the Settings in the lower left corner, locate Network Settings, open Proxy Settings, and type http://127.0.0.1:xxxxx (which then represents http in the proxy: Value), check the agent to apply to git, pip, environment variables, model download, these 4 options, and then open the agent and restart the launcher, but I am a computer white, the specific principle does not understand, can only talk about my operation, about this

**Comment by EmmaWebGH** [comment]
Why is it even trying to connect to something? I have the model already but on launch it tries to connect to... get the model? Didn't happen before update.
Why is the issue closed? There's no explanation of why the extension would need to connect, if the older version was already working fine. What does it want and why now?

**Comment by TigermanUK** [comment]
As this still has happened to me in 2026 I would add.  It seemed my firewall software is blocking download access even though I've allowed outgoing.  My quick fix was to download the models manually from     https://huggingface.co/Bingsu/adetailer/tree/main    and save them into     sd-webui-forge-neo\models\diffusers\models--Bingsu--adetailer\snapshots\"your numbered folder".     After which the error messages ceased.
