### ISSUE TITLE
Missing ADetailer tab

### ISSUE THREAD

**Issue by raiken92** [Bing-su/adetailer#325]
### Question

Everything was working fine but then I decided to update my extensions. After installing the updates and restarting the webui, I noticed that the ADetailer tab was missing. The extension still appears in the list of installed extensions though. And then in the cmd logs I got this error message:

```
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "D:\SD\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 20, in <module>
        from adetailer import (
      File "D:\SD\stable-diffusion-webui\extensions\adetailer\adetailer\__init__.py", line 5, in <module>
        from .ultralytics import ultralytics_predict
      File "D:\SD\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py", line 8, in <module>
        from ultralytics import YOLO
    ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)
```

I've also tried deleting and reinstalling the extension, but it still doesn't work. Is it something I did or is it the update that broken? If anyone can help me with this I'd be very grateful..

**Comment by mongalong247** [comment]
I'm having the same issue, i posted in the other error thread but this is the exact issue im having.

Currently in the process of rolling back to see if it fixes it.

https://stackoverflow.com/questions/76192675/importerror-cannot-import-name-yolo-from-ultralytics-unknown-location

**Comment by mongalong247** [comment]
Okay, so i dont think the issue is with Adetailer.  There was a push about the same time we started getting issues from Adetailer from the utralytics github, there's an issue loaded that matches pretty much what we are seeing here.  Also there hasn't been any changes to the file referenced in the error "ultralytics.py" since this commit https://github.com/Bing-su/adetailer/commit/335e6834faec5d4a2a34c38334b6175078d76340

https://github.com/ultralytics/ultralytics/issues/4889

**Comment by raiken92** [comment]
So have you found any solution for it? or is it something that we just have to wait until it's fixed?

**Comment by mongalong247** [comment]
> So have you found any solution for it? or is it something that we just have to wait until it's fixed?

from what i can see, they're marking stuff as resolved in that issue i linked to... but im not seeing it resolve at this end.  It might be a case of wait and see what Bing-Su says once they've had a look at this.  I'm not a programmer, so i can only discern so much.  I've even tried adding the model manually but it hasnt helped.

**Comment by raiken92** [comment]
Hmmm, I guess.. Thanks anyway for replying. At least I know I'm not the only one experiencing this. If you do find a solution please let me know, thanks .. :)

**Comment by Bing-su** [comment]
Update the `ultralytics` package to 8.0.178... or any version other than 8.0.177 or 8.0.174.

**Comment by ArtDesignAwesome** [comment]
Seriously, same issue here. needs to be fixed! this is a huge part of my workflow. PLZZZ

**Comment by QBloody** [comment]
I also have the same problem. For me it doesnt show an error with the adetailer.py, but when loading at the end also appears : ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)

:(

**Comment by nakedfighter3d** [comment]
Same, `ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)`

**Comment by sadxzero** [comment]
So, i kinda figured out how we can fix it
so basically i noticed that for some reason there is 2 ultralytics folders: first in python folder, second in venv folder of automatic
so I did it next way:

```
pip uninstall ultralytics
pip install ultralytics 
pip show ultralytics
```

then go to location that showed up in console, something like  e:\python 3.10.6\lib\site-packages
copy "ultralytics" folder and then paste and replace it in your automatic folder\venv\Lib\site-packages
for me it solve whole problem

**Comment by QBloody** [comment]
> So, i kinda figured out how we can fix it so basically i noticed that for some reason there is 2 ultralytics folders: first in python folder, second in venv folder of automatic so I did it next way:
> 
> ```
> pip uninstall ultralytics
> pip install ultralytics 
> pip show ultralytics
> ```
> 
> then go to location that showed up in console, something like e:\python 3.10.6\lib\site-packages copy "ultralytics" folder and then paste and replace it in your automatic folder\venv\Lib\site-packages for me it solve whole problem


OMG, this worked for me!! Thank you so much!

**Comment by nakedfighter3d** [comment]
Awesome, that worked for me! I activated my virtual environment first from the SD folder and simply reinstalled the ultralytics. It fixed the issues
`.\venv\Scripts\activate
pip uninstall ultralytics
pip install ultralytics 
`

**Comment by mongalong247** [comment]
yeah this worked for me as well.  I had to also delete the venv folder as well and do a full restart but i can see the ADetailer tab again.

**Comment by spa** [comment]
The command line approach didn't work for me (Windows 11, but probably user error). 

Instead, I took a more brute-force approach:

1. Manually removed the 'ultralytics' directories mentioned above from both my venv and web-ui directories.
2. Manually deleted the adetailer folder from /stable-diffusion-webui/extensions/
3. Restarted web-ui and re-installed adetailer
