### ISSUE TITLE
[Feature Request]: Compatibility with ReActor Extention

### ISSUE THREAD

**Issue by OfficialDSplayer** [Bing-su/adetailer#327]
### Is your feature request related to a problem? Please describe.

Currently using both ADetailer and ReActor in conjunction results in ReActor overriding any detail done by ADetailer because ReActor runs after ADetailer.

### Describe the solution you'd like

Make ADetailer run after ReActor.

### Describe alternatives you've considered

Ability to choose when ADetailer runs in the sequence post initial image generation.

**Comment by co5dt** [comment]
Yea, this would be very useful. Or is there any other way to influence the order of execution?

**Comment by drnod** [comment]
With the newest version of ReActor (0.6.1 BETA2) it seems that not even the workaround (renaming the extensions folder name, to change loading order) is helping anymore to make adetailer applying after reactor.

This would be awesome.

**Comment by co5dt** [comment]
Thanks for the heads-up, that has so far been my only resolve.

**Comment by drnod** [comment]
See also this ticket on ReActor. This is connected.
https://github.com/Gourieff/sd-webui-reactor/issues/218
