### ISSUE TITLE
Which img2img SD model is used?

### ISSUE THREAD

**Issue by buptlihang** [Bing-su/adetailer#329]
### Question

How is inpainting implemented? Which img2img SD model is used?

**Comment by buptlihang** [comment]
> It uses the inpainting from automatic1111. The model will be the one you choose.

Does this mean that the inpainting model and the Text2Img SD model I selected are the same model? 
That is, the SD model in the pipeline is called twice？

**Comment by Woisek** [comment]
> That is, the SD model in the pipeline is called twice？

Why should this be the case?
When you use Adetailer, you choose a CN model (and it's even labeled as 'ControlNet model') and a SD model.
So, where's the confusion?

**Comment by Bing-su** [comment]
You have the option to specify which checkpoint to use for inpainting, so it's not always the same. Anyway, it is correct that the pipeline is called twice.

**Comment by buptlihang** [comment]
> You have the option to specify which checkpoint to use for inpainting, so it's not always the same. Anyway, it is correct that the pipeline is called twice.

Thank you for your reply!
I noticed that the hand repaint didn't work that well (if I'm not mistaken). Do you have any ideas or plans for improving hand redrawing?
What I don't quite understand is why we would expect the second draw to be better than the first, even though the second draw may be using the same SD model as the first.
