### ISSUE TITLE
[Feature Request]: more model types

### ISSUE THREAD

**Issue by K0shachiyamyatA** [Bing-su/adetailer#334]
### Is your feature request related to a problem? Please describe.

Person inpaint works well in my discord bot, but it covers everything, including face and arms. So, when i only need to inpaint **specific** areas, it changes the face, arms and even background completely.

### Describe the solution you'd like

New model that would mask only the body(not including face, arms, etc) or a model for inpainting those 2 points of interest on the body. Maybe even both. Would be quite useful.

**Comment by Bing-su** [comment]
Thank you for the suggestion. However, I don't have any plans to add more models. If you want to build your own, you can use the [human parts segmentation](https://paperswithcode.com/dataset/pascal-person-part) dataset, for example.
