### ISSUE TITLE
[Feature Request]: True mask offsets and better box size control

### ISSUE THREAD

**Issue by GreenLandisaLie** [Bing-su/adetailer#344]
### Is your feature request related to a problem? Please describe.

Maybe its just me but I thought the 'offset' settings would **move** the box around without changing its shape. Instead, it actually **extends the box in a singular direction** - so we can't expand the box both (upwards and downwards / to the left and to the right) at the same time!

While this is great and all its still very limited in regards to control so I'd like to suggest to give users the ability to trully offset the box's position and also allow to expand it however we want.
Some simple math and a few lines of code + the ones for the extra UI elements is all it takes.

Thank you for this amazing tool! I've been having a lot of fun with it.

**Comment by Bing-su** [comment]
```py
from PIL import Image, ImageDraw, ImageChops

img = Image.new("L", (512, 512))
draw = ImageDraw.Draw(img)
draw.rectangle((100, 100, 200, 200), "white")
img
```
![230928-01](https://github.com/Bing-su/adetailer/assets/37621276/4bec2bd0-c94b-440c-83cd-e086b295ba05)

```py
ImageChops.offset(img, xoffset=100, yoffset=100)
```

![230928-02](https://github.com/Bing-su/adetailer/assets/37621276/ba16bf32-9d55-4804-94f3-814da3805406)

**Comment by GreenLandisaLie** [comment]
@Bing-su Interesting, I must have analyzed my results wrong because it felt to me like the box was expanding in the direction of the offset. My sincere apologies.

Since the offset is already working as intended then I guess this feature request should be only about the ability to expand the size of the box.

It should accept 4 directions, up, down, right and left. 4 new sliders in the UI. As for the max limit maybe 512? It should stop after reaching the corner of the image when giving it too high.

**Comment by GreenLandisaLie** [comment]
Tried to add this myself - see if it works. Need more testing but so far its working alright.

![ui](https://github.com/Bing-su/adetailer/assets/80653235/15b2e2f8-c97b-4381-9bb1-8cbef156b014)



```
from PIL import Image, ImageChops, ImageDraw

def get_mask_position(mask: Image.Image) -> list[float]:
    if is_all_black(mask):
        return None
    first_white_pixel, last_white_pixel = np.array(np.where(np.array(mask) == 255))[:,[0,-1]].T # values = (y, x)
    return [first_white_pixel[1], first_white_pixel[0], last_white_pixel[1], last_white_pixel[0]]

def ensure_border_limits(image_shape, value, is_X_value) -> int:
    if value < 0:
        return 0
    if value > image_shape[0] and is_X_value:
        return image_shape[0]
    if value > image_shape[1] and not is_X_value:
        return image_shape[1]
    return value

def resize_mask(mask: Image.Image, x1: int = 0, y1: int = 0, x2: int = 0, y2: int = 0) -> Image.Image:
    """
    All x,y args must be positive. Their range in the UI should probably be something like: 0 ~ 512
    """
    mask_position = get_mask_position(mask)
    if mask_position is None:
        return mask
    
    new_x1 = ensure_border_limits(mask.size, mask_position[0] - x1, True)
    new_y1 = ensure_border_limits(mask.size, mask_position[1] - y1, False)
    new_x2 = ensure_border_limits(mask.size, mask_position[2] + x2 -1, True)
    new_y2 = ensure_border_limits(mask.size, mask_position[3] + y2 -1, False)
    
    new_mask = Image.new("L", mask.size, 0)
    new_mask_draw = ImageDraw.Draw(new_mask)
    new_mask_draw.rectangle([new_x1, new_y1, new_x2, new_y2], fill=255)
    
    return new_mask
```

Made the necessary changes in args.py, ui.py, and passed the new args in !adetailer.py through mask_preprocess which resizes before offsetting like so:

```
if ad_x1_expand != 0 or ad_x2_expand != 0 or ad_y1_expand != 0 or ad_y2_expand != 0:
        masks = [resize_mask(m, x1=ad_x1_expand, y1=ad_y1_expand, x2=ad_x2_expand, y2=ad_y2_expand) for m in masks]
```

Test subject:
![v2](https://github.com/Bing-su/adetailer/assets/80653235/39dc681c-adef-482a-a7a1-d7b73ee62ceb)

Adetailer inpainted without mask expansion and dilation=4:
![result](https://github.com/Bing-su/adetailer/assets/80653235/e951fd22-778a-46f2-b0bc-d88d4ed2e492)

Result with resize=[0, 512, 0, 0] and dilation=52:
![resized_mask](https://github.com/Bing-su/adetailer/assets/80653235/31744c4b-006b-4ec5-b4db-52def0a5f761)
Notice how with a bit higher dilation the inpaint covered the hair a bit more to the left but not by much - and yet - it still inpainted all the way to the top of the image (the trees above the head changed). Which means its working.

Still don't know what kind of problems we could face since SD is very shape sensitive but for now its working for me.
