### ISSUE TITLE
[Feature Request]: [MODELS] command

### ISSUE THREAD

**Issue by GreenLandisaLie** [Bing-su/adetailer#345]
### Is your feature request related to a problem? Please describe.

We have `[PROMPT]` which is useful for concatenating the prompt. 
But let's say we only want to extract the LoRA triggers from the prompt - we could do this with a new command that would work like so:

Image prompt: `<lora:lora_name:0.5>, 1girl, blonde hair, long hair, full body, white dress, sunflower field, <lora:other_lora_name:0.6>`

(Inpainting face)

Adetailer initial prompt: `[MODELS], detailed face, 1girl, blonde hair, long hair, sunflower field`
Adetailer final prompt: `<lora:lora_name:0.5>, <lora:other_lora_name:0.6>, detailed face, 1girl, blonde hair, long hair, sunflower field`

Although I used just LoRAs as an example it should also work with textual inversions and hypernetworks.

**Comment by Bing-su** [comment]
굳이? 자주 쓰는 프롬프트가 있다면 와일드카드에 등록해서 사용해보세요.

**Comment by GreenLandisaLie** [comment]
That's not a bad idea but it over complicates the problem by a lot.

The idea here is simple - its to just allow Adetailer to force Stable Diffusion to inject the same extra model weights (LoRAs, etc...) used in the original image without having to dump everything from its prompt.

The use cases for this are self explanatory as per the example I showed above. 
Perhaps most people wouldn't use this feature but I do find it useful to me so I've already modified the code a little on 'def _get_prompt' within '!adetailer.py' to allow for at least LoRAs to be injected this way. I'm no programmer so this is a bit dumb code but it seems to work:

```
def replace_ignore_case(original_string, replace_this, with_this):
    compiled = re.compile(re.escape(replace_this), re.IGNORECASE)
    return compiled.sub(with_this, original_string)

...
elif "[lora]" in prompts[n].lower():
    prompt_copy = blank_replacement.lower()
    lora_ranges = []
    current_blank_replacement_index = 0 
    while "<lora:" in prompt_copy and ">" in prompt_copy:
        if prompt_copy.index("<lora:") < prompt_copy.index(">"):
            lora_ranges.append([prompt_copy.index("<lora:") + current_blank_replacement_index, prompt_copy.index(">")+1 + current_blank_replacement_index])
        current_blank_replacement_index += prompt_copy.index(">")+1
        prompt_copy = prompt_copy[prompt_copy.index(">")+1:]
        
    loras_str = ""
    for lr in lora_ranges:
        loras_str += blank_replacement[lr[0]:lr[1]] + ", "
    prompts[n] = replace_ignore_case(prompts[n], "[LORA]", loras_str[:-2] if len(loras_str) > 0 else "")
```
