### ISSUE TITLE
[Bug]: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by sunhaha123** [Bing-su/adetailer#346]
### Describe the bug

    RuntimeError: CUDA error: an illegal memory access was encountered

    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertion

 Can anyone tell me why I encounter this error after installing this extension?

### Screenshots

![image](https://github.com/Bing-su/adetailer/assets/27773261/eacc1413-6193-4a7c-a023-0bfaf9c3a804)

### Console logs, from start to end.

```Shell
Loading LoRA step controller...
Composable LoRA load successful.

  0%|          | 0/20 [00:00<?, ?it/s]

Total progress: 244it [07:23,  9.78s/it][A
  5%|▌         | 1/20 [00:00<00:13,  1.39it/s]

Total progress: 245it [07:23,  6.96s/it][A
 10%|█         | 2/20 [00:01<00:09,  1.89it/s]

Total progress: 246it [07:23,  5.00s/it][A
 15%|█▌        | 3/20 [00:01<00:08,  2.12it/s]

Total progress: 247it [07:24,  3.61s/it][A
 20%|██        | 4/20 [00:01<00:07,  2.28it/s]

Total progress: 248it [07:24,  2.65s/it][A
 25%|██▌       | 5/20 [00:02<00:06,  2.37it/s]

Total progress: 249it [07:25,  1.96s/it][A
 30%|███       | 6/20 [00:02<00:05,  2.50it/s]

Total progress: 250it [07:25,  1.47s/it][A
 35%|███▌      | 7/20 [00:02<00:04,  2.69it/s]

Total progress: 251it [07:25,  1.12s/it][A
 40%|████      | 8/20 [00:03<00:04,  2.82it/s]

Total progress: 252it [07:26,  1.13it/s][A
 45%|████▌     | 9/20 [00:03<00:03,  2.85it/s]

Total progress: 253it [07:26,  1.40it/s][A
 50%|█████     | 10/20 [00:03<00:03,  2.98it/s]

Total progress: 254it [07:26,  1.68it/s][A
 55%|█████▌    | 11/20 [00:04<00:02,  3.03it/s]

Total progress: 255it [07:27,  1.86it/s][A
 60%|██████    | 12/20 [00:04<00:02,  2.83it/s]

Total progress: 256it [07:27,  2.02it/s][A
 65%|██████▌   | 13/20 [00:05<00:02,  2.74it/s]

Total progress: 257it [07:27,  2.16it/s][A
 70%|███████   | 14/20 [00:05<00:02,  2.68it/s]

Total progress: 258it [07:28,  2.37it/s][A
 75%|███████▌  | 15/20 [00:05<00:01,  2.79it/s]

Total progress: 259it [07:28,  2.66it/s][A
 80%|████████  | 16/20 [00:06<00:01,  3.02it/s]

Total progress: 260it [07:28,  2.93it/s][A
 85%|████████▌ | 17/20 [00:06<00:00,  3.23it/s]

Total progress: 261it [07:28,  3.22it/s][A
 90%|█████████ | 18/20 [00:06<00:00,  3.47it/s]

Total progress: 262it [07:29,  3.39it/s][A
 95%|█████████▌| 19/20 [00:06<00:00,  3.58it/s]

Total progress: 263it [07:29,  3.53it/s][A
100%|██████████| 20/20 [00:07<00:00,  3.67it/s]
100%|██████████| 20/20 [00:07<00:00,  2.84it/s]

  0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0/10 [00:00<?, ?it/s]
*** API error: POST: http://127.0.0.1:6006/sdapi/v1/txt2img {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'CUDA error: an illegal memory access was encountered\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'}
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
        return self.receive_nowait()
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/talesofai_sd_v2/webui/modules/api/api.py", line 152, in exception_handling
        return await call_next(request)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "/root/talesofai_sd_v2/webui/modules/api/api.py", line 116, in log_and_time
        res: Response = await call_next(req)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
        raise app_exc
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
        raise exc
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
        raise e
      File "/root/miniconda3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
        response = await func(request)
      File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "/root/miniconda3/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
        return await future
      File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
        result = context.run(func, *args)
      File "/root/talesofai_sd_v2/webui/modules/api/api.py", line 345, in text2imgapi
        shared.state.end()
      File "/root/talesofai_sd_v2/webui/modules/shared.py", line 208, in end
        devices.torch_gc()
      File "/root/talesofai_sd_v2/webui/modules/devices.py", line 55, in torch_gc
        torch.cuda.empty_cache()
      File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
        torch._C._cuda_emptyCache()
    RuntimeError: CUDA error: an illegal memory access was encountered
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


---
```

### List of installed extensions

<html>
<body>
<div data-page-id="M7TDdPqE8oLJJYxS5e3c9PHrnLe" data-docx-has-block-data="true"><div>

webui | 1.5.1 master
-- | --
controlnet | v1.1.234
Lora Weight Block | 2023.07.22.0030(JST)
ADetailer | v23.7.8

</div></div><span data-lark-record-data="{&quot;isCut&quot;:false,&quot;rootId&quot;:&quot;M7TDdPqE8oLJJYxS5e3c9PHrnLe&quot;,&quot;parentId&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;blockIds&quot;:[1067,1069,1073,1075,1079,1081,1085,1087],&quot;recordIds&quot;:[&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;],&quot;recordMap&quot;:{&quot;La7XdYtfQoAIwuxz6N2cTNaVnfh&quot;:{&quot;id&quot;:&quot;La7XdYtfQoAIwuxz6N2cTNaVnfh&quot;,&quot;snapshot&quot;:{&quot;children&quot;:[&quot;BIl0daMbToLnbQx0HwrcfmTZnId&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;}},&quot;BIl0daMbToLnbQx0HwrcfmTZnId&quot;:{&quot;id&quot;:&quot;BIl0daMbToLnbQx0HwrcfmTZnId&quot;,&quot;snapshot&quot;:{&quot;align&quot;:&quot;&quot;,&quot;parent_id&quot;:&quot;La7XdYtfQoAIwuxz6N2cTNaVnfh&quot;,&quot;locked&quot;:false,&quot;children&quot;:[],&quot;text&quot;:{&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]},&quot;nextNum&quot;:1},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+5&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;webui&quot;}}},&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;comments&quot;:[],&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;}},&quot;DDLwdpAV7o3t3Ax5YYxcnUAznPd&quot;:{&quot;id&quot;:&quot;DDLwdpAV7o3t3Ax5YYxcnUAznPd&quot;,&quot;snapshot&quot;:{&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;YQdqd65gbowXErxofWgcPlRrnTg&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false}},&quot;YQdqd65gbowXErxofWgcPlRrnTg&quot;:{&quot;id&quot;:&quot;YQdqd65gbowXErxofWgcPlRrnTg&quot;,&quot;snapshot&quot;:{&quot;locked&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;align&quot;:&quot;&quot;,&quot;text&quot;:{&quot;apool&quot;:{&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]},&quot;nextNum&quot;:1},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+c&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;1.5.1 master&quot;}}},&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;DDLwdpAV7o3t3Ax5YYxcnUAznPd&quot;,&quot;comments&quot;:[],&quot;hidden&quot;:false,&quot;children&quot;:[]}},&quot;ECiqdwQ4Oobjy2xDV95cgYzVnKb&quot;:{&quot;id&quot;:&quot;ECiqdwQ4Oobjy2xDV95cgYzVnKb&quot;,&quot;snapshot&quot;:{&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;Wl0Td5s7Aost1gxGJcucOWcpnQf&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false}},&quot;Wl0Td5s7Aost1gxGJcucOWcpnQf&quot;:{&quot;id&quot;:&quot;Wl0Td5s7Aost1gxGJcucOWcpnQf&quot;,&quot;snapshot&quot;:{&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[],&quot;folded&quot;:false,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+a&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;controlnet&quot;}}},&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;ECiqdwQ4Oobjy2xDV95cgYzVnKb&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false}},&quot;Rka4d5mx5oOAsBxNUP7c3mmsnKd&quot;:{&quot;id&quot;:&quot;Rka4d5mx5oOAsBxNUP7c3mmsnKd&quot;,&quot;snapshot&quot;:{&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;ZcdndTfGjoWBkzxBBbwc3eQQnqY&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[]}},&quot;ZcdndTfGjoWBkzxBBbwc3eQQnqY&quot;:{&quot;id&quot;:&quot;ZcdndTfGjoWBkzxBBbwc3eQQnqY&quot;,&quot;snapshot&quot;:{&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;Rka4d5mx5oOAsBxNUP7c3mmsnKd&quot;,&quot;locked&quot;:false,&quot;children&quot;:[],&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+8&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;v1.1.234&quot;}}},&quot;comments&quot;:[],&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;folded&quot;:false}},&quot;TXycdeosWobXtixOCTAcsY5bnBh&quot;:{&quot;id&quot;:&quot;TXycdeosWobXtixOCTAcsY5bnBh&quot;,&quot;snapshot&quot;:{&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;GVM5dQ02UoOVvOxgZpJc0iXAnhc&quot;],&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;}},&quot;GVM5dQ02UoOVvOxgZpJc0iXAnhc&quot;:{&quot;id&quot;:&quot;GVM5dQ02UoOVvOxgZpJc0iXAnhc&quot;,&quot;snapshot&quot;:{&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;TXycdeosWobXtixOCTAcsY5bnBh&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:2,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;abbreviation-data&quot;,&quot;{\&quot;id\&quot;:\&quot;40e22efb-ded0-4a0e-a6ab-929749e0e210\&quot;,\&quot;abbr_ids\&quot;:\&quot;enterprise_7219181588217839620\&quot;,\&quot;is_visible\&quot;:1,\&quot;is_first\&quot;:1}&quot;],&quot;1&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0*1+4*1+d&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;Lora Weight Block&quot;}}}}},&quot;ShrVdOl0ZouJYgxgUU0cQO3Cnbg&quot;:{&quot;id&quot;:&quot;ShrVdOl0ZouJYgxgUU0cQO3Cnbg&quot;,&quot;snapshot&quot;:{&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;OGVwdAytVoBc8txW6EmczPNKn1d&quot;],&quot;type&quot;:&quot;table_cell&quot;}},&quot;OGVwdAytVoBc8txW6EmczPNKn1d&quot;:{&quot;id&quot;:&quot;OGVwdAytVoBc8txW6EmczPNKn1d&quot;,&quot;snapshot&quot;:{&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[],&quot;text&quot;:{&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+g*1*0+3*0+1&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;2023.07.22.0030(JST)&quot;}},&quot;apool&quot;:{&quot;nextNum&quot;:2,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;],&quot;1&quot;:[&quot;abbreviation-data&quot;,&quot;{\&quot;id\&quot;:\&quot;b5f98ca0-658c-4530-aaca-6926103ad072\&quot;,\&quot;abbr_ids\&quot;:\&quot;enterprise_7239246918264700932\&quot;,\&quot;is_visible\&quot;:1,\&quot;is_first\&quot;:1}&quot;]}}},&quot;align&quot;:&quot;&quot;,&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;ShrVdOl0ZouJYgxgUU0cQO3Cnbg&quot;,&quot;folded&quot;:false}},&quot;WZAsdOCtqoDG8hxCMQFcOLnDneg&quot;:{&quot;id&quot;:&quot;WZAsdOCtqoDG8hxCMQFcOLnDneg&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;table_cell&quot;,&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;DejEdqTtooBpTfxTByVcqjzUn5c&quot;]}},&quot;DejEdqTtooBpTfxTByVcqjzUn5c&quot;:{&quot;id&quot;:&quot;DejEdqTtooBpTfxTByVcqjzUn5c&quot;,&quot;snapshot&quot;:{&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0+9&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;ADetailer&quot;}}},&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;WZAsdOCtqoDG8hxCMQFcOLnDneg&quot;,&quot;children&quot;:[],&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false,&quot;comments&quot;:[],&quot;author&quot;:&quot;7178719282182815772&quot;}},&quot;YnJedZq62o4gWVxNUhWcOKVZnGe&quot;:{&quot;id&quot;:&quot;YnJedZq62o4gWVxNUhWcOKVZnGe&quot;,&quot;snapshot&quot;:{&quot;parent_id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[&quot;NJpnd88UboS8B8xreQkc7Vh0nYf&quot;],&quot;type&quot;:&quot;table_cell&quot;}},&quot;NJpnd88UboS8B8xreQkc7Vh0nYf&quot;:{&quot;id&quot;:&quot;NJpnd88UboS8B8xreQkc7Vh0nYf&quot;,&quot;snapshot&quot;:{&quot;type&quot;:&quot;text&quot;,&quot;parent_id&quot;:&quot;YnJedZq62o4gWVxNUhWcOKVZnGe&quot;,&quot;comments&quot;:[],&quot;locked&quot;:false,&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;children&quot;:[],&quot;text&quot;:{&quot;apool&quot;:{&quot;nextNum&quot;:1,&quot;numToAttrib&quot;:{&quot;0&quot;:[&quot;author&quot;,&quot;7178719282182815772&quot;]}},&quot;initialAttributedTexts&quot;:{&quot;attribs&quot;:{&quot;0&quot;:&quot;*0|1+1*0+7&quot;},&quot;text&quot;:{&quot;0&quot;:&quot;\nv23.7.8&quot;}}},&quot;hidden&quot;:false,&quot;align&quot;:&quot;&quot;,&quot;folded&quot;:false}},&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;:{&quot;id&quot;:&quot;PFJEdyvVeoZU76xj1ioc3OYCnS0&quot;,&quot;snapshot&quot;:{&quot;parent_id&quot;:&quot;M7TDdPqE8oLJJYxS5e3c9PHrnLe&quot;,&quot;comments&quot;:[],&quot;author&quot;:&quot;7178719282182815772&quot;,&quot;rows_id&quot;:[&quot;rowbad1404b-a88c-478e-805d-c3ee879640b3&quot;,&quot;row9cd9b141-3c62-4be0-9017-36de5a51e4fe&quot;,&quot;rowa28d89cc-7551-4d8c-a4ea-b453147ba55a&quot;,&quot;rowe1155ecc-5770-4d6a-80e9-51f03c03ea67&quot;],&quot;column_set&quot;:{&quot;col4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;column_width&quot;:336},&quot;col89537274-0646-4846-96a1-72718323d816&quot;:{&quot;column_width&quot;:219},&quot;colab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;column_width&quot;:336}},&quot;cell_set&quot;:{&quot;rowc64ce01a-1edb-4d17-8aba-d90981615f86col89537274-0646-4846-96a1-72718323d816&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;WVPcdYyldoGnA1xeLPiceculnsh&quot;},&quot;rowe1155ecc-5770-4d6a-80e9-51f03c03ea67col4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;ZcPTdBhgLoeZSTxjsPtcyaeanph&quot;},&quot;rowa28d89cc-7551-4d8c-a4ea-b453147ba55acolab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;TXycdeosWobXtixOCTAcsY5bnBh&quot;},&quot;rowbad1404b-a88c-478e-805d-c3ee879640b3col4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;MrhjdbSD9oN838xOR8BcACfOnru&quot;},&quot;rowc64ce01a-1edb-4d17-8aba-d90981615f86col4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;Zrsnd6PjroNllrxJ3g1c6oAWn0d&quot;},&quot;row9cd9b141-3c62-4be0-9017-36de5a51e4fecolab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;ECiqdwQ4Oobjy2xDV95cgYzVnKb&quot;},&quot;rowa28d89cc-7551-4d8c-a4ea-b453147ba55acol4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;YQLVd1jONouk6Lxd5g8c19kwnle&quot;},&quot;rowe1155ecc-5770-4d6a-80e9-51f03c03ea67col89537274-0646-4846-96a1-72718323d816&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;YnJedZq62o4gWVxNUhWcOKVZnGe&quot;},&quot;row9cd9b141-3c62-4be0-9017-36de5a51e4fecol4b915cb0-848d-4872-a534-601e6f0cf5b8&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;Fmakd2XKMoK3wDxCvSMcYqlvnxf&quot;},&quot;rowa28d89cc-7551-4d8c-a4ea-b453147ba55acol89537274-0646-4846-96a1-72718323d816&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;ShrVdOl0ZouJYgxgUU0cQO3Cnbg&quot;},&quot;rowbad1404b-a88c-478e-805d-c3ee879640b3colab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;merge_info&quot;:{&quot;col_span&quot;:1,&quot;row_span&quot;:1},&quot;block_id&quot;:&quot;La7XdYtfQoAIwuxz6N2cTNaVnfh&quot;},&quot;rowe1155ecc-5770-4d6a-80e9-51f03c03ea67colab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;WZAsdOCtqoDG8hxCMQFcOLnDneg&quot;},&quot;row9cd9b141-3c62-4be0-9017-36de5a51e4fecol89537274-0646-4846-96a1-72718323d816&quot;:{&quot;block_id&quot;:&quot;Rka4d5mx5oOAsBxNUP7c3mmsnKd&quot;,&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1}},&quot;rowbad1404b-a88c-478e-805d-c3ee879640b3col89537274-0646-4846-96a1-72718323d816&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;DDLwdpAV7o3t3Ax5YYxcnUAznPd&quot;},&quot;rowc64ce01a-1edb-4d17-8aba-d90981615f86colab54e6d4-6339-41ac-9275-6a5df2d00168&quot;:{&quot;merge_info&quot;:{&quot;row_span&quot;:1,&quot;col_span&quot;:1},&quot;block_id&quot;:&quot;RptgdEf9SoBPQTxoBx4cccaGnGh&quot;}},&quot;type&quot;:&quot;table&quot;,&quot;locked&quot;:false,&quot;hidden&quot;:false,&quot;columns_id&quot;:[&quot;colab54e6d4-6339-41ac-9275-6a5df2d00168&quot;,&quot;col89537274-0646-4846-96a1-72718323d816&quot;]}}},&quot;payloadMap&quot;:{&quot;BIl0daMbToLnbQx0HwrcfmTZnId&quot;:{&quot;level&quot;:1},&quot;YQdqd65gbowXErxofWgcPlRrnTg&quot;:{&quot;level&quot;:1},&quot;Wl0Td5s7Aost1gxGJcucOWcpnQf&quot;:{&quot;level&quot;:1},&quot;ZcdndTfGjoWBkzxBBbwc3eQQnqY&quot;:{&quot;level&quot;:1},&quot;GVM5dQ02UoOVvOxgZpJc0iXAnhc&quot;:{&quot;level&quot;:1},&quot;OGVwdAytVoBc8txW6EmczPNKn1d&quot;:{&quot;level&quot;:1},&quot;DejEdqTtooBpTfxTByVcqjzUn5c&quot;:{&quot;level&quot;:1},&quot;NJpnd88UboS8B8xreQkc7Vh0nYf&quot;:{&quot;level&quot;:1}},&quot;extra&quot;:{&quot;mention_page_title&quot;:{},&quot;external_mention_url&quot;:{}},&quot;isKeepQuoteContainer&quot;:false,&quot;selection&quot;:[{&quot;id&quot;:1067,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;La7XdYtfQoAIwuxz6N2cTNaVnfh&quot;},{&quot;id&quot;:1069,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;DDLwdpAV7o3t3Ax5YYxcnUAznPd&quot;},{&quot;id&quot;:1073,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;ECiqdwQ4Oobjy2xDV95cgYzVnKb&quot;},{&quot;id&quot;:1075,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;Rka4d5mx5oOAsBxNUP7c3mmsnKd&quot;},{&quot;id&quot;:1079,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;TXycdeosWobXtixOCTAcsY5bnBh&quot;},{&quot;id&quot;:1081,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;ShrVdOl0ZouJYgxgUU0cQO3Cnbg&quot;},{&quot;id&quot;:1085,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;WZAsdOCtqoDG8hxCMQFcOLnDneg&quot;},{&quot;id&quot;:1087,&quot;type&quot;:&quot;block&quot;,&quot;recordId&quot;:&quot;YnJedZq62o4gWVxNUhWcOKVZnGe&quot;}],&quot;pasteFlag&quot;:&quot;717a4abb-f537-4255-a9cb-b0acb45e8952&quot;}" data-lark-record-format="docx/record" class="lark-record-clipboard"></span>
</body>
</html>

**Comment by Bing-su** [comment]
게임을 하면서 이미지 생성도 같이 하는 경우에 가끔 이 에러를 볼 수 있습니다. adetailer와 관련은 없는것 같습니다.

**Comment by sunhaha123** [comment]
> 게임을 하면서 이미지 생성도 같이 하는 경우에 가끔 이 에러를 볼 수 있습니다. adetailer와 관련은 없는것 같습니다.

I just using txt2img api to generate images with different ckpts in Ubuntu22. Some extensions I also used, latent couple, composable lora, controlnet tile.
