### ISSUE TITLE
[Feature Request]: Startup speed optimization

### ISSUE THREAD

**Issue by hben35096** [Bing-su/adetailer#348]
### Is your feature request related to a problem? Please describe.

When I didn't have this plugin enabled, my webUI startup time was 20 seconds; After enabling this plugin, the WebUI startup time is 70 seconds.
This plugin is powerful and I love it, but after testing, it severely slows down the startup time of WebUI.

**Comment by Bing-su** [comment]
I'm aware of this issue but don't have any ideas on the solution.
