### ISSUE TITLE
Using different controlnet

### ISSUE THREAD

**Issue by rohitpaul23** [Bing-su/adetailer#353]
### Question

Hey nice repo..

1. I was working on fixing my generated image hand using openpose controlnet. I am thinking that it takes the pose of the generated image(am i correct ?) and use that to fixed hand and if so i wanted to understand what if the generated image has distorted hand and so the pose is also not correct 

2. Whether can I use any other controlnets apart from the given one, let's say dwpose. If so how to do it

**Comment by Bing-su** [comment]
1. There's no feature to fix the generated image if it has an incorrect pose. you need to do this manually.
2. What about dwpose? The restriction is hardcoded, so you should be able to modify it if you want.

**Comment by snowyu** [comment]
the dwpose is a preprocessor to detect fingers etc: https://github.com/Mikubill/sd-webui-controlnet/issues/1855
@Bing-su Could you add the selector of preprocessors?
