### ISSUE TITLE
Noticed openpose and Adetailer don't work together for faces

### ISSUE THREAD

**Issue by freke70** [Bing-su/adetailer#36]
When I use openpose and Adetailer inpaints the face, I notice I try to use openpose's full frame, instead of just the face portion.
Resulting in the faces regularly having tiny bodies inside.
Because it is using the full scale openpose model, instead of it's face portion.

Love this extension, hopefully it's something that can be fixed in the future.

Thanks for creating and sharing it!

**Comment by Bing-su** [comment]
Well, it could be an issue with the adetailer, or it could be an issue with your prompts and denoising strength.
