### ISSUE TITLE
How to use Adetailer with diffusers?

### ISSUE THREAD

**Issue by wly-ai-bj** [Bing-su/adetailer#360]
### Question

I want to use the  StableDiffusionControlNetInpaintPipeline of diffusers, but I don't know how to add adetailer in it.

I have tried to use AdCnPipeline instead of StableDiffusionControlNetInpaintPipeline,  but it did not work for me, because your inpaint_pipeline is StableDiffusionImg2ImgPipeline, not StableDiffusionControlNetInpaintPipeline.

Can you give me some examples to show how to use it??

Thank you!!

**Comment by agcty** [comment]
That would be amazing, also trying to use it with diffusers.

**Comment by wly-ai-bj** [comment]
> That would be amazing, also trying to use it with diffusers.

yes, I tried it with diffusers, but the result was not good and even the  hand got even worse.

**Comment by TmLev** [comment]
Anyone figured it out?

**Comment by crapthings** [comment]
Any news?
