### ISSUE TITLE
[Feature Request]: Please consider making comfyUi edition🙏

### ISSUE THREAD

**Issue by IdeaFridge** [Bing-su/adetailer#361]
### Is your feature request related to a problem? Please describe.

In the WebUI, unlike DDetailer and other similar extensions, I could use this extension with 'Animatediff,' and it has significantly improved the overall quality of the results.

However, in ComfyUI, there is no detailers like ADetailer. There is another face detailer available, but it's not compatible with 'Animatediff' or latent-related functions. (In my opinion, ADetailer offers advantages in other areas as well.)

When I attempt to convert latent data into a list of images, the detailer works, but only for individual images. Unfortunately, there is no cohesion when they are all brought together.

If you don't mind, please consider making a comfyUI edition of this awesome extension 🙏

**Comment by Bing-su** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack
