### ISSUE TITLE
[Bug]: Can't use adetailer + AnimateDiff more than once without restart

### ISSUE THREAD

**Issue by ColinCee** [Bing-su/adetailer#366]
### Describe the bug

TXT2IMG - The first run of adetailer and animatediff work fine, however the second run always errors

Only a restart of A1111 will fix this problem

### Console logs, from start to end.

```Shell
return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 12, 8]
```

### List of installed extensions

animatediff, adetailer

**Comment by fbz0081** [comment]
Getting the same error, have to restart after every gif generation. If adetailer is disabled with animatediff on it works.

https://civitai.com/articles/2475/animatediff-settings
other people are also encountering 
https://github.com/continue-revolution/sd-webui-animatediff/issues/3
issue on animatediff

**Comment by GuruVirus** [comment]
Support - highly anticipated
