### ISSUE TITLE
업데이트 후 혹시 ARGS 바뀐 부분이 있나요? 기존 방식으로 API 호출하면 또 에러가 나서 롤백 하였습니다.

### ISSUE THREAD

**Issue by rubyon** [Bing-su/adetailer#37]
업데이트 후 혹시 ARGS 바뀐 부분이 있나요? 기존 방식으로 API 호출하면 또 에러가 나서 롤백 하였습니다.

현재 API 로 호출하는 파라메터는 이렇습니다.

      alwayson_scripts = {
        "After Detailer":
          {
            "args": [
              true,
              args[1]["ad_model"],
              args[1]["ad_prompt"],
              args[1]["ad_negative_prompt"],
              args[1]["ad_conf"].to_i,
              args[1]["ad_dilate_erode"].to_i,
              args[1]["ad_x_offset"].to_i,
              args[1]["ad_y_offset"].to_i,
              args[1]["ad_mask_blur"].to_i,
              args[1]["ad_denoising_strength"].to_f,
              args[1]["ad_inpaint_full_res"],
              args[1]["ad_inpaint_full_res_padding"].to_i,
              args[1]["ad_use_inpaint_width_height"],
              args[1]["ad_inpaint_width"].to_i,
              args[1]["ad_inpaint_height"].to_i,
              args[1]["ad_cfg_scale"].to_f,
              "None",
              1,
            ]
          }
      }
      
      8c525a3c 커밋에서는 정상동작 합니다. 혹시 추가된 부분이 있으면 귀뜸해주시면 수정해보겠습니다.

에러 메세지 첨부 합니다.

May 10 14:38:34 rubyon.co.kr sh[100987]: Error running process: /home/ai/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py
May 10 14:38:34 rubyon.co.kr sh[100987]: Traceback (most recent call last):
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "/home/ai/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 346, in get_args
May 10 14:38:34 rubyon.co.kr sh[100987]:     inp = get_one_args(enabled, *args)
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "/home/ai/stable-diffusion-webui/extensions/adetailer/adetailer/args.py", line 117, in get_one_args
May 10 14:38:34 rubyon.co.kr sh[100987]:     return ADetailerArgs(**arg_dict)
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
May 10 14:38:34 rubyon.co.kr sh[100987]: pydantic.error_wrappers.ValidationError: 2 validation errors for ADetailerArgs
May 10 14:38:34 rubyon.co.kr sh[100987]: ad_use_cfg_scale
May 10 14:38:34 rubyon.co.kr sh[100987]:   value could not be parsed to a boolean (type=type_error.bool)
May 10 14:38:34 rubyon.co.kr sh[100987]: ad_cfg_scale
May 10 14:38:34 rubyon.co.kr sh[100987]:   value is not a valid float (type=type_error.float)
May 10 14:38:34 rubyon.co.kr sh[100987]: The above exception was the direct cause of the following exception:
May 10 14:38:34 rubyon.co.kr sh[100987]: Traceback (most recent call last):
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "/home/ai/stable-diffusion-webui/modules/scripts.py", line 417, in process
May 10 14:38:34 rubyon.co.kr sh[100987]:     script.process(p, *script_args)
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "/home/ai/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 558, in process
May 10 14:38:34 rubyon.co.kr sh[100987]:     arg_list = self.get_args(*args_)
May 10 14:38:34 rubyon.co.kr sh[100987]:   File "/home/ai/stable-diffusion-webui/extensions/adetailer/scripts/!adetailer.py", line 355, in get_args
May 10 14:38:34 rubyon.co.kr sh[100987]:     raise ValueError("\n".join(message)) from e
May 10 14:38:34 rubyon.co.kr sh[100987]: ValueError: [-] ADetailer: ValidationError when validating 1st arguments: 2 validation errors for ADetailerArgs
May 10 14:38:34 rubyon.co.kr sh[100987]: ad_use_cfg_scale
May 10 14:38:34 rubyon.co.kr sh[100987]:   value could not be parsed to a boolean (type=type_error.bool)
May 10 14:38:34 rubyon.co.kr sh[100987]: ad_cfg_scale
May 10 14:38:34 rubyon.co.kr sh[100987]:   value is not a valid float (type=type_error.float)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_model: 'face_yolov8s.pt' (<class 'str'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_prompt: '' (<class 'str'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_negative_prompt: '' (<class 'str'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_conf: 30 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_dilate_erode: 32 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_x_offset: 0 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_y_offset: 0 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_mask_blur: 4 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_denoising_strength: 0.4 (<class 'float'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_inpaint_full_res: True (<class 'bool'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_inpaint_full_res_padding: 0 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_use_inpaint_width_height: False (<class 'bool'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_inpaint_width: 512 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_inpaint_height: 512 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_use_cfg_scale: 7.0 (<class 'float'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_cfg_scale: 'None' (<class 'str'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_controlnet_model: 1 (<class 'int'>)
May 10 14:38:34 rubyon.co.kr sh[100987]:     ad_controlnet_weight: 1.0 (<class 'float'>)

**Comment by rubyon** [comment]
자세히 들여다보니 ad_use_cfg_scale 파라메터가추가 되었네요 일단 true 로 강제로 넘겨서 오류는 잡았습니다.

**Comment by Bing-su** [comment]
사실 입력을 key value 형태로 받을수 있었다면 이런걸 막을 수 있었을텐데 그렇게 할 수가 없어서 아쉽습니다.
저는 입력값 검증에 pydantic을 쓰고있기때문에, 모든 타입을 string으로 보내도 pydantic이 처리를 해줘서 유효합니다.

**Comment by Bing-su** [comment]
API 사용법을 고쳤습니다. 위키에 예시를 적어뒀으니 확인해주세요
