### ISSUE TITLE
[Feature Request]: Add a Save Original Image checkbox

### ISSUE THREAD

**Issue by Code4SAFrankie** [Bing-su/adetailer#371]
### Is your feature request related to a problem? Please describe.

If a face is not detected no image is save and the original image is lost. The Face Editor extension has a Save Original Image checkbox which saves the original image before the face is replaced. This is a nice feature, since sometimes the original face is better than the one replaced by the extension. Also completely losing the image when no face is detected is very wasteful in terms of computer cycles and potential inpaint fixes.

### Describe the solution you'd like

Provide a Save Original Image checkbox which will always save the image generated before the adetailer extension replaces the face.

### Describe alternatives you've considered

None.

**Comment by Bing-su** [comment]
![chrome_744iLWzsbU](https://github.com/Bing-su/adetailer/assets/37621276/771dcf2b-d39a-4f08-96bb-d1422b0f9685)
That option already exists. Thanks.

**Comment by Code4SAFrankie** [comment]
Thanks found it under Settings
