### ISSUE TITLE
[Feature Request]: detail the background (inverse person)

### ISSUE THREAD

**Issue by muunkky** [Bing-su/adetailer#373]
### Is your feature request related to a problem? Please describe.

I am frustrated with the backgrounds of images are not as detailed as the foreground. In comfyui I can invert the mask and detail the background, I think people would like this with a pretty simple integration in adetailer too.

### Describe the solution you'd like

A new pt model in the "Adetailer model" dropdown, or a checkbox for "inverse mask" to detail everything except what the model finds.

### Describe alternatives you've considered

Can set up comfyui for this but is quite complicated

**Comment by jheidt** [comment]
Doesn't mask merge invert do this?
Mask merge mode: [Merge & Invert](https://github.com/search?q=repo%3ABing-su/adetailer%20mask_merge_invert&type=code)

**Comment by Bing-su** [comment]
![image](https://github.com/Bing-su/adetailer/assets/37621276/bc673d8d-36cf-4817-9cf9-67d5216f1f47)
Yes. That option already exists
