### ISSUE TITLE
[Feature Request]: Configurable path to Adetailer models in settings

### ISSUE THREAD

**Issue by GodEmperor785** [Bing-su/adetailer#374]
### Is your feature request related to a problem? Please describe.

Adetailer detection models are always in models/adetailer directory and when I have multiple webui installations I have to either duplicate models or create links which for some reason can break and need to be recreated.
Having a configurable path to adetailer models in settings would help here as it would be easier to just add a path there and it would be easier to share models between several webui installations

### Describe the solution you'd like

A new setting in adetailer tab in settings to specify path where to find detection models, like it is done for example with ControlNet extenstion (setting "Extra path to scan for ControlNet models").

**Comment by Bing-su** [comment]
I see, I'll add it.

**Comment by GodEmperor785** [comment]
After updating Adetailer I see that now there is additional setting for adetailer models and it seems to work as expected. I will close this issue as feature is added now. Thanks for adding this setting
