### ISSUE TITLE
[Feature Request]: Can you add multiple pass

### ISSUE THREAD

**Issue by FurkanGozukara** [Bing-su/adetailer#375]
### Is your feature request related to a problem? Please describe.

What i mean is let's say I want to inpaint face 3 times with 0.4 denoise

So first inpaint and repeat process

Can you add this option? It will be just for loop :)

**Comment by Bing-su** [comment]
What use case is this...

**Comment by FurkanGozukara** [comment]
> What use case is this...

it will be like this

with lower denoise we will have better image with multiple times inpainting 

in each loop it will get better

**Comment by njmp11** [comment]
You can experiment with this already, use face model in all 3 tabs and set as you wish. I think result is not as good as you imagine. I thought this could let me use low denoise per pass and improve incrementally without changing facial expression, eyes open, smile etc. but it results in ghosting of features.

**Comment by FurkanGozukara** [comment]
> You can experiment with this already, use face model in all 3 tabs and set as you wish. I think result is not as good as you imagine. I thought this could let me use low denoise per pass and improve incrementally without changing facial expression, eyes open, smile etc. but it results in ghosting of features.

this makes sense thank you.
