### ISSUE TITLE
[Feature Request]: It is hard slash impossible to use adetailer with https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt

### ISSUE THREAD

**Issue by left1000** [Bing-su/adetailer#380]
### Is your feature request related to a problem? Please describe.

The issue is that even a dynamic rttensor engine profile has a minimum resolution of 256x256 and adetailer's autodetection can end up with a lower resolution than even that.

It'd be nice if there was some sort of option for adetailer to use the standard default u-net instead of the bespoke rttensor engine profile, even when sd-unet is set to use the custom rttensor engine for the main image generation and highres fix portions....

I could set adetailer to a fixed resolution of 256x256 but that wouldn't handle the situation particularly well as it would often be too much resolution and sometimes be too little...

The dynamic range engine profile of 256x256x up to 512x512 feels like it could be meant for adetailer, but it just flat out doesn't work, again, I assume due to the adetailer's varied resolutions.

### Describe the solution you'd like

I'm not sure if this has to be a feature of automatic1111webgui or adetailer itself, but defaulting to the default sd-unet for adetailer really needs to be a toggle checkbox so people can use their engine profiles while adetailer is on.... it'll make large batches so quick.

### Describe alternatives you've considered

I already covered the alternative, the alternative is to checkbox fixed resolution for adetailer, but I feel like this goes against the point of adetailer's automatic region detection systems?

**Comment by left1000** [comment]
Even better idea! Something that would help everyone and be quite a bit simpler. Make adetailer have an option for minimum width and minimum height and maximum width and maximum height. That way I could set my width and height to 256-512 x 256-512 and perfectly force adetailer to fit within my engine profile from https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt while still giving the detection some freedom to make a decently sized/shaped inpainting region.

**Comment by tyen0** [comment]
My tensorrt profile has a minimum of 512x512, but adetailer is logging "0: 640x480 1 face, 3.0ms" and certainly getting the speed boost running at 40it/s.  I have no idea why since it's outside the range, but I am not complaining. :D I'm probably misunderstanding the adetailer log messages.

**Comment by bigmover** [comment]
> Even better idea! Something that would help everyone and be quite a bit simpler. Make adetailer have an option for minimum width and minimum height and maximum width and maximum height. That way I could set my width and height to 256-512 x 256-512 and perfectly force adetailer to fit within my engine profile from https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt while still giving the detection some freedom to make a decently sized/shaped inpainting region.


Is it re-calculated or resized? Any idea for this？
