### ISSUE TITLE
[Bug]: Progress bar completely nonsensical with adetailer

### ISSUE THREAD

**Issue by hollowstrawberry** [Bing-su/adetailer#382]
### Describe the bug

The progress bar jumps all over the place during and after adetailer passes.

In the video, you can see how after 1 image is done out of 2, it jumps from 50% to 20%, climbs to 40%, jumps to 33%, climbs to 50%, then jumps to 67% (at this point, it should be showing 50%). After the second image is finished, it shows 88% instead of 100%.

For a single image, adetailer finishes at 50% instead of 100%.

This is confusing and annoying.

### Screenshots

https://github.com/Bing-su/adetailer/assets/33796679/4eba80c7-c593-44f6-9b7c-b396f4c21883

### Console logs, from start to end.

```Shell
0: 640x512 1 animal ears, 192.0ms
Speed: 5.0ms preprocess, 192.0ms inference, 13.0ms postprocess per image at shape (1, 3, 640, 512)
Using already loaded model LimboMixV2.inpainting.safetensors [9e933bb0eb]: done in 0.0s
100%|██████████████████████████████████████████████| 16/16 [00:04<00:00,  3.39it/s]
Using already loaded model LimboMixV2.safetensors [60b0221b31]: done in 0.0s
100%|██████████████████████████████████████████████| 30/30 [00:10<00:00,  2.74it/s]
100%|██████████████████████████████████████████████| 10/10 [00:13<00:00,  1.33s/it]
Total progress: 100%|██████████████████████████████| 80/80 [01:15<00:00,  1.43s/it]
0: 640x512 1 face, 262.0ms
Speed: 7.0ms preprocess, 262.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 512)
100%|██████████████████████████████████████████████| 13/13 [00:04<00:00,  2.98it/s]

0: 640x512 3 animal earss, 267.0ms
Speed: 7.0ms preprocess, 267.0ms inference, 11.0ms postprocess per image at shape (1, 3, 640, 512)
Using already loaded model LimboMixV2.inpainting.safetensors [9e933bb0eb]: done in 0.0s
100%|██████████████████████████████████████████████| 16/16 [00:04<00:00,  3.26it/s]
100%|██████████████████████████████████████████████| 16/16 [00:05<00:00,  2.92it/s]
Using already loaded model LimboMixV2.safetensors [60b0221b31]: done in 0.0s
Total progress: 100%|██████████████████████████████| 80/80 [01:50<00:00,  1.38s/it]
Total progress: 100%|██████████████████████████████| 80/80 [01:50<00:00,  1.43s/it]
```

### List of installed extensions

- Config-Presets
- a1111-sd-webui-tagcomplete
- adetailer
- multidiffusion-upscaler-for-automatic1111
- sd-dynamic-prompts
- sd-webui-agent-scheduler
- sd-webui-controlnet
- sd-webui-freeu, sd_civitai_extension
- stable-diffusion-webui-dataset-tag-editor
- stable-diffusion-webui-images-browser
- stable-diffusion-webui-model-toolkit

**Comment by iTeddyBe** [comment]
Hi, hollowstrawberry
What model of ADetailer are you using for "animal ears/animal earss" detection? (name.pt)

**Comment by Woisek** [comment]
Looks perfectly normal to me. ADetailer does some additional work, so the progress bar gets adjusted for each additional step.
And of course, it should be clear that the progress bar itself as no 100% accuracy, but is only an estimation.
The more important thing is that the process runs and finishes correctly, no matter what a percentage display says.

**Comment by hollowstrawberry** [comment]
> Hi, hollowstrawberry What model of ADetailer are you using for "animal ears/animal earss" detection? (name.pt)

https://civitai.com/models/157210
