### ISSUE TITLE
Feature Request: Option to restore last used pos and neg prompts in pass1 & 2 pos & neg fields

### ISSUE THREAD

**Issue by johneliot1978** [Bing-su/adetailer#39]
Would be really great to be able to store the pos and neg prompts for both 1st&2nd passes in a text file after each generate acrion, and have a button in ADetailer to restore last used prompts from previous sessions in A1111

especially now with the cool new multiple passes, it's 4 prompts fields to manually fenagle back into place each new session

**Comment by Bing-su** [comment]
![당신이원하는불러오기기능](https://github.com/Bing-su/adetailer/assets/37621276/93e548ce-c261-4ac3-8156-7f53a1dd76d5)
