### ISSUE TITLE
[Feature Request]: Lower Threshold

### ISSUE THREAD

**Issue by mayaponDL** [Bing-su/adetailer#396]
### Is your feature request related to a problem? Please describe.

For example, suppose I set the threshold of detection to 0.8 and as a result, three faces with a value of 0.83, 0.84 and 0.85 are detected.
If I want to enable ADtailer's effect on only one face of 0.84, It may be difficult to specify with the current settings.

### Describe the solution you'd like

I want to use ADtailer for only one face (main character) when multiple faces are detected with similar values.
I would like a function to specify a specific detection area or easily narrow the detection range.

### Describe alternatives you've considered

The current threshold value is the upper limit value, but by adding a lower limit value to it, you can specify the effective range of ADtailer.

e.g. 
       upper threshold (this is same as "Detection model confidence threshold") = 0.85
       lower threshold =0.83
       Then only a face of 0.84 can be detected.

### Additional context

I think there may be difficult cases even if you specify the Lower Threshold. In that case, it would be nice if you could specify one specific one, but there is a risk that ADtailer's GUI might become difficult to understand.

**Comment by Bing-su** [comment]
The problem here is that thresholds help us determine which objects are target objects, but they don't do much to tell us whether that object is something we really want.

There are other ways to filter based on the area of masks. Try these methods first please.
