### ISSUE TITLE
Is there a way to run ADetailer from command line?

### ISSUE THREAD

**Issue by AnnaPetrovicheva** [Bing-su/adetailer#398]
### Question

Hi! Thank you for creating ADetailer!

I want to run it from command line on Ubuntu. Is there a way to do this? Thank you!

**Comment by Bing-su** [comment]
As far as I know, there is no way to do that.

**Comment by up_the_irons** [comment]
You might be able to get something going on the command line by using the sd-webui API and adding ADetailer to the API call.  ADetailer supports being used through the API: https://github.com/Bing-su/adetailer/wiki/API

I actually just discovered that part over the weekend and will be doing some experimenting today. :)
