### ISSUE TITLE
[Feature Request]: IP adapter 

### ISSUE THREAD

**Issue by 2blackbar** [Bing-su/adetailer#399]
### Is your feature request related to a problem? Please describe.

When i select ip adapter in txt2img controlnet panel and feed it image to make similar one then it does wel but the face thats treated by adetailer totally ignores ip adapter from controlnet and in the end it does not transfet the style properly like it did with the whole body, i disabled adetailer and the face looks more close to ip adapter fed image.

### Describe the solution you'd like

can you make it work so it will check what controlnet is in use and it will use that controlnet for face inpaint in adetailer ? Maybe we could select a controlnet instance number to be used with adetailer ?

**Comment by valerian** [comment]
Did anyone find a good workaround to this problem?

**Comment by lhucklen** [comment]
Would still love to see this be developed
