### ISSUE TITLE
Feature Request: Option to save pre-ADetailer, Pass1 and Pass2 images for easier comparisons

### ISSUE THREAD

**Issue by johneliot1978** [Bing-su/adetailer#40]
Would be awesome to be able to tick a box and have intermediate versions saved, so a before adetailer, after 1st pass and after 2nd pass, to make comparison of each step easier when tweaking params

**Comment by Bing-su** [comment]
![여기있는옵션](https://github.com/Bing-su/adetailer/assets/37621276/9cdebdeb-b483-40a8-be1c-07b2d504811f)

**Comment by Aptronymist** [comment]
> Are the settings here not enough?

was going to say that myself!
I knew that existed and already had it turned on!
Loving the extension, thank you for your efforts! I tried to get a few of the forks of ddetailer working in Vlad's Automatic fork but no go, yours worked right out of the box!
Now I just have to figure out how to use it better, though I have noticed its effects, I even put TI's in the positive prompt and had it apply faces to some degree.
