### ISSUE TITLE
[Feature Request]:  Add Adetailed to Extra

### ISSUE THREAD

**Issue by ema7569** [Bing-su/adetailer#402]
### Is your feature request related to a problem? Please describe.

Please add Adetailer to extra tab, on option to upscale image because few time we don't have the the choice to recreate the entire image for various reasons. Image is too big, we do not have the prompt, we do not want to alter the rest of the image, ect...

**Comment by Woisek** [comment]
What do the extras tab different/better as the inpainting tab ... ? 🤔

**Comment by ema7569** [comment]
Ok you don't want... Bye.

**Comment by Ken-g6** [comment]
I have to say, the way to accomplish the goal discussed here - namely, running ADetailer on an existing image and doing nothing else - is not obvious.  The tab to use is the main img2img tab under Generation, not Inpaint.  Then, under ADetailer, check the "Skip img2img" checkbox.

I feel like an Extras tab entry might have been simpler, but it is what it is.
