### ISSUE TITLE
Is face_yolov8n_v2 available?

### ISSUE THREAD

**Issue by kuyin** [Bing-su/adetailer#41]
I downloaded face_yolov8n_v2.pt but it didn't show up in the model list.

**Comment by Bing-su** [comment]
There's no refresh button, so you'll have to shut it down and turn it back on.

**Comment by alenknight** [comment]
where do we put this? i saw in instructions says put in webui/models/adetailer... but in my SD install, i don't see that folder there.  in extensions i have adetailer... but there's no models folder.

**Comment by Bing-su** [comment]
If you don't have one, just create folder and put it in.
