### ISSUE TITLE
[Bug]: Skip Img2Img not working with multiple Adetailer instances

### ISSUE THREAD

**Issue by majorsauce** [Bing-su/adetailer#410]
### Describe the bug

When running two or more A-Detailer instances with skip img2img option enabled, only the last instance takes effect.
Eg: 
Adetailer 1st inpaints on input image
Adetailer 2nd inptains on input image too, work from 1st is lost
 
I know I´m running the unsupported vladmandic/automatic version but verified with another user on auto1111 the same behaviour.

### Console logs, from start to end.

```Shell
11:27:26-872202 INFO     Starting SD.Next
11:27:26-911201 INFO     Python 3.10.11 on Windows
11:27:27-228203 INFO     Version: app=sd.next updated=2023-11-13 hash=f1862579 url=https://github.com/vladmandic/automatic.git/tree/master
11:27:28-502356 INFO     Platform: arch=AMD64 cpu=AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.11
11:27:28-525357 INFO     nVidia CUDA toolkit detected: nvidia-smi present
```

### List of installed extensions

'Lora'
'sd-extension-chainner'
'sd-extension-system-info'
'sd-webui-agent-scheduler'
'sd-webui-controlnet'
'stable-diffusion-webui-images-browser'
'stable-diffusion-webui-rembg'
'adetailer'
'sd-webui-infinite-image-browsing'
'stable-diffusion-webui-Layer-Divider'
'TemporalKit'

**Comment by Bing-su** [comment]
I made a stupid mistake, I'll fix it soon.

**Comment by majorsauce** [comment]
@Bing-su actually created a PR for this.
There´s also a second issue where [vladmandic/automatic](https://github.com/vladmandic/automatic) transforms the init_img to an numpy.ndarray datatype which cannot be processed by adetailer when using Skip Img2Img

**Comment by fifskank** [comment]
>>>SOLVED<<<
i updated winodws and my AMD adrenalin drivers too, and it fixed it, i also removed some extensions i didnt use, DeepBooru recognition and Deepbooru Tag2Folder, i tried out those 2 extensions but the normal Train deepbooru image process does the same thing and has the flipped image option, the other ones dont have that, so i removed those updated an Boooommm ready to roll !!!!
