### ISSUE TITLE
[Feature Request]: Automatically adjust prompt when specific detections found, from mapped detection -> prompt

### ISSUE THREAD

**Issue by hassan-sd** [Bing-su/adetailer#412]
### Describe the solution you'd like

As aDetailer detects things in our images based on the model we are using, then inpaints/enhances the image based on the prompt we have, it would be great to allow automatic mapping of prompts based on what is detected.

_**### An example flow would be:**_

- I create a custom mapping for adetailer, if  "`shoes`" are detected, "`nike white trainers, detailed shoes, nike logo <lora:mylorahere:5>`" is added to the adetailer prompt. 
- I create a second custom mapping for "`watch`" so if a wrist watch is detected via my ultralytics model, the prompt "`shiny silver rolex watch, detailed watch face, intricate chronograph watch face`" is added to the prompt

1: Image is generated of a person standing in front of a mirror
2: Adetailer runs, a custom ultralytics model is loaded to detect `shoes ` based on the confidence, ie 0.75 and it triggers the next change
3: As shoes are detected , my adetailer prompt is updated with the mapped prompt we configured.  `nike white trainers, detailed shoes, nike logo <lora:mylorahere:5>`
4: Adetailer continues it's logic to enhance the image but with the new prompt modification.

Allow this for multiple mappings, so if it detects both shoes and a watch, it then updates the prompt with both mappings included. 

### Benefits
After the first image is generated, our prompt is dynamically updated to be more tailored to improve the image, based on user mapped values of what is important for this image.

**Comment by Bing-su** [comment]
It's a great idea. Maybe a model like [fuyu](https://huggingface.co/adept/fuyu-8b) could be used here. But it seems better to have the actual implementation in a separate repository, not here.
