### ISSUE TITLE
[Bug]: Metadata is wrong in some instances

### ISSUE THREAD

**Issue by Nrgte** [Bing-su/adetailer#413]
### Describe the bug

Hello

There are a couple of issues with the metadata.

1. If I use a lora in ADetailer, it will overwrite all the previous lora hashes with the one used during the last generation. So all the lora hashes from the main prompt get overwritten if I use a lora in ADetailer.

2. If I use the dynamic prompts extension alongside ADetailer, it doesn't write the replaced values into the metadata.

Example face prompt: "young man, {green|blue} eyes"

ADetailer correctly triggers the dynamicprompts extension and writes a message in the log in green font: "young man, green eyes", however the metadata of the image shows the base prompt instead of the replaced prompt.

Thanks!

### Console logs, from start to end.

```Shell
-
```

**Comment by Bing-su** [comment]
It didn't seem to have much usability relative to the difficulty of implementation, so I left it as is.

**Comment by Nrgte** [comment]
@Bing-su May I ask what's difficult to implement? I mean you're already printing the values out in green text to the console that I've mentioned in point 1. So pushing that to the metadata instead of the generic one should be quite straight forward.

I understand that point 2 may be a bit tricky.

If you can give me some loose guidance on what's the hurdle I may be able to help.

Thanks!

**Comment by Bing-su** [comment]
Because the metadata is created before the image is created, it becomes cumbersome to modify the metadata again after the image is created.
