### ISSUE TITLE
[Bug]: I updated ADetailer then SD dont start

### ISSUE THREAD

**Issue by Adzido** [Bing-su/adetailer#420]
### Describe the bug

I updated ADetailer today and then SD dont want to start. If I remove the ext everything works as it should. Probably a conflict with something else after the update, but I don't know which addon. I also added a list with my installed plug-ins. Any ideas?

### Screenshots

![obraz](https://github.com/Bing-su/adetailer/assets/136247258/f08de7e0-b261-40d7-9657-496c3107470b)
![obraz](https://github.com/Bing-su/adetailer/assets/136247258/8eaa3814-9b25-4a3b-a895-09cec5e2df78)

### Console logs, from start to end.

```Shell
venv "C:\Users\AdziOo\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
```

**Comment by ewilli** [comment]
Same here.
