### ISSUE TITLE
[Feature Request]: ADetailer seed

### ISSUE THREAD

**Issue by roselma** [Bing-su/adetailer#426]
### Is your feature request related to a problem? Please describe.

Inpainting doesn't always work the first try.  ADetailer is a great tool, but there is no good way to vary the generations it automates without varying the initial image.  In effect, if ADetailer doesn't get it right the first try, you're out of luck and back to manual inpainting.

### Describe the solution you'd like

An optional ADetailer seed—preferably one per ADetailer pane/model—would allow one to make multiple attempts at getting desirable details without changing the base generation.

### Describe alternatives you've considered

Today, I tweak ADetailer settings in such a way that they perturb the output but still conform to what I am looking for; however, there are only so many ways to do this and of course each has small side-effects since the parameter does actually control something.

### Additional context

If this feature is seen as a potentially useful addition but you lack the time to write it, if you'll give me a pointer or two on where to start, I might take a stab at it and submit a PR.

**Comment by Bing-su** [comment]
시드를 변경해서 다시 생성하는 것과 같은 작업은 img2img탭으로 이미지를 보내서 작업하는 것을 추천드립니다
