### ISSUE TITLE
How to collapse the Adetailer area?

### ISSUE THREAD

**Issue by carnivar10** [Bing-su/adetailer#427]
### Question

<img width="469" alt="ask" src="https://github.com/Bing-su/adetailer/assets/141563521/4e3cda05-98a6-4563-aff7-d802126bd5a4">

첨부한 이미지처럼 Adetailer를 사용할 경우 model이 적용된 곳에 네모 범위가 같이 나타나는데 해당 영역을 최대한 줄일 수 있는 방법이 있나요? 손가락과 동일하게 줄일 수는 없더라도 최대한 줄여볼 수 없을지 궁금합니다 (기능 상으로는 지원하는 것 같아 보이는데 어느 옵션을 손대야 할지 모르겠습니다)

When I use Adetailer, like in the attached image, a square range appears where the model is applied, is there any way to reduce that area as much as possible? I'm wondering if it's possible to reduce it as much as possible, even if it's not possible to reduce it to the same size as a finger (it looks like the functionality supports it, but I don't know which option to change)

**Comment by carnivar10** [comment]
질문의 요지는 결국 사각형 프레임을 보이지 않게 하는 것입니다 (The point of the question is to eventually make the rectangle frame invisible)

**Comment by Bing-su** [comment]
사실 저도 잘 모릅니다
