### ISSUE TITLE
something changed with torch2?

### ISSUE THREAD

**Issue by alenknight** [Bing-su/adetailer#43]
After updating to Torch 2, i did a fresh install of SD.... in img2img i use Controlnet Tile + Ultimate SD Upscaler (4xultrasharp)....and aDetailer.  
when i turn on ADETAILER, the faces are a garbled mess now.... when i turn it off.... it's working same as it was before the Torch update ....
is there some incompatibility or change that you know of that would cause this?

**Comment by Bing-su** [comment]
I've only tested with torch 2.0, and the output will vary depending on your settings.
