### ISSUE TITLE
[Feature Request]: 추가프롬프트 기능 추가

### ISSUE THREAD

**Issue by ThisisLandu** [Bing-su/adetailer#436]
### Is your feature request related to a problem? Please describe.

Adetailer 사용시 새로 사용할 프롬프트를 작성할수도 있고
아예 아무것도 작성 안할시, 기존의 프롬프트를 사용해서 할수도 있는데
기존의 프롬프트에 추가할 프롬프트만 작성할수 있게 기능 추가 될까요??

지금 face detector 외에도 다른 detector도 많이 나와서
해당부분에 대한 로라나 프롬프트를 추가로 사용하고 싶은데(hand나 특정 부위....)

이미지생성시의 프롬프트에 {}를 사용해 랜덤으로 설정해놨는데
detect하고 변경하고 싶은 부분을 프롬프트로 직접 지정해버리면, 그 부분만 강조되서 나옵니다;

즉 '찾고자 하는 부위가 있으면, 다시 그려라'  로 설정하고싶은데

현재 이렇게 사용하려면
프롬프트 주어질때마다  **기존프롬프트+추가하고자 하는 내용**  를 적어야하는데

개선시 **추가하고자 하는 내용**  만 적게끔 설정할수 있으면 좋겠읍니다...(web ui config 설정으로 변경 안해도 되게끔)

**Comment by Bing-su** [comment]
`[PROMPT] 추가하려는 프롬프트` 처럼 작성해보세요.

**Comment by ThisisLandu** [comment]
> `[PROMPT] 추가하려는 프롬프트` 처럼 작성해보세요.

Adetailer에서 추가하고픈 프롬이 'beautiful' 이라하면, adetailer 프롬에 [PROMPT] beautiful로 했는데 exif 정보보니 '[PROMPT] beautiful' 그대로 들어가네요 ㅠㅠ

제가 하고픈 부위가 얼굴이 아니라 특정부위긴한데... 이걸 adetailer 말고 positive prompt에 넣으면 NSFW가 너무 강조되서 나와서요...
그래서 무작위로 생성된 이미지 중 해당 부위가 있으면 수정하게끔 하고 싶은데
제가 제안한 방법은 매번 바뀌는 positive prompt를 adetailer prompt에 안적어줘도 되게끔 하는 방법입니다...
