### ISSUE TITLE
[Feature Request]: Allow up to four adetailer runs

### ISSUE THREAD

**Issue by luotinen** [Bing-su/adetailer#440]
### Is your feature request related to a problem? Please describe.

The problem: I want to run four adetailers: face, hands, and two more body parts

### Describe the solution you'd like

Preferred solution: four tabs instead of two tabs, therefore enabling 1-4 adetailers to be run 

### Describe alternatives you've considered

Alternative: running two adetailers, then running again two adetailers - cumbersome but it works

### Additional context

The additional adetailers can be downloaded (for example) from Civitai

**Comment by Bing-su** [comment]
please see the setting tab, this option already exists
