### ISSUE TITLE
[Missing model] Such as face_yolov8n hand_yolov8n is missing

### ISSUE THREAD

**Issue by wanStu** [Bing-su/adetailer#444]
### Question

Such as face_yolov8n hand_yolov8n is missing
![图片](https://github.com/Bing-su/adetailer/assets/49781112/8689ac9a-27ba-4031-94de-b587fd03bcfe)
![图片](https://github.com/Bing-su/adetailer/assets/49781112/caf2b4c8-d592-4135-9efc-721e1923dc9e)

**Comment by Bing-su** [comment]
Only Chinese users seem to be experiencing this issue.
https://huggingface.co/Bingsu/adetailer/tree/main
Get the file directly from there and put it in your models/adetailer folder.

**Comment by Pervertica** [comment]
I also had the same problem. all yolov8n models were available before but suddenly got disappeared today. I completely restarted (not reload) the webui and they came back.
