### ISSUE TITLE
The API call is resulting in an error!

### ISSUE THREAD

**Issue by Wester1220** [Bing-su/adetailer#45]
![Snipaste_2023-05-13_06-53-07](https://github.com/Bing-su/adetailer/assets/11775508/ee8147b4-e444-4e86-a725-9391dfcca386)
![Snipaste_2023-05-13_06-53-45](https://github.com/Bing-su/adetailer/assets/11775508/31aee3c2-7d39-4b1e-aa44-94423072c440)

This is a great plugin.
I followed the instructions in **args.py** file for setup, but for some reason, I'm encountering an error.

**Comment by Bing-su** [comment]
You sent `ad_use_cfg_scale` as `None`. Options will be added as I update. I apologise for this.

**Comment by Bing-su** [comment]
I've made some big changes to API usage. Please see the wiki.
