### ISSUE TITLE
[Bug]: ADetailer: img2img inpainting detected. adetailer disabled.

### ISSUE THREAD

**Issue by k99goran** [Bing-su/adetailer#455]
### Describe the bug

Hi,

I just updated Adetailer to the latest version, now it won't allow me to run in inpaint mode.
I made sure that the "Skip img2img" checkbox is unchecked, and I don't see any options in Settings that allow me to turn it back on.
It just prompts this error message:
ADetailer: img2img inpainting detected. adetailer disabled.

How do I resolve this?

### Console logs, from start to end.

```Shell
venv "E:\Programs\Automatic1111\stable-diffusion-webui-master\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0
Commit hash: <none>
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers --no-half
[-] ADetailer initialized. version: 23.12.0, num models: 11
ControlNet preprocessor location: E:\Programs\Automatic1111\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\downloads
2023-12-31 13:27:33,359 - ControlNet - INFO - ControlNet v1.1.425
2023-12-31 13:27:33,428 - ControlNet - INFO - ControlNet v1.1.425
13:27:33 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [676f0d60c8] from E:\Programs\Automatic1111\stable-diffusion-webui-master\models\Stable-diffusion\SDXL turbo\dreamshaperXL_turboDpmppSDEKarras.safetensors
2023-12-31 13:27:33,901 - AnimateDiff - INFO - Injecting LCM to UI.
2023-12-31 13:27:34,173 - AnimateDiff - INFO - Hacking i2i-batch.
Running on local URL:  http://127.0.0.1:7860

[-] ADetailer: img2img inpainting detected. adetailer disabled.
2023-12-31 13:30:51,404 - ControlNet - INFO - unit_separate = False, style_align = False
2023-12-31 13:30:51,621 - ControlNet - INFO - Loading model: ipAdapterControlnet_sdxl [bc449f62]
2023-12-31 13:30:51,630 - ControlNet - INFO - Loaded state_dict from [E:\Programs\Automatic1111\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\ipAdapterControlnet_sdxl.safetensors]
2023-12-31 13:30:53,261 - ControlNet - INFO - ControlNet model ipAdapterControlnet_sdxl [bc449f62] loaded.
2023-12-31 13:30:53,437 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sdxl_plus_vith
2023-12-31 13:30:53,437 - ControlNet - INFO - preprocessor resolution = 1280
2023-12-31 13:31:01,133 - ControlNet - INFO - ControlNet Hooked - Time = 9.735368967056274
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.03it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.42s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.23it/s]

```

**Comment by etreto** [comment]
I was wondering if it's a bug or an intended feature. The latest commit makes it seem intended but I'm unsure why you'd want to disable in inpaint.

I've fixed it by going to
<repo dir>\extensions\adetailer\scripts\

Edit !detailer.py
Look for "def is_img2img_inpaint"
Change the return to False

Save and restart SD.

**Comment by k99goran** [comment]
Yes. I just saw it in the latest changelog. Very strange to arbitrarily limit such a great feature.

Anway, the fix worked. Thanks for the quick help!

**Comment by iiiiik06** [comment]
After I tried to change it, the ADetailer was completely gone from the page.

**Comment by FlorentMasseglia** [comment]
Thank you Etroto!! It works.

**Comment by ElevatedKitten** [comment]
can we please revisit whether this is intended behavior or actually a bug? for me it doesn't really make sense to deactivate adetailer for inpainting either. by the way, not only inpainting is affected by this change, but generally everything that has to do with img2img. if you want to upscale via img2img, for example, adetailer also no longer works.

and tbh manually changing values in *.py files isn't exactly a good solution to fix this.

imo this issue shouldn't be marked als closed and complete

@Bing-su any thoughts on this?

**Comment by k99goran** [comment]
Perhaps I jumped the gun when closing this issue. Should I reopen it?

**Comment by Bing-su** [comment]
It's working fine for me, but how are you guys doing this? This is to prevent a bug with nested inpaints that was often reported in the past.

![스크린샷 2024-01-04 003222](https://github.com/Bing-su/adetailer/assets/37621276/78b58eed-f90c-4ec9-90a5-14a98c469fe3)

```sh
0: 640x448 1 face, 5.0ms
Speed: 1.0ms preprocess, 5.0ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 448)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  7.61it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 9/9 [00:06<00:00,  1.43it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.84it/s]
Total progress:   0%|                                                                            | 0/1 [00:00<?, ?it/s]
0: 640x512 1 face, 84.7ms
Speed: 2.7ms preprocess, 84.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 512)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  7.30it/s]

0: 640x512 1 face, 6.5ms
Speed: 1.0ms preprocess, 6.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 512)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  7.59it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.67s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.24it/s]
Total progress:   0%|                                                                            | 0/1 [00:00<?, ?it/s]
0: 640x512 1 face, 79.6ms
Speed: 3.5ms preprocess, 79.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 512)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  5.54it/s]

0: 640x512 1 face, 5.2ms
Speed: 2.6ms preprocess, 5.2ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 512)
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  7.64it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.05s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:06<00:00,  6.05s/it] 
```

**Comment by coderCK2** [comment]
> It's working fine for me, but how are you guys doing this? This is to prevent a bug with nested inpaints that was often reported in the past.

I'm also experiencing this issue, and I'm simply going from txt2img to img2img by clicking the "Send image and generation parameters to img2img tab." button underneath the original image.

**Comment by phopeu** [comment]
> After I tried to change it, the ADetailer was completely gone from the page.

Had the same issue, commenting out the whole block fixed it. 
![Untitled](https://github.com/Bing-su/adetailer/assets/101328049/74ef3e54-b2e9-49f7-a04d-ef1a0906e7bc)

**Comment by Woisek** [comment]
> I was wondering if it's a bug or an intended feature. The latest commit makes it seem intended but I'm unsure why you'd want to disable in inpaint.
> 
> I've fixed it by going to \extensions\adetailer\scripts\
> 
> Edit !detailer.py Look for "def is_img2img_inpaint" Change the return to False
> 
> Save and restart SD.

Somehow, there is no return for true or false.
```
    @staticmethod
    def is_img2img_inpaint(p) -> bool:
        return hasattr(p, "image_mask") and bool(p.image_mask)
```

**Comment by coderCK2** [comment]
> Somehow, there is no return for true or false.

What do you mean exactly?
All you need to do is change this:
```python
@staticmethod
def is_img2img_inpaint(p) -> bool:
    return hasattr(p, "image_mask") and bool(p.image_mask)
```
to this:
```python
@staticmethod
def is_img2img_inpaint(p) -> bool:
    return False
```

Or if you want to preserve the original line in case you want to revert (for whatever reason), you can comment it and add your new line below it, like this:
```python
@staticmethod
def is_img2img_inpaint(p) -> bool:
    # return hasattr(p, "image_mask") and bool(p.image_mask)
    return False
```

**Comment by Woisek** [comment]
> > Somehow, there is no return for true or false.
> 
> What do you mean exactly? All you need to do is change this:
> 
> ```python
> @staticmethod
> def is_img2img_inpaint(p) -> bool:
>     return hasattr(p, "image_mask") and bool(p.image_mask)
> ```
> 
> to this:
> 
> ```python
> @staticmethod
> def is_img2img_inpaint(p) -> bool:
>     return False
> ```
> 
> Or if you want to preserve the original line in case you want to revert (for whatever reason), you can comment it and add your new line below it, like this:
> 
> ```python
> @staticmethod
> def is_img2img_inpaint(p) -> bool:
>     # return hasattr(p, "image_mask") and bool(p.image_mask)
>     return False
> ```

Okay, that's something different. I thought there was a true that has to be changed to a false. I'll try that, thanks. 👍

**Comment by THATDONFC** [comment]
I'm also seeing this issue. I upscaled an image 2x and then sent that upscaled image to img2img to upscale again. I wanted to touch up the face using adetailer but I keep seeing this message in the console at the start of the generation:

`[-] ADetailer: img2img inpainting detected. adetailer disabled.`

**Comment by halfblack** [comment]
Will this be addressed, or manual code change gonna be necessary all the time?

**Comment by ENTPRESTIGIOUS** [comment]
I have the same issue on v1.7.0 

```
ADetailer: img2img inpainting detected. adetailer disabled.
```

**Comment by EtienneDosSantos** [comment]
> I have the same issue on v1.7.0
> 
> ```
> ADetailer: img2img inpainting detected. adetailer disabled.
> ```

Edit the section in !adetailer.py file (follow this path to find it: \stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py) from
```
    @rich_traceback
    def process(self, p, *args_):
        if getattr(p, "_ad_disabled", False):
            return

        if self.is_img2img_inpaint(p):
            p._ad_disabled = True
            msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
            print(msg)
            return

        if self.is_ad_enabled(*args_):
            arg_list = self.get_args(p, *args_)
            self.check_skip_img2img(p, *args_)
            extra_params = self.extra_params(arg_list)
            p.extra_generation_params.update(extra_params)
        else:
            p._ad_disabled = True
```
to
```
    @rich_traceback
    def process(self, p, *args_):
        if getattr(p, "_ad_disabled", False):
            return

        if self.is_img2img_inpaint(p):
            p._ad_disabled = False
            msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
            print(msg)
            return

        if self.is_ad_enabled(*args_):
            arg_list = self.get_args(p, *args_)
            self.check_skip_img2img(p, *args_)
            extra_params = self.extra_params(arg_list)
            p.extra_generation_params.update(extra_params)
        else:
            p._ad_disabled = False
```

**Comment by humanoide13** [comment]
> I was wondering if it's a bug or an intended feature. The latest commit makes it seem intended but I'm unsure why you'd want to disable in inpaint.
> 
> I've fixed it by going to \extensions\adetailer\scripts\
> 
> Edit !detailer.py Look for "def is_img2img_inpaint" Change the return to False
> 
> Save and restart SD.

Thanks! It worked.

**Comment by malfdawg** [comment]
Is this bug ever going to be addressed?! It happens on standard img2img not just inpainting tab.

**Comment by EtienneDosSantos** [comment]
> Is this bug ever going to be addressed?! It happens on standard img2img not just inpainting tab.

Seems like it's not a bug, but a feature.

**Comment by malfdawg** [comment]
> > Is this bug ever going to be addressed?! It happens on standard img2img not just inpainting tab.
> 
> Seems like it's not a bug, but a feature.

How can it be a feature if it occurs even when there is no inpainting? It specifically says "inpainting detected adetailer disabled."

**Comment by EtienneDosSantos** [comment]
> > > Is this bug ever going to be addressed?! It happens on standard img2img not just inpainting tab.
> > 
> > 
> > Seems like it's not a bug, but a feature.
> 
> How can it be a feature if it occurs even when there is no inpainting? It specifically says "inpainting detected adetailer disabled."

Hmm, this is strange. Just tested it and it doesn't happen in normal img2img for me.

**Comment by EtienneDosSantos** [comment]
Aight, you did the best thing (modifying the script).

**Comment by akmesb** [comment]
> Edit !detailer.py Look for "def is_img2img_inpaint" Change the return to False

Changing the script just makes the message disappear. ADetailer does its job, but the result is not embedded. I get just the original.

I have the suspicion that ADetailer should not work for this way for copyright reasons, because one could manipulate any photo in a lifelike way, while all other face-swap methods (currently) still deliver poor results and are almost always recognizable as manipulation.

**Comment by halfblack** [comment]
> > Edit !detailer.py Look for "def is_img2img_inpaint" Change the return to False
> 
> Changing the script just makes the message disappear. ADetailer does its job, but the result is not embedded. I get just the original.
> 
> I have the suspicion that ADetailer should not work for this way for copyright reasons, because one could manipulate any photo in a lifelike way, while all other face-swap methods (currently) still deliver poor results and are almost always recognizable as manipulation.

Then you must've done something wrong, as for me adetailer does work after changing this line. As for the reasoning, ReActor and other tools offer much better and reliable options for face swapping, while adetailer is not only not exclusive to face adjustments, but also works on fundamentally different principle.

**Comment by malfdawg** [comment]
> > Edit !detailer.py Look for "def is_img2img_inpaint" Change the return to False
> 
> Changing the script just makes the message disappear. ADetailer does its job, but the result is not embedded. I get just the original.
> 
> I have the suspicion that ADetailer should not work for this way for copyright reasons, because one could manipulate any photo in a lifelike way, while all other face-swap methods (currently) still deliver poor results and are almost always recognizable as manipulation.

Adetailer is not a faceswap. It's just inpainting.  You could do exactly what it's doing by inpainting with your own mask. Having it auto detect a face, mask, and inpaint on-the-fly, is the convenience Adetailer offers, but at the end of the day it just an inpaint, which has no 'copyright protection'.

**Comment by malfdawg** [comment]
> I'm also seeing this issue. I upscaled an image 2x and then sent that upscaled image to img2img to upscale again. I wanted to touch up the face using adetailer but I keep seeing this message in the console at the start of the generation:
> 
> `[-] ADetailer: img2img inpainting detected. adetailer disabled.`

This is the biggest issue for me. Adetailer is disabling itself when merely upscaling in img2img. Why? I now have to run img2img again after upscaling with 'Skip img2img' checked. This takes 10x longer than just letting adetailer run during the upscale. 

If this is a feature and not a bug, it's a bad one. The author should consider changing it.

**Comment by MathDC99** [comment]
For me same problem, Adetailer deactivates itself even after modifying "!adetailer.py" and restarting the web.ui:
"[-] ADetailer: img2img inpainting detected. adetailer disabled" in img2img, inpaint.
I have version 24.1.2. Wouldn't there be a more stable version? Or would reinstalling Adetailer not solve the problem?...

**Comment by ArnorWing** [comment]
arghh this is really annoying. All i want is adetailer to tidy up folders of images.

**Comment by EtienneDosSantos** [comment]
> For me same problem, Adetailer deactivates itself even after modifying "!adetailer.py" and restarting the web.ui: "[-] ADetailer: img2img inpainting detected. adetailer disabled" in img2img, inpaint.
> 
> I have version 24.1.2. Wouldn't there be a more stable version? Or would reinstalling Adetailer not solve the problem?...

I don't think that reinstalling would do anything, since the "inpainting detected, adetailer disabled" is specifically implemented into all versions post [v23.11.1](https://github.com/Bing-su/adetailer/releases/tag/v23.11.1). I rolled back to v23.11.1 for that reason.

**Comment by ArnorWing** [comment]
Adetailer seems to work in I2I if Ultimate Upscale is not enabled ... BUT the generation takes a really long time, i closed the console at about 10mins on my 3090. 
Someone check that as well?
-Disable I2I in Adetailer
-Use tiled VAE
-Disable Ultimate Upscale.

**Comment by Mejnun333** [comment]
> > I have the same issue on v1.7.0
> > ```
> > ADetailer: img2img inpainting detected. adetailer disabled.
> > ```
> 
> As @etreto suggested, edit the section in !adetailer.py file (follow this path to find it: \stable-diffusion-webui\extensions\adetailer\scripts!adetailer.py) from
> 
> ```
>     @rich_traceback
>     def process(self, p, *args_):
>         if getattr(p, "_ad_disabled", False):
>             return
> 
>         if self.is_img2img_inpaint(p):
>             p._ad_disabled = True
>             msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
>             print(msg)
>             return
> 
>         if self.is_ad_enabled(*args_):
>             arg_list = self.get_args(p, *args_)
>             self.check_skip_img2img(p, *args_)
>             extra_params = self.extra_params(arg_list)
>             p.extra_generation_params.update(extra_params)
>         else:
>             p._ad_disabled = True
> ```
> 
> to
> 
> ```
>     @rich_traceback
>     def process(self, p, *args_):
>         if getattr(p, "_ad_disabled", False):
>             return
> 
>         if self.is_img2img_inpaint(p):
>             p._ad_disabled = False
>             msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
>             # print(msg)
>             return
> 
>         if self.is_ad_enabled(*args_):
>             arg_list = self.get_args(p, *args_)
>             self.check_skip_img2img(p, *args_)
>             extra_params = self.extra_params(arg_list)
>             p.extra_generation_params.update(extra_params)
>         else:
>             p._ad_disabled = False
> ```

Thank you!

**Comment by yvliew** [comment]
> > I have the same issue on v1.7.0
> > ```
> > ADetailer: img2img inpainting detected. adetailer disabled.
> > ```
> 
> As @etreto suggested, edit the section in !adetailer.py file (follow this path to find it: \stable-diffusion-webui\extensions\adetailer\scripts!adetailer.py) from
> 
> ```
>     @rich_traceback
>     def process(self, p, *args_):
>         if getattr(p, "_ad_disabled", False):
>             return
> 
>         if self.is_img2img_inpaint(p):
>             p._ad_disabled = True
>             msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
>             print(msg)
>             return
> 
>         if self.is_ad_enabled(*args_):
>             arg_list = self.get_args(p, *args_)
>             self.check_skip_img2img(p, *args_)
>             extra_params = self.extra_params(arg_list)
>             p.extra_generation_params.update(extra_params)
>         else:
>             p._ad_disabled = True
> ```
> 
> to
> 
> ```
>     @rich_traceback
>     def process(self, p, *args_):
>         if getattr(p, "_ad_disabled", False):
>             return
> 
>         if self.is_img2img_inpaint(p):
>             p._ad_disabled = False
>             msg = "[-] ADetailer: img2img inpainting detected. adetailer disabled."
>             # print(msg)
>             return
> 
>         if self.is_ad_enabled(*args_):
>             arg_list = self.get_args(p, *args_)
>             self.check_skip_img2img(p, *args_)
>             extra_params = self.extra_params(arg_list)
>             p.extra_generation_params.update(extra_params)
>         else:
>             p._ad_disabled = False
> ```

Tried this and also return Flase, adetailer still wont work in inpainting. Any other methods? How do I roll back previous version?

**Comment by EtienneDosSantos** [comment]
> How do I roll back previous version?

Assuming you want to use the version without adetailer deactivation upon inpainting implemented:
1) Download the zip file of [v23.11.1](https://github.com/Bing-su/adetailer/releases/tag/v23.11.1)
2) Extract the data from the zip file and put it in the extensions folder of your stable-diffusion-webui directory
3) Open command prompt and navigate to the folder you just pasted there in 2)
4) Create a virtual environment using the command: `python -m venv adetailer_venv`
5) Activate the newly created adetailer_venv with: `adetailer_venv\Scripts\activate`
6) Run `python install.py`
7) Hit `deactivate` after install.py has finished and close the command prompt
8) Start stable-diffusion-webui normally and adetailer should work

**Comment by akmesb** [comment]
> > How do I roll back previous version?
> 
> Assuming you want to use the version without adetailer deactivation upon inpainting implemented:
> 
>     1. Download the zip file of [v23.11.1](https://github.com/Bing-su/adetailer/releases/tag/v23.11.1)
> 
>     2. Extract the data from the zip file and put it in the extensions folder of your stable-diffusion-webui directory
> 
>     3. Open command prompt and navigate to the folder you just pasted there in 2)
> 
>     4. Create a virtual environment using the command: `python -m venv adetailer_venv`
> 
>     5. Activate the newly created adetailer_venv with: `adetailer_venv\Scripts\activate`
> 
>     6. Run `python install.py`
> 
>     7. Hit `deactivate` after install.py has finished and close the command prompt
> 
>     8. Start stable-diffusion-webui normally and adetailer should work

Why so complicated? Stable-diffusion-webui does all this completely automatically at next startup anyway.

**Comment by EtienneDosSantos** [comment]
> > > How do I roll back previous version?
> > 
> > 
> > Assuming you want to use the version without adetailer deactivation upon inpainting implemented:
> > ```
> > 1. Download the zip file of [v23.11.1](https://github.com/Bing-su/adetailer/releases/tag/v23.11.1)
> > 
> > 2. Extract the data from the zip file and put it in the extensions folder of your stable-diffusion-webui directory
> > 
> > 3. Open command prompt and navigate to the folder you just pasted there in 2)
> > 
> > 4. Create a virtual environment using the command: `python -m venv adetailer_venv`
> > 
> > 5. Activate the newly created adetailer_venv with: `adetailer_venv\Scripts\activate`
> > 
> > 6. Run `python install.py`
> > 
> > 7. Hit `deactivate` after install.py has finished and close the command prompt
> > 
> > 8. Start stable-diffusion-webui normally and adetailer should work
> > ```
> 
> Why so complicated? Stable-diffusion-webui does all this completely automatically at next startup anyway.

Oh, so you simply put the folder in the extensions directory and it will work? Super easy then!

**Comment by warrockmill** [comment]
Well I tried the fix and had no luck. Rolling back also did nothing in the end. This change has really made a chore of my workflow.

**Comment by highnrgappalachian** [comment]
Why is this a thing? Lmao.

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.semlinker, @Quincynickyoung, @Sheesh14, @gateixeira, @AbraxasN, @l294265421, @NormaRad5, @tooxin, @dreamYiZ, @klonggan, @Luckydayez, @luobende, @netveil, @bitburner, @AnandTeachesPython, @nikvizio, @Minchi-Tsai, @zhanshijinwat, @manhbq-2536-1, @baiheinet

**Comment by ENTPRESTIGIOUS** [comment]
Damn, still no fix? But yeah changing those values to `False` didn't do anything.

**Comment by ENTPRESTIGIOUS** [comment]
> [arafatx](https://github.com/arafatx) added a commit to arafatx/adetailer that referenced this issue [2 weeks ago](https://github.com/Bing-su/adetailer/issues/455#ref-commit-f87c83c)
@arafatx
[Update !adetailer.py](https://github.com/arafatx/adetailer/commit/f87c83ca6ccb9d4454f93f5ade51b3990970beab)

It starts the ADetailer process but once it's finished, it gets discarded.

**Comment by kalle07** [comment]
why ADetailer is working with SD15 in inpaint but SDXL dont ?

**Comment by omartanveer** [comment]
Installing the older version of Adetailer worked for me
Installation URL: https://gitee.com/JonyShan/adetailer.git

**Comment by ENTPRESTIGIOUS** [comment]
> Installing the older version of Adetailer worked for me Installation URL: https://gitee.com/JonyShan/adetailer.git

Wait wha?

**Comment by omartanveer** [comment]
For me, installing the latest version resulted in this error ADetailer: img2img inpainting detected. adetailer disabled

So, i shifted to the older version. Removed the latest version and installed the older version from the extensions tab, using the URL mentioned above. Thereafter, in the installed tab, i didn't click "check for updates" and clicked "Apply and Restart UI"

**Comment by ENTPRESTIGIOUS** [comment]
> For me, installing the latest version resulted in this error ADetailer: img2img inpainting detected. adetailer disabled
> 
> So, i shifted to the older version. Removed the latest version and installed the older version from the extensions tab, using the URL mentioned above. Thereafter, in the installed tab, i didn't click "check for updates" and clicked "Apply and Restart UI"

I thought that didn't work for someone else. Kinda sad that you have to downgrade...

**Comment by omartanveer** [comment]
> > For me, installing the latest version resulted in this error ADetailer: img2img inpainting detected. adetailer disabled
> > So, i shifted to the older version. Removed the latest version and installed the older version from the extensions tab, using the URL mentioned above. Thereafter, in the installed tab, i didn't click "check for updates" and clicked "Apply and Restart UI"
> 
> I thought that didn't work for someone else. Kinda sad that you have to downgrade...

Yep, but its still better than getting an error.

**Comment by highnrgappalachian** [comment]
@Bing-su Could you revert this change, please?

**Comment by ArnorWing** [comment]
> > Installing the older version of Adetailer worked for me Installation URL: https://gitee.com/JonyShan/adetailer.git
> 
> Wait wha?

I wouldnt use that link. Looks suspect

**Comment by k52252467** [comment]
Can't this problem be fixed? 
Every time I update, I have to manually change !detailer.py

**Comment by Bing-su** [comment]
The restriction on this issue has been relaxed since version 24.3.1.
If you are still experiencing similar issues, please open an issue as this is probably a different issue.
