### ISSUE TITLE
Sort bounding boxes via the API

### ISSUE THREAD

**Issue by inverherive** [Bing-su/adetailer#457]
### Question

Apologies if I've missed it in the API documentation, but how do I specify the bounding boxes sort direction via the API?

**Comment by Bing-su** [comment]
![스크린샷 2024-01-04 003611](https://github.com/Bing-su/adetailer/assets/37621276/8abb7187-69c4-4ec6-b2f9-fc9ad202b408)

You can use the `/options` endpoint.

**Comment by search-acumen** [comment]
Thanks for that but the GET:/sdapi/v1/options endpoint doesn't return any adetailer options.
What would I need to set to specify the bounding box sort direction?

**Comment by inverherive** [comment]
Thanks for that but the GET:/sdapi/v1/options endpoint doesn't return any adetailer options.
What would I need to set in POST: to specify the bounding box sort direction?
