### ISSUE TITLE
[Feature Request]: Add ability to specify alternate ADetailer checkpoint via API

### ISSUE THREAD

**Issue by rbbrdckybk** [Bing-su/adetailer#459]
### Is your feature request related to a problem? Please describe.

Noticed that there is no place to specify an alternate ADetailer checkpoint via API call, at least not according to [the docs](https://github.com/Bing-su/adetailer/wiki/API).

This option is available via the UI (along with VAE, which also appears to be missing from the API):

![image](https://github.com/Bing-su/adetailer/assets/80607958/e7c1d140-e979-4c7d-8157-9e290d6686e8)

### Describe the solution you'd like

Add an API parameter ("ad_checkpoint" or whatever) to allow us to access this functionality via the API. VAE would be nice as well!

### Additional context

For those of us with Dreambooth models trained on custom faces, being able to use an alternate checkpoint model with ADetailer is important. Being able to access this via the API would be amazing!

**Comment by rbbrdckybk** [comment]
Nevermind, it's missing from the docs but available. It's **ad_use_checkpoint** and **ad_checkpoint** if anyone else can't find it!

**Comment by Bing-su** [comment]
Sorry about that. I forgot to update it.
