### ISSUE TITLE
Not work when put models in ./models/adetailer

### ISSUE THREAD

**Issue by spldmanager** [Bing-su/adetailer#46]
In windows, models are downloaded into C:\Users\Administrator\.cache\huggingface\hub\models--Bingsu--adetailer\snapshots\403e56c1b291da2145da824f3fde640bbe08de2f  with shotcut to C:\Users\Administrator\.cache\huggingface\hub\models--Bingsu--adetailer\blobs
Any way to use ./models/adetailer directly? It is bad network to download files from huggingface

**Comment by Bing-su** [comment]
I just added the `--ad-no-huggingface` option, try adding it when you run it.
