### ISSUE TITLE
[Bug]: 使用controlnet模型control_sd15_inpaint_depth_hand_fp16时，ControlNet module没有对应预处理器

### ISSUE THREAD

**Issue by yuanyixiangxin** [Bing-su/adetailer#463]
### Describe the bug

使用controlnet模型control_sd15_inpaint_depth_hand_fp16时，ControlNet module没有对应预处理器

### Screenshots

<img width="570" alt="屏幕截图 2024-01-06 091018" src="https://github.com/Bing-su/adetailer/assets/152783389/8b5aec8d-3402-4326-a7d3-0c74351ed37a">
<img width="573" alt="屏幕截图 2024-01-06 091059" src="https://github.com/Bing-su/adetailer/assets/152783389/c4746b36-2a66-4bb2-b2f9-c64c0050ccbb">

### Console logs, from start to end.

```Shell
无报错
```

**Comment by ema7569** [comment]
Same, when selecting control_sd15_inpaint_depth_hand_fp16 the preprocessor depth_hand_refiner do not show

**Comment by Darkenlord1** [comment]
Same
