### ISSUE TITLE
[Feature Request]:  stand-in text to represent the main prompt in the adetailer prompt fields

### ISSUE THREAD

**Issue by rjgoif** [Bing-su/adetailer#465]
### Is your feature request related to a problem? Please describe.

If I am swapping in a LORA with adetailer over multiple prompts, I need to update the prompt in both the main A1111 interface and the adetailer prompt field, It's double the work and, if the step is forgotten, can ruin the generation. 

### Describe the solution you'd like

wildcards that are recognized by adetailer to stand in for the positive and negative main prompt

### Describe alternatives you've considered

I've tried using a wildcard file for my prompt but this just overcomplicates things further

### Additional context

Adetailer already pulls in the pos and negative prompt if the adetailer prompt field is empty. 

A wildcard would give more flexibility. Alternatively, a check box for "addend to original prompt" would work, but would be less flexible

**Comment by muunkky** [comment]
I think I came here to make the same request. When detailing hands, it sometimes makes them into faces. So, I replaced the positive prompt with "hand" but it still turned it into a face. I'm assuming this is because it's using the whole prompt AND the additional "hand". This isn't how I thought it would/should work. It would be quite important to be able to ignore the rest of the prompt when detailing.

I agree with the "addend to original prompt" would be helpful and also help explain how it works.

**Comment by Zotikus1001** [comment]
> I think I came here to make the same request. When detailing hands, it sometimes makes them into faces. So, I replaced the positive prompt with "hand" but it still turned it into a face. I'm assuming this is because it's using the whole prompt AND the additional "hand". This isn't how I thought it would/should work. It would be quite important to be able to ignore the rest of the prompt when detailing.
> 
> I agree with the "addend to original prompt" would be helpful and also help explain how it works.

Actually thats not the issue. 
It turn into faces when this error occurs:

Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 819, in controlnet_main_entry
        preprocessor = self.preprocessor[unit.module]
    KeyError: 'depth_hand_refiner'
    
In my experience it gives this error 75% of the time. 
And thats why it turns into faces, cus its not applying the depth map control net.
No idea how to fix this.

**Comment by muunkky** [comment]
@Zotikus1001 Does that mean the detailer prompt _does_ replace the main prompt?

**Comment by Zotikus1001** [comment]
> @Zotikus1001 Does that mean the detailer prompt _does_ replace the main prompt?

Well. If you write anything in the adetailer prompt, then yes, it does replace it on the adetailer phase.
If you leave it empty, it uses the same prompt. This is if you have everything updated. Long ago it wasnt like this.

But the issue I said was that it fails to apply the hand controlnet, thus only running with the main prompt, and thats why it makes faces on the hands.
