### ISSUE TITLE
Can I use adetailers magic directly from the command line?

### ISSUE THREAD

**Issue by derRaab** [Bing-su/adetailer#467]
### Question

Hi! I'm a total python, stable diffusion, docker and runpod serverless noob, but during the last two month I managed to implement automatic lora training and image generation using the stable diffusion scripts from https://github.com/kohya-ss/sd-scripts .

After some research and suggestions I think I need to use adetailer to fix hands and faces, but this seems to be meant as a web-ui plugin only? I found https://github.com/Bing-su/adetailer/wiki/API and this also suggests dependencies to web-ui?

So my question is:
Is it even possible to let adetailer do it's magic directly form the command line? Or do you suggest something different?

**Comment by derRaab** [comment]
After digging deeper I'm quite certain it is better to fire up a webui setup and use it's API. https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by ai1361720220000** [comment]
> ### Question
> Hi! I'm a total python, stable diffusion, docker and runpod serverless noob, but during the last two month I managed to implement automatic lora training and image generation using the stable diffusion scripts from https://github.com/kohya-ss/sd-scripts .
> 
> After some research and suggestions I think I need to use adetailer to fix hands and faces, but this seems to be meant as a web-ui plugin only? I found https://github.com/Bing-su/adetailer/wiki/API and this also suggests dependencies to web-ui?
> 
> So my question is: Is it even possible to let adetailer do it's magic directly form the command line? Or do you suggest something different?

Have you succeed in running adetailer using python? I met the same issus and need to fix the face in python script during postprocess.
