### ISSUE TITLE
[Feature Request]: Let us use IP-Adapters and other controlnet modes alongside adetailer.

### ISSUE THREAD

**Issue by CrazyKrow** [Bing-su/adetailer#469]
### Is your feature request related to a problem? Please describe.

Now that controlnet supports IP-Adapters with FaceID, it would be great to implement a way to use it with Adetailer.

https://github.com/Mikubill/sd-webui-controlnet/discussions/2442

### Describe the solution you'd like

Implement a way for IP-adapters to work alongside adetailer.

### Describe alternatives you've considered

Give us an option on the controlnet section of adetailer to not skip controlnet, because the way its implemented right now you can only choose the options available on adetailer, if you choose "none" it just skips controlnet altogether. This would also be useful if we want to use other types of modes, like Reference, Revision, etc.

### Additional context

Thanks for all the work you do for us. Its really appreciated.

**Comment by lhucklen** [comment]
Please do this! I was thinking the same thing

**Comment by bkunbargi** [comment]
Can you explain? With automatic1111 I can enable control net w/ ip adapter and ADetailer

**Comment by lhucklen** [comment]
You can use them both. But it appears ipadapter with Face ID is being ignored when doing a face pass via a detailer.

**Comment by lhucklen** [comment]
@bkunbargi 

see -> it outlines what I am suggesting
https://github.com/Bing-su/adetailer/issues/480#issue-2091420227
