### ISSUE TITLE
How can we set different prompt for each face?

### ISSUE THREAD

**Issue by FurkanGozukara** [Bing-su/adetailer#472]
### Describe the bug

Currently I am using regional prompt and generating myself with another person

I wonder if we can use Adetailer to set different face prompt for each person?

for example left face : ohwx man
right face : dwayne johnson

e.g. main prompt : closeshot photo of ohwx man wearing an expensive white suit in an otherworldly garden hands in pockets BREAK together with the dwayne johnson the rock hands in pockets

**Comment by JustusJ** [comment]
This is already possible by using the [SEP] and [SKIP] tokens (documented here: [wiki/Advanced](https://github.com/Bing-su/adetailer/wiki/Advanced)).

**Comment by FurkanGozukara** [comment]
> This is already possible by using the [SEP] and [SKIP] tokens (documented here: [wiki/Advanced](https://github.com/Bing-su/adetailer/wiki/Advanced)).

thank you so much
