### ISSUE TITLE
Turbo Inpainting

### ISSUE THREAD

**Issue by germyparker** [Bing-su/adetailer#475]
### Question

When you use a Turbo model or lora, so that the steps and CFG are very low, should you also lower the steps & CFG in the inpainting section of ADetailer?

**Comment by EtienneDosSantos** [comment]
The default setting in adetailer is that the same steps as for the normal inpaint are used. Since you're using a turbo model, step count will probably be quite low, right? If the results are bad, you might want to increase the adetailer steps a bit or perhaps even both normal and adetailer steps.
