### ISSUE TITLE
[Feature Request]: Option to Exclude ADetailer Prompts from Style Application

### ISSUE THREAD

**Issue by Fabelwesen** [Bing-su/adetailer#477]
### Is your feature request related to a problem? Please describe.

Yes, the feature request is related to a problem I've encountered while using the ADetailer Extension with the "Style" feature. Currently, when a style is applied, it affects not only the main prompt but also the ADetailer prompts (both positive and negative). This can be problematic as it limits the flexibility in maintaining the original intent of the ADetailer prompts, which I find crucial for precise adjustments and specific detailing in my work.

### Describe the solution you'd like

The ideal solution would be the introduction of a toggle or option within the settings that allows users to exempt ADetailer prompts from being altered by the applied style. This means that when a style is selected, it should only influence the main prompt, leaving the ADetailer prompts (positive and negative) in their original state. Such a feature would provide users with greater control and precision in their work, ensuring that the ADetailer prompts function as intended regardless of the chosen style.

### Describe alternatives you've considered

The only workaround I've found is to manually insert prompts from the style and avoid using the "Style" feature of A1111. However, this approach is cumbersome and negates the ease of switching between multiple styles in the X/Y/Z plot. It's a time-consuming process that detracts from the efficiency and user-friendliness of the tool.

**Comment by Targren** [comment]
I was looking into this today after a discussion with another user on reddit and came up with some related information. 

Overriding ADetailers Pos/Neg prompts still shows it as using the styles in the console output, but not in the image metadata of the gen itself (see attached examples)


![style_no_ad_prompt](https://github.com/Bing-su/adetailer/assets/11566412/aa8c797b-d276-4849-9afc-c3dc9cb1fcba)
Embedded Metadata:
```
1boy, Age:50, [graying|black] hair, Dark Wizard, Menacing Expression, Narrowed Eyes, 8k uhd hyperrealistic ultrarealistic photographic
Negative prompt: badhandv4, doll plastic fake cgi illustration art cartoon anime
Steps: 35, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1417898986, Size: 512x512, Model hash: 91d003eed7, Model: arthemyComics_v50Bakedvae, Clip skip: 2, TI hashes: "badhandv4: 5e40d722fc3d", Version: v1.7.0
```
![style_no_prompt_Adetailer_log](https://github.com/Bing-su/adetailer/assets/11566412/e2d63979-f7c4-4436-988c-20bfe2ead490)
![style_w_ad_prompt](https://github.com/Bing-su/adetailer/assets/11566412/ca1710d1-a06d-402e-a0ab-916fb8c252f5)
Embedded Metadata: 
```
parameters

1boy, Age:50, [graying|black] hair, Dark Wizard, Menacing Expression, Narrowed Eyes, 8k uhd hyperrealistic ultrarealistic photographic
Negative prompt: badhandv4, doll plastic fake cgi illustration art cartoon anime
Steps: 35, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1417898986, Size: 512x512, Model hash: 91d003eed7, Model: arthemyComics_v50Bakedvae, Clip skip: 2, ADetailer model: face_yolov8n.pt, ADetailer prompt: "(Narrowed eyes:1.3), (evil expression:1.2)", ADetailer negative prompt: "cross-eyed\n", ADetailer confidence: 0.65, ADetailer dilate erode: 4, ADetailer mask blur: 4, ADetailer denoising strength: 0.4, ADetailer inpaint only masked: True, ADetailer inpaint padding: 32, ADetailer version: 23.11.1, Version: v1.7.0
```
![style_w_prompt_Adetailer_log](https://github.com/Bing-su/adetailer/assets/11566412/2a029476-c0ad-44d2-aaae-92a27521e595)
