### ISSUE TITLE
[Feature Request]: support ip-adapter Face ID 

### ISSUE THREAD

**Issue by lhucklen** [Bing-su/adetailer#480]
### Is your feature request related to a problem? Please describe.

Currently, main branch does not support IP-adapter within the UI or via controlnet.

I am curious if anyone or the devs have tested the application of IP adapter with aDetailer for yoloperson models or Yoloface models with ip adapterpluscontrolnet or ipadapter Face ID plus’s controlnet respectively.

### Describe the solution you'd like

I see two ways this works.

1. While refining with ipadapter and appropriate segmentation model (as described above), the controlnet extension passes through the a detailer extension  (no need to select IP adapter within the aDetailer extension.)
2. While refining with ipadapter and aDetailer, you select the IP adapter model within the a detailer extension and it runs outside of controlnet like other control net models used within a detailer extension (e.g. tile, depth, openpose, etc…) 

### Describe alternatives you've considered

I have no idea how to implement this.

### Additional context

No coding experience here, just someone who enjoys making art. I think it would be interesting to test out if this would work or not and if the impact on generations is worthwhile.

**Comment by lhucklen** [comment]
Right now it seems the only thing close to this is inpainting only masked with ip adapter Face ID. A detailer would make it much more efficient imo

**Comment by logicmoon** [comment]
This would indeed be a useful addition!

**Comment by legolaswang** [comment]
Adetailer messes up the face generated with face id ! Even if I selected "pass through" for control net
