### ISSUE TITLE
[Feature Request]: API call to retrieve list of available models

### ISSUE THREAD

**Issue by physis123** [Bing-su/adetailer#483]
It would be really useful to have an API endpoint which returns a list of available ADetailer models.

Similar to what ControlNet has with:
Route GET /controlnet/model_list
(https://github.com/Mikubill/sd-webui-controlnet/wiki/API#route-get-controlnetversion)

This would also serve as a useful way to check whether ADetailer is installed and enabled. Currently if you include ADetailer settings in "alwayson_scripts" without it being installed, then the API call will fail. If we could check whether ADetailer is available first we could modify the API call accordingly.

Thanks for the awesome extension!

**Comment by BimBomBin** [comment]
+1
