### ISSUE TITLE
[Bug]: Version after November 19th cannot take effect during batch run

### ISSUE THREAD

**Issue by minaco101** [Bing-su/adetailer#487]
### Describe the bug

I often use Adetailer for batch generation

However, in versions after November 19th, when generating in bulk, adetailer cannot be called. Recently, several versions have been updated and each update has been tried, but it still does not work. Therefore, I am posting feedback and hope to fix this issue~

### Console logs, from start to end.

```Shell
none
```

**Comment by tanuki-create** [comment]
same here, I use prompts from file or text file and generate as batch.

Can you tell me exact version you can generate successfully?
I need that version.
