### ISSUE TITLE
[Feature Request]:  suggestion for pass through and inpaint only controlnet

### ISSUE THREAD

**Issue by lhucklen** [Bing-su/adetailer#488]
### Is your feature request related to a problem? Please describe.

Currently if you use pass through with inpaint only controlnet, it does not function as desired. 

Specifically, if you use a face detection model and inpaint only via pass through it will redo the entire image in the bounding box and inpaint an even smaller area of an even smaller head. Best way to describe it is like looking into and infinite mirror see photo below 
![IMG_6473](https://github.com/Bing-su/adetailer/assets/74945062/f906d646-df9f-4480-ae35-fe6c831f4f86)

To be more specific, I am trying to use ip-adapter Face ID plus at high denois strength with inpaint only to get more consistency without “hallucinations in the final image or tiling artifact. 

### Describe the solution you'd like

It would be nice if pass through worked with inpaint. In this way you could use multiple control nets with a single aDetailer pass. 

It seems like it has something to do with inpainting mask only or not being able to do so while using pass through. I am not sure though.

### Additional context

Appreciate your work, this is next level stuff!

**Comment by Bing-su** [comment]
Consider dividing your workflow into two or more steps
