### ISSUE TITLE
[Bug]: deepfashion2_yolov8s-seg.pt model not available by default.

### ISSUE THREAD

**Issue by StellarBeing25** [Bing-su/adetailer#498]
### Describe the bug

The deepfashion2_yolov8s-seg.pt model has to be downloaded from the huggingface; please make it available by default like all the other models.

**Comment by brknsoul** [comment]
Why? There are half-dozen non-included detection model. Just download them.

**Comment by StellarBeing25** [comment]
The deepfashion2_yolov8s-seg.pt is available in Bing-su Huggingface folder itself https://huggingface.co/Bingsu/adetailer/tree/main & it is mentioned that you don't need to download any model from the huggingface on the Github page so I thought Its a bug.

**Comment by Woisek** [comment]
What are the differences between the models marked with s, n or m? 🤔

**Comment by brknsoul** [comment]
According to https://www.reddit.com/r/StableDiffusion/comments/18zm7pj/updated_adetailer_models_for_better_face/

s = small
n = nano.

Use m if possible, else s.

**Comment by Woisek** [comment]
Thanks for this information, much appreciated.

**Comment by sekazi** [comment]
I noticed huggingface has person_yolov8n-seg.pt, deepfashion2_yolov8s-seg.pt, person_yolov8s-seg.pt, person_yolov8m-seg.pt, and clothing_poor_yolov8s-seg.pt flagged as unsafe. What would be triggering the pickle scanner?

**Comment by brknsoul** [comment]
> What would be triggering the pickle scanner?
It's not like a virus scanner. There's nothing wrong with the files. It's just a warning.
