### ISSUE TITLE
Does it Inpaint automatically or do I have to do it manually. 

### ISSUE THREAD

**Issue by Lenos500** [Bing-su/adetailer#499]
### Question

Does ADetailer Inpaint clothes for example in an image automatically or do I have to use the default brush of stable diffusion to do the inpainting myself?

I'm looking for a method to Inpaint clothes automatically and precisely then giving stable diffusion prompts to change them. Is this repository what I'm looking for? (I read through it and didn't quiet get it).

Thanks!

**Comment by brknsoul** [comment]
If you can find a clothes detection model, then adetailer shoulder be able to alter clothes.

You could also simply use the person detection model, and describe the person, incl. clothes.

**Comment by Lenos500** [comment]
> If you can find a clothes detection model, then adetailer shoulder be able to alter clothes.
> 
> You could also simply use the person detection model, and describe the person, incl. clothes.

If you could provide more information on where I can get that it would be helpful 👍

**Comment by brknsoul** [comment]
The person detection model comes with adetailer. Just expand Adetailer and select the person model from the model dropdown.

You can use the 2nd tab to also fix faces.
