### ISSUE TITLE
항상 enable 이 체크되어있습니다.

### ISSUE THREAD

**Issue by rubyon** [Bing-su/adetailer#50]
항상 enable 이 체크되어있습니다.

다른 익스텐션들은 사용할때 켜야 하는데

ad 는 사용안할때 꺼야 하는데... 의도된 건가요?

예전이라면 항상 켜져있어도 모델이 None 으로 되어있어 적용이 안되었는데

디폴트를 끔으로 하면 어떨까요

**Comment by Bing-su** [comment]
enable 기본값은 False입니다. 예전에 잠깐 True였을때 설치하신 분은 `ui-config.json`파일에서 직접 수정하셔야합니다.

**Comment by rubyon** [comment]
> enable 기본값은 False입니다. 예전에 잠깐 True였을때 설치하신 분은 `ui-config.json`파일에서 직접 수정하셔야합니다.

앗 감사 합니다
