### ISSUE TITLE
Can you add newest arrived Soft inpainting with RC 1.8?

### ISSUE THREAD

**Issue by FurkanGozukara** [Bing-su/adetailer#507]
### Describe the bug

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/14208

![image](https://github.com/Bing-su/adetailer/assets/19240467/3aa5288a-4692-4616-8d7f-480bca0c4514)

**Comment by gel-crabs** [comment]
Hey, I've gotten it working previously with ADetailer. Go to ADetailer in the settings tab, then add soft_inpainting to the list of script names.

(Adding the soft inpainting settings tab in ADetailer is still needed though, so don't close the issue)

**Comment by FurkanGozukara** [comment]
> Hey, I've gotten it working previously with ADetailer. Go to ADetailer in the settings tab, then add soft_inpainting to the list of script names.
> 
> (Adding the soft inpainting settings tab in ADetailer is still needed though, so don't close the issue)

thanks. i wont close. gonna check settings

**Comment by BenDes21** [comment]
> soft_inpainting

Hi, I add soft_inpainting to the adetailer settings script but it's not show in the adetailer tabs
