### ISSUE TITLE
How to setup ControlNet Model?

### ISSUE THREAD

**Issue by YKefasu** [Bing-su/adetailer#52]
it always "None", how to setup the Control net properly model?
![image](https://github.com/Bing-su/adetailer/assets/129555908/bd9d4f5f-6767-40aa-a18f-2276897fbc0f)

**Comment by Bing-su** [comment]
Only ControlNet models with `inpaint` in their name are displayed.

**Comment by YKefasu** [comment]
i hope it also work with t2i and i2i
