### ISSUE TITLE
ADetailer not working with inpainting

### ISSUE THREAD

**Issue by yumianhuli1** [Bing-su/adetailer#525]
@Bing-su ，Hello！ADetailer: img2img inpainting detected. adetailer disabled
![image](https://github.com/Bing-su/adetailer/assets/13059391/063e22d5-bb35-4ee2-aad7-67fb75142f2d)
![image](https://github.com/Bing-su/adetailer/assets/13059391/7d6e5025-89b6-4d58-a8fb-0600c794b9ed)

**Comment by SiTWulf** [comment]
Same problem for me
ADetailer: img2img inpainting detected. adetailer disabled.

Any way to disable this limitation?

**Comment by benfy95** [comment]
Can refer to:
https://github.com/Bing-su/adetailer/issues/455

**Comment by yumianhuli1** [comment]
> Can refer to: #455

thanks，but Why don't the author fix this? There must be some other reason, not robbing Peter to pay Paul

**Comment by Deerobouros** [comment]
The solution listed earlier (#455) stopped working for me after the update. I tried to change it again after, but the code doesn't look exactly the same, and changing the "p._ad_disabled = True" spots to "p._ad_disabled = False", but it didn't seem to fix it.

**Comment by highnrgappalachian** [comment]
> The solution listed earlier (#455) stopped working for me after the update. I tried to change it again after, but the code doesn't look exactly the same, and changing the "p._ad_disabled = True" spots to "p._ad_disabled = False", but it didn't seem to fix it.

Just redownload an older version. 

I'm still interested in knowing the reasons why the author has silently disabled the option to use the plugin in img2img.

**Comment by yumianhuli1** [comment]
> > The solution listed earlier (#455) stopped working for me after the update. I tried to change it again after, but the code doesn't look exactly the same, and changing the "p._ad_disabled = True" spots to "p._ad_disabled = False", but it didn't seem to fix it.
> 
> Just redownload an older version.
> 
> I'm still interested in knowing the reasons why the author has silently disabled the option to use the plugin in img2img.

img2img is not disabled. inpainting is disabled

**Comment by Haoming02** [comment]
**ADetailer** IS just **Inpainting**

So why would you want to **Inpaint** an **Inpainting**...?

If you want it to automatically detect the mask, just put the image in **img2img** and enable the `Skip img2img` toggle;
if you want to manually draw a mask , then just disable **ADetailer**.

There is practically no reason to enable **ADetailer** in **Inpainting**.

**Comment by yumianhuli1** [comment]
> **ADetailer** IS just **Inpainting**
> 
> So why would you want to **Inpaint** an **Inpainting**...?
> 
> If you want it to automatically detect the mask, just put the image in **img2img** and enable the `Skip img2img` toggle; if you want to manually draw a mask , then just disable **ADetailer**.
> 
> There is practically no reason to enable **ADetailer** in **Inpainting**.

inpainting can control the number of repairs

**Comment by Haoming02** [comment]
> inpainting can control the number of repairs

wdym by "number of repairs" ?

If you meant parameters, ADetailer has the same parameters to set as Inpaint

**Comment by Deerobouros** [comment]
> **ADetailer** IS just **Inpainting**
> 
> So why would you want to **Inpaint** an **Inpainting**...?
> 
> If you want it to automatically detect the mask, just put the image in **img2img** and enable the `Skip img2img` toggle; if you want to manually draw a mask , then just disable **ADetailer**.
> 
> There is practically no reason to enable **ADetailer** in **Inpainting**.

The main thing I wanted to be able to do is run "person" adetailer while masking the face to be unaffected
