### ISSUE TITLE
Is there a way to change the default parameters?

### ISSUE THREAD

**Issue by Zueuk** [Bing-su/adetailer#535]
### Question

I found that the Detection model confidence threshold = 0.3 is way too low and often picks up random tiny faces in the background or an occasional face on a painting on the wall.

Another thing is that when applying ADetailer to a hires-fixed image it is often better to set "Use separate width/height", but the default size of 512x512 is too small.

The Inpaint denoising strength is another value that some users might prefer to set to a different default for a particular use case.

Is there a way to set these parameters somewhere so I wouldn't have to change them manually every time?

**Comment by Bing-su** [comment]
Try modifying your `ui-config.json` file.

https://www.reddit.com/r/StableDiffusion/comments/159k8n7/quick_tip_for_beginners_you_can_change_the/

**Comment by SirVeggie** [comment]
Auto webui has this built in, you can refresh the webui, change the defaults you want to change, then go to settings -> defaults. You can press 'view changes' to check which values are being updated, then press 'apply' and then 'apply settings' and then 'reload UI'.

**Comment by Zueuk** [comment]
This is just what I was looking for, thanks!
