### ISSUE TITLE
[Feature Request]: "Enabled" checkbox in the title

### ISSUE THREAD

**Issue by Zueuk** [Bing-su/adetailer#536]
### Is your feature request related to a problem? Please describe.

Would be really nice for all extensions to have the "Enabled" checkbox visible and usable from outside the accordion.

### Describe the solution you'd like

![image](https://github.com/Bing-su/adetailer/assets/5717247/27e3d3f4-af36-4935-a6f8-8fdd20ccb874)

**Comment by BrickMissle** [comment]
Yes this would be a great Quality of Life change
