### ISSUE TITLE
where to download this model?

### ISSUE THREAD

**Issue by Chengym2023** [Bing-su/adetailer#537]
### Question

i saw this " **breasts_seg.pt**",but i can not research where to download this pt,someone could tell me?thk.

**Comment by dmytro-ddst** [comment]
ADetailer (After Detailer) Female Breast model on Civitai

**Comment by Chengym2023** [comment]
> 'ADetailer (After Detailer) Female Breast model' on Civitai

thanks,but why they named it "breasts_seg.pt"?
