### ISSUE TITLE
How to prevent adetailer detailing background people's faces?

### ISSUE THREAD

**Issue by IQOS** [Bing-su/adetailer#54]
for example, i have a images shows a female, and there are a lot of in the background, how to prevent adetailer detailing those people's face? it will make picture looks weird. such as the picture below

![20230515015613](https://github.com/Bing-su/adetailer/assets/29145373/93183bc6-1a33-43cd-9980-5d36d19c4a5f)

**Comment by Bing-su** [comment]
Increase the detection model confidence threshold to around 80.

**Comment by jmp909** [comment]
related to https://github.com/Bing-su/adetailer/issues/61 and https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8524 _([Feature Request]: face restoration minimum/maximum face size to process)_ (please see example screenshots there)

I'm looking to do the same (enhance face in foreground, don't enhance faces in the background) but this time also including codeformer in the process (or maybe sometimes you'd want to enhance faces in the background with the foreground being blurred, but this could be controlled by a threshold range - with the face sizes used to define the ratio: 100% being the largest face found)

is it possible to hook codeformer into adetailer?

thanks
J

**Comment by jmp909** [comment]
@danielos123ssa isn't that just down to your prompt used for the inpainting.. plus your denoising strength?

(note, most of what I requested has been addressed .. see #61

**Comment by danielos123ssa** [comment]
> @danielos123ssa isn't that just down to your prompt used for the inpainting.. plus your denoising strength?
> 
> (note, most of what I requested has been addressed .. see #61.. this also specfically closes your issue i think @IQOS.. see my example there [#61 (comment)](https://github.com/Bing-su/adetailer/issues/61#issuecomment-1554568779))

Agreed, I forgot it uses same prompt as generated image if left blank, didn't quite make it to my logic at first.

**Comment by ManuelMultiverse** [comment]
Hi, when im using Adetailer in Batch process to restore faces in a massive run, im finding some noise/blur arround entire frame, it changes the face but also blurrying everything around (even using inpaint mask folder). Any ideas?

**Comment by magmirant0011** [comment]
I add BREAK and [SEP] in main prompt which is for f sake the main prompt idk where it would find any other, but adetailer still confuses and applies the lora of female to the male, or just makes the male go full female face. If i dont use adetailer its all good but for some models its neccesary and it makes me lose time just wandering off to facefusion and fix the faces later. Not to mention i cant post originals on civit because they look too funny. Idk what im doing wrong.
