### ISSUE TITLE
Report error when batching the img2img process

### ISSUE THREAD

**Issue by jeffkai** [Bing-su/adetailer#548]
### Question

Speed: 1.0ms preprocess, 7.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
*** Error running postprocess_image: E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.5\modules\scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\sd-webui-aki-v4.5\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    cv2.error:
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.8.0                                                │ │
    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5              │ │
    │ │ Commandline │ ['E:\\sd-webui-aki-v4.5\\launch.py', '--theme',       │ │
    │ │             │ 'dark', '--xformers', '--xformers-flash-attention',   │ │
    │ │             │ '--api', '--autolaunch']                              │ │
    │ │   Libraries │ {'torch': '2.2.0+cu121', 'torchvision':               │ │
    │ │             │ '0.17.0+cu121', 'ultralytics': '8.1.29', 'mediapipe': │ │
    │ │             │ '0.10.11'}                                            │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ (masterpiece, top quality, best quality,          │ │
    │ │                 │ photorealistic, official art, beautiful and       │ │
    │ │                 │ aesthetic:1.2),1 girl,velvet texture,transparent  │ │
    │ │                 │ texture,facing the camera,full body               │ │
    │ │                 │ photo,<lora:lgzg_v10:0.65>,wedding_dress,<lora:l… │ │
    │ │ negative_prompt │ (:1.2),(worst quality:2),(low quality:2),(normal  │ │
    │ │                 │ quality:2),lowres,bad anatomy,bad                 │ │
    │ │                 │ hands,((monochrome)),((grayscale))                │ │
    │ │                 │ watermark,moles,large breast,bad-artist           │ │
    │ │                 │ bad-picture-chill-75v,BadDream,EasyNegativeV2     │ │
    │ │                 │ negative_hand-neg,NegfeetV2,realisticvision-nega… │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 720                                               │ │
    │ │          height │ 1278                                              │ │
    │ │    sampler_name │ DPM++ 2M Karras                                   │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ majicmix7.safetensors [7c819b6d13]                │ │
    │ │             vae │ Automatic                                         │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │                  ADetailer                                              │
    │ ┌─────────────────────┬───────────────────┐                             │
    │ │                     │ Value             │                             │
    │ ├─────────────────────┼───────────────────┤                             │
    │ │             version │ 24.3.1            │                             │
    │ │            ad_model │ face_yolov8s.pt   │                             │
    │ │           ad_prompt │ <lora:taohua:0.8> │                             │
    │ │  ad_negative_prompt │                   │                             │
    │ │ ad_controlnet_model │ None              │                             │
    │ │              is_api │ False             │                             │
    │ └─────────────────────┴───────────────────┘                             │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\adetailer\traceback.py:13 │ │
    │ │ 9 in wrapper                                                        │ │
    │ │                                                                     │ │
    │ │   138 │   │   try:                                                  │ │
    │ │ > 139 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   140 │   │   except Exception as e:                                │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py:788 │ │
    │ │ in postprocess_image                                                │ │
    │ │                                                                     │ │
    │ │    787 │   │   │   │   │   continue                                 │ │
    │ │ >  788 │   │   │   │   is_processed |= self._postprocess_image_inne │ │
    │ │    789                                                              │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py:713 │ │
    │ │ in _postprocess_image_inner                                         │ │
    │ │                                                                     │ │
    │ │    712 │   │                                                        │ │
    │ │ >  713 │   │   masks = self.pred_preprocessing(p, pred, args)       │ │
    │ │    714 │   │   shared.state.assign_current_image(pred.preview)      │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py:583 │ │
    │ │ in pred_preprocessing                                               │ │
    │ │                                                                     │ │
    │ │    582 │   │   │   image_mask = ensure_pil_image(p.image_mask, mode │ │
    │ │ >  583 │   │   │   masks = self.inpaint_mask_filter(image_mask, mas │ │
    │ │    584 │   │   return masks                                         │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py:648 │ │
    │ │ in inpaint_mask_filter                                              │ │
    │ │                                                                     │ │
    │ │    647 │   │   │   img2img_mask = ImageChops.invert(img2img_mask)   │ │
    │ │ >  648 │   │   return [mask for mask in ad_mask if has_intersection │ │
    │ │    649                                                              │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\scripts\!adetailer.py:648 │ │
    │ │ in <listcomp>                                                       │ │
    │ │                                                                     │ │
    │ │    647 │   │   │   img2img_mask = ImageChops.invert(img2img_mask)   │ │
    │ │ >  648 │   │   return [mask for mask in ad_mask if has_intersection │ │
    │ │    649                                                              │ │
    │ │                                                                     │ │
    │ │ E:\sd-webui-aki-v4.5\extensions\adetailer\adetailer\mask.py:96 in   │ │
    │ │ has_intersection                                                    │ │
    │ │                                                                     │ │
    │ │    95 │   arr2 = np.array(ensure_pil_image(im2, "L"))               │ │
    │ │ >  96 │   return not is_all_black(cv2.bitwise_and(arr1, arr2))      │ │
    │ │    97                                                               │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ error: OpenCV(4.9.0)                                                    │
    │ D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:214 │
    │ : error: (-209:Sizes of input arguments do not match) The operation is  │
    │ neither 'array op array' (where arrays have the same size and type),    │
    │ nor 'array op scalar', nor 'scalar op array' in function                │
    │ 'cv::binary_op'                                                         │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

**Comment by k52252467** [comment]
Speed: 0.0ms preprocess, 6.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
*** Error running postprocess_image: C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 856, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    AssertionError:
    
    
    
    I encountered the same problem, which caused my Console to be interrupted directly and no other Console logs were displayed. Moreover, every time I updated, I had to change !adetailer.py like #455, so that it could work normally, but the above problem still did not occur. solve,
