### ISSUE TITLE
[Bug]: hires.fix denoising strength always saved as 0.4 value in image metadata if ADetailer is active

### ISSUE THREAD

**Issue by himmelweiss** [Bing-su/adetailer#552]
### Describe the bug

ADetailer version: 24.3.2

If hires.fix is enabled, hires.fix denoising strength will be "always" saved as 0.4 value in the metadata of the result image (no matter what i set the value to originally).

As soon i disable ADetailer, hires.fix denoising value is saved with the correct value.

### Console logs, from start to end.

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 115cd9c35b0774c90cb9c397ad60ef6a7dac60de
SD-WebUI revision: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5

Checking Civitai Link requirements...

#######################################################################################################
Launching Web UI with arguments: --theme=dark --xformers
[-] ADetailer initialized. version: 24.3.2, num models: 24
```

**Comment by tetsuoo-online** [comment]
I came for the same issue, I can confirm it's happening for me as well, I always use external TXT files but it's in the image metadata as well, always stuck at 0.4 its very annoying I can't compare generated images anymore or reproduce them

**Comment by Bing-su** [comment]
I haven't cared about metadata for a long time, so I'm not sure, how long has this been an issue?

**Comment by himmelweiss** [comment]
> I haven't cared about metadata for a long time, so I'm not sure, how long has this been an issue?

Since quite some time so it seems 😄
Only noticed it just yesterday.

**Comment by miasik** [comment]
> I haven't cared about metadata for a long time, so I'm not sure, how long has this been an issue?

Maybe about a week

**Comment by Bing-su** [comment]
The image that is processed through adetailer becomes a product of img2img as a result. Right now, this seems like a tough problem to solve, since denoising strength in hires and denoising strength in img2img have the same name.

**Comment by himmelweiss** [comment]
> The image that is processed through adetailer becomes a product of img2img as a result. Right now, this seems like a tough problem to solve, since denoising strength in hires and denoising strength in img2img have the same name.

And there is no way to catch the hires.fix denoising strength value and send it over to the img2img process?
Shouldn't matter if the name is the same? Or maybe i am just misunderstanding something there, quite possible as i have no idea about the overall code and how everything works etc., too lazy to dig through all this, i have my fair share of code annoyances already in my job since several decades :D

**Comment by Nakadun** [comment]
Oh should have made the request to the dev branch. My bad :|
