### ISSUE TITLE
how can preset `ControlNet model` in `ui-config.json`

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#557]
### Question

![image](https://github.com/Bing-su/adetailer/assets/167966/256b28eb-ffd8-4c18-a5e0-b1695eb8f192)

---

all not work

- txt2img/ad_controlnet_model/value
- txt2img/ControlNet model/value
- txt2img/ad_controlnet_model${i}/value

**Comment by Bing-su** [comment]
![chrome_yaGYYH5g5W](https://github.com/Bing-su/adetailer/assets/37621276/f11e0164-799d-4af0-ba76-2b051022a799)

Try this option on the Settings tab.
