### ISSUE TITLE
[Bug]: ADetailer: img2img inpainting SDXL since december WHY?

### ISSUE THREAD

**Issue by kalle07** [Bing-su/adetailer#558]
### Describe the bug

please tell us a reason ...
we want to know ...
[ #455](https://github.com/Bing-su/adetailer/issues/455)

### Console logs, from start to end.

```Shell
https://github.com/Bing-su/adetailer/issues/455
```

**Comment by Bing-su** [comment]
The restriction on issue #455 has been relaxed since version 24.3.1.

Why are you still having trouble?

**Comment by k52252467** [comment]
> The restriction on issue #455 has been relaxed since version 24.3.1.
> 
> Why are you still having trouble?

This is a very interesting question. In fact, most people who have problems refer to problems with img2img, but probably most of them use ControlNet's img2img in txt2img. According to the feedback you provided, you seem to have fixed it. This problem has been solved, but some people still have to use the old version or change def is_img2img_inpaint to False before they can use it.
 Most of it may be related to ControlNet's img2img I mentioned above,

 Like I said, even after downloading the latest version, I had to change is_img2img_inpaint to False,
 There will also be the following problems

Speed: 0.0ms preprocess, 6.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
*** Error running postprocess_image: C:\stable-diffusion-webui\extensions\adetailer\scripts![adetailer.py](http://adetailer.py/)
Traceback (most recent call last):
File "C:\stable-diffusion-webui\modules\[scripts.py](http://scripts.py/)", line 856, in postprocess_image
script.postprocess_image(p, pp, *script_args)
File "C:\stable-diffusion-webui\extensions\adetailer\adetailer\[traceback.py](http://traceback.py/)", line 159, in wrapper
raise error from None
AssertionError:

which caused my Console to be interrupted directly and no other Console logs were displayed.  

Thank you very much for your continued efforts, but this is really troubling to some people.

**Comment by Bing-su** [comment]
@k52252467 I'm following the [flake8-bandit S](https://docs.astral.sh/ruff/rules/assert/) rules, I don't raise AssertionError except for testing. Please write a proper bug report.

**Comment by k52252467** [comment]
> @k52252467 I'm following the [flake8-bandit S](https://docs.astral.sh/ruff/rules/assert/) rules, I don't raise AssertionError except for testing. Please write a proper bug report.

I think my problem is similar to #548. This problem bothers me more. It may interrupt my Console at any time, and sometimes there are no Console logs.
