### ISSUE TITLE
红色面部跟踪框，这个工具在哪儿设置？

### ISSUE THREAD

**Issue by yanjingwyj** [Bing-su/adetailer#56]
使用方法：安装好插件就出现SEED下面，勾选开启，并选择模型，下面还要选“INPOINT”，还有选“CON V11p SD15”（所有模式通用）红色面部追踪框：在SD的总设置里面找到它勾选开启，这样能在生成图片的文件里面夹看到2张相同的图片，其中1张有脸部红框，否则看不到。

红色面部跟踪框，这个工具在哪儿设置？“CON V11p SD15”（所有模式通用）这个在哪儿？

**Comment by Bing-su** [comment]
![Cap 2023-05-15 22-48-46-336](https://github.com/Bing-su/adetailer/assets/37621276/5822f7b9-7867-415c-a3fe-01470fb15eb5)
Settings - After Detailer - Save mask previews

**Comment by zethfoxster** [comment]
i think this isnt the anwser this person needed. im also having this issue. the adetailer is working however, the bounding box and red mask are not drawn...when it detects the img...i just did a reinstall of auto1111 and after i did, these mask and boxes no longer get drawn for me to see...i cant find any option to see them anywhere

**Comment by zethfoxster** [comment]
![image](https://github.com/Bing-su/adetailer/assets/5951657/86bb91ae-3eb0-4290-9e11-21bdb4bfd3c8)
