### ISSUE TITLE
[Bug]: AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'inpainting_mask_invert'   

### ISSUE THREAD

**Issue by k52252467** [Bing-su/adetailer#561]
### Describe the bug

Based on the error message, it seems like there's an attribute error occurring in your code. The program is trying to access an attribute named 'inpainting_mask_invert', but the 'StableDiffusionProcessingTxt2Img' object does not have this attribute. This could be due to a bug or error in the code.

### Console logs, from start to end.

```Shell
*** Error running process: C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py0:02<1:04:25,  2.59it/s]
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "C:\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    AttributeError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22631-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.8.0                                                                                         │ │
    │ │      Commit │ bef51aed032c0aaa5cfd80445bc4cf0d85b408b5                                                       │ │
    │ │ Commandline │ ['launch.py', '--xformers']                                                                    │ │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.1.33', 'mediapipe':  │ │
    │ │             │ '0.10.11'}                                                                                     │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                  Inputs                                                          │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓        │
    │ ┃                 ┃ Value                                                                               ┃        │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩        │
    │ │          prompt │ A, (closed_eyes:1.6), (pain:1.2), (open_mouth:1.6), (smile:1.1), (closed_mouth:1.6) │        │
    │ │ negative_prompt │ B                                                                                   │        │
    │ │          n_iter │ 1                                                                                   │        │
    │ │      batch_size │ 1                                                                                   │        │
    │ │           width │ 792                                                                                 │        │
    │ │          height │ 1408                                                                                │        │
    │ │    sampler_name │ DPM++ 2M Karras                                                                     │        │
    │ │       enable_hr │ False                                                                               │        │
    │ │     hr_upscaler │ Latent                                                                              │        │
    │ │      checkpoint │ MAIN\beautifulRealistic_v7.safetensors [1a17bcd93d]                                 │        │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors                                            │        │
    │ │            unet │ Automatic                                                                           │        │
    │ └─────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘        │
    │                    ADetailer                                                                                     │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓                                                                  │
    │ ┃                     ┃ Value                 ┃                                                                  │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩                                                                  │
    │ │             version │ 24.3.4                │                                                                  │
    │ │            ad_model │ person_yolov8m-seg.pt │                                                                  │
    │ │           ad_prompt │ A                     │                                                                  │
    │ │  ad_negative_prompt │ B                     │                                                                  │
    │ │ ad_controlnet_model │ None                  │                                                                  │
    │ │              is_api │ False                 │                                                                  │
    │ └─────────────────────┴───────────────────────┘                                                                  │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper             │             │
    │ │                                                                                                  │             │
    │ │   138 │   │   try:                                                                               │             │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   140 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:685 in process              │             │
    │ │                                                                                                  │             │
    │ │    684 │   │                                                                                     │             │
    │ │ ❱  685 │   │   if self.is_img2img_inpaint(p) and is_all_black(self.get_image_mask(p)):           │             │
    │ │    686 │   │   │   p._ad_disabled = True                                                         │             │
    │ │                                                                                                  │             │
    │ │ C:\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:670 in get_image_mask       │             │
    │ │                                                                                                  │             │
    │ │    669 │   │   mask = p.image_mask                                                               │             │
    │ │ ❱  670 │   │   if p.inpainting_mask_invert:                                                      │             │
    │ │    671 │   │   │   mask = ImageChops.invert(mask)                                                │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'inpainting_mask_invert'              │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### List of installed extensions

Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[925d928a](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/925d928a32e5b476ae08bd9d9dd79155bb9112c0)	2024-03-28 15:19:56	latest
adetailer	https://github.com/Bing-su/adetailer.git	main	[372e8b75](https://github.com/Bing-su/adetailer/commit/372e8b754bf6ea7d92bc666920a3c5aa43e49dbd)	2024-03-28 19:29:51	latest
sd-dynamic-prompts	https://github.com/adieyal/sd-dynamic-prompts.git	main	[e8326b5e](https://github.com/adieyal/sd-dynamic-prompts/commit/e8326b5eee92c78f3bc2aa424d5ea4a91bed2c38)	2024-03-28 02:13:36	latest
sd-webui-IS-NET-pro	https://github.com/ClockZinc/sd-webui-IS-NET-pro.git	main	[1ac270e4](https://github.com/ClockZinc/sd-webui-IS-NET-pro/commit/1ac270e438b441ac30580b8b608f77389bbcb968)	2023-09-27 22:10:17	latest
sd-webui-ar	https://github.com/alemelis/sd-webui-ar.git	main	[3973c86a](https://github.com/alemelis/sd-webui-ar/commit/3973c86a7a0f9722b5f61dd1a141ba6821f60245)	2023-09-26 21:23:07	latest
sd-webui-boomer	https://github.com/Haoming02/sd-webui-boomer.git	main	[4f310316](https://github.com/Haoming02/sd-webui-boomer/commit/4f31031660b88b1883f1b83c97092beb10b12ac2)	2024-03-06 10:16:12	latest
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[2a210f04](https://github.com/Mikubill/sd-webui-controlnet/commit/2a210f0489a4484f55088159bbfa51aaf73e10d9)	2024-03-27 16:00:56	latest
sd-webui-enable-checker	https://github.com/shirayu/sd-webui-enable-checker.git	main	[b2b49769](https://github.com/shirayu/sd-webui-enable-checker/commit/b2b49769beb7f414672b16b5e7ffbceb966e790b)	2024-03-09 15:37:19	latest
sd-webui-freeu	https://github.com/ljleb/sd-webui-freeu.git	main	[08a1734f](https://github.com/ljleb/sd-webui-freeu/commit/08a1734f166b87efba96f42d79a79b2850e1bea4)	2023-10-19 05:45:52	latest
sd-webui-lora-block-weight	https://github.com/hako-mikan/sd-webui-lora-block-weight.git	main	[1fa7eb78](https://github.com/hako-mikan/sd-webui-lora-block-weight/commit/1fa7eb78f59af791183d6ed35972039c34b51fad)	2024-02-12 22:56:37	latest
stable-diffusion-webui-chinese	https://github.com/VinsonLaro/stable-diffusion-webui-chinese.git	main	[1db3194d](https://github.com/VinsonLaro/stable-diffusion-webui-chinese/commit/1db3194d931a44b7e9fec9c3146efecf3d478f61)	2024-03-13 23:13:03	latest
stable-diffusion-webui-wd14-tagger	https://github.com/picobyte/stable-diffusion-webui-wd14-tagger.git	master	[e72d984b](https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/commit/e72d984bdbed832ba83e2a443238c3851b9088ae)	2023-11-04 19:58:30	latest

**Comment by Bing-su** [comment]
저는 논리적으로 이 에러가 발생하지 않게 구성해뒀습니다. 더 자세한 정보를 제공해주세요.

**Comment by k52252467** [comment]
> 저는 논리적으로 이 에러가 발생하지 않게 구성해뒀고, 테스트까지 진행했습니다. 더 자세한 정보를 제공해주세요.

https://github.com/ClockZinc/sd-webui-IS-NET-pro/issues/16
I'm not sure if this has an impact as well, so attaching it too
==================================================================================

Since I don't understand code myself, I asked about GPT,
his answer is

This error message indicates that somewhere in your code, an attempt is being made to access an attribute called inpainting_mask_invert on an object of type StableDiffusionProcessingTxt2Img. However, the object does not have this attribute, hence the AttributeError.

To resolve this issue, you need to review your code and ensure that the attribute inpainting_mask_invert is correctly defined and accessible within the StableDiffusionProcessingTxt2Img class or object. If it's supposed to exist but is missing, you may need to check for any spelling errors or typos in the attribute name and ensure that it is properly initialized.
==================================================================================

I searched for the relevant code of controlnet
https://github.com/search?q=repo%3AMikubill%2Fsd-webui-controlnet%20StableDiffusionProcessingTxt2Img%20&type=code

79 | p.__class__ = processing.StableDiffusionProcessingTxt2Img
80 | dummy = processing.StableDiffusionProcessingTxt2Img()
843 | isinstance(p, StableDiffusionProcessingTxt2Img)
904 | high_res_fix = isinstance(p, StableDiffusionProcessingTxt2Img) and getattr(p, 'enable_hr', False)
==================================================================================

Your script code was also searched
https://github.com/search?q=repo%3ABing-su%2Fadetailer%20npainting_mask_invert&type=code

507 | inpainting_mask_invert=0,
508 | initial_noise_multiplier=initial_noise_multiplier,
669 | mask = p.image_mask
670 | if p.inpainting_mask_invert:
671 | mask = ImageChops.invert(mask)
==================================================================================

I'm not sure if these are related, but these issues have been really bothering me for a week now
