### ISSUE TITLE
Adetailer produces black square when used and black screen when not used !!

### ISSUE THREAD

**Issue by EKKIV0K** [Bing-su/adetailer#565]
### Describe the bug

i don't really have to say more about that problem it produce juste black square or black silhouetes corresponding where i want to inpaint after generating, it work when i start a1111 and start to doing some weird stuffs after a couple of generations.

Really annoying ! never had those problem since the updates maded to this poor extension.

### Steps to reproduce

use the latest a1111 stable diffusion version 
generate and .......black screen !

### Screenshots

![00847-2704552904](https://github.com/Bing-su/adetailer/assets/119963095/e2b22c31-5708-4dd5-94cf-c4776969d0a4)

### Console logs, from start to end.

```Shell
Nothing to show here cause there is no errors, or messages.
the extension just run as usual in logs, not problem for it.
but big problem in the output.....
```

### List of installed extensions

Just Adtailer.

**Comment by EKKIV0K** [comment]
Someone ????

**Comment by EKKIV0K** [comment]
it didn't resolve anything. please some help

**Comment by Bing-su** [comment]
Our AI friend @dosu-bot has given us a pretty good answer. Have you tried it?

**Comment by EKKIV0K** [comment]
@Bing-su yep i did everything it worked on time and after that it restarted to be black....
but in forgeUI i don't have that kind of problem ....

**Comment by Bing-su** [comment]
I'm not sure.
