### ISSUE TITLE
How to call 3 controlnets through Passthrough setting

### ISSUE THREAD

**Issue by anzhongqian** [Bing-su/adetailer#570]
### Question

In img2img, when I call three controlnets through Passthrough and use independent control images, the face appears abnormal. Please analyze how to solve this problem. Thank you very much！
img 2 imgでは、Passthroughを介して3つのcontrolnetを呼び出し、独自の制御画像を使用した場合、顔に異常が発生します。この問題を解決する方法を分析してください。ありがとうございます！

**Comment by Bing-su** [comment]
@dosu-bot Tell him to write bug reports properly. In Japanese.
