### ISSUE TITLE
[Feature Request]: Add support to Euler-Smea-Dyn-Sampler

### ISSUE THREAD

**Issue by DavideAlidosi** [Bing-su/adetailer#571]
### Is your feature request related to a problem? Please describe.

Can you please add support to [Euler-Smea-Dyn-Sampler](https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler)?
Actually not work, but is possibile use the standard Euler A instead.
Bests

**Comment by Bing-su** [comment]
You should ask the headquarters for this.
