### ISSUE TITLE
Request help!!!

### ISSUE THREAD

**Issue by mrdoug2023** [Bing-su/adetailer#58]
When I choose to use "hand_yolov8n.pt", the following result appears:

![031455](https://github.com/Bing-su/adetailer/assets/125487984/c713ae5e-7497-47be-b253-e3f38d1836ec)
PS: All parameters in [adetailer] are using default values,  I don't know where this error comes from...😣

**Comment by Bing-su** [comment]
Unlike face and person, inpainting hands requires careful parameterisation.

**Comment by mrdoug2023** [comment]
> Unlike face and person, inpainting hands requires careful parameter setting. Note that if you leave the ad_prompt blank, the default prompts will be used.

Ah, that accounts for it. Thank you for your guidance.
