### ISSUE TITLE
[Bug]: A1111 1.9.0 "Separate Steps", "Separate Sampler" and possibly other "Separate" options have no effect, 

### ISSUE THREAD

**Issue by zcatharisis** [Bing-su/adetailer#588]
### Describe the bug

Title. Adetailer acts as if several "Separate" options are  disabled even when ticked on or off. Instead, it will use settings from the initial image generated. This happens in both t2i and i2i. Tested only on a 1.5 checkpoint, no idea if this happens with SDXL. 

I can only confirm that it happens with Steps and Sampler based on the console log. Please refer to the screenshot and console log below. Adetailer used 15 steps instead of five. It also seems to be using the Restart sampler still instead of DPM 2++; you can tell because the adetailer it/s is still 1.01, when it should be around ~1.7it/s like the second generated image.

I can't definitively confirm if the other Separate options still work though, they **_seem_** to still take effect. I also just checked to see if this might be a problem with adding more models, but the problem still persists even when using Adetailer 1st, 2nd, and 3rd

### Steps to reproduce

1. Set standard t2i or i2i generation. 
2. Tick Separate Steps or Sampler checkbox to enable.
3. Set value to anything but the initial image settings.
4. Generate image.

### Screenshots

![image](https://github.com/Bing-su/adetailer/assets/143588182/ffe1906a-6d71-4117-b006-40d3031ef84c)

### Console logs, from start to end.

```Shell
Model loaded in 24.1s (load weights from disk: 0.5s, create model: 1.3s, apply weights to model: 21.0s, load textual inversion embeddings: 0.4s, calculate empty prompt: 0.6s).
NegPiP enable, Positive:[6],Negative:None
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:14<00:00,  1.03it/s]

0: 640x480 1 face, 35.3ms
Speed: 23.5ms preprocess, 35.3ms inference, 164.6ms postprocess per image at shape (1, 3, 640, 480)
tiled upscale: 100%|█████████████████████████████████████████████████████████████████████| 4/4 [00:07<00:00,  1.95s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:15<00:00,  1.01s/it]
[-] ADetailer: applied 5th ad_prompt: '<lora:ReaLora:1> smile, detailed irises'

NegPiP enable, Positive:[14],Negative:None
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:08<00:00,  1.74it/s]
```

### List of installed extensions

![image](https://github.com/Bing-su/adetailer/assets/143588182/f0391274-ce62-4a70-a7dd-5935742625c8)

**Comment by Bing-su** [comment]
I've tested it several times and it still works as intended.

Perhaps there's some other unknown issue.
