### ISSUE TITLE
Inpainting

### ISSUE THREAD

**Issue by porternw** [Bing-su/adetailer#59]
Can this be used with an inpainting mask? In other words, if I paint a mask on the inpainting tab, can adetailer *only* mask and modify the inpaint-masked portion? This would make it easy to change just one character/piece of clothing/etc rather than the whole segment. Great extension, thank you!

**Comment by andupotorac** [comment]
Yes, but you'll use it for faces and hands only. Otherwise what's the point? You would stick to inpainting and writing your prompt for clothes manually.

Here's how it's been done before: https://github.com/Bing-su/adetailer/issues/5#issuecomment-1533433450
