### ISSUE TITLE
[Feature Request]: The installation path of the model is very messy, can it be modified to a uniform position?

### ISSUE THREAD

**Issue by FengLeiDong** [Bing-su/adetailer#590]
### Is your feature request related to a problem? Please describe.

Thank you very much for developing and providing you with the plug-in, I have a question, that is, the installation path of the model is very messy, can you unify the path, install it to sd-webui\models\adetailer, so that the software installation and use can be convenient, and it is more conducive to the spread of the software

**Comment by Bing-su** [comment]
Currently, adetailer handles major model downloads through the huggingface_hub library. Downloading via huggingface_hub makes it easy to handle integrity checks, model updates, and is useful for ensuring that models are downloaded only once across multiple use cases. (In fact, even if you use the adetailer in both forge and sd-next and webui, the model will only be downloaded once)

So for now, I'd like to leave it as it is.
