### ISSUE TITLE
[Bug]: adetailer detects face but won't process it

### ISSUE THREAD

**Issue by MonkeyDocs** [Bing-su/adetailer#591]
### Describe the bug

For some reason adetailer doesn't work, it detects the image after the whole generation but doesn't do anything afterwards, it just completes

I'm on A1111 version: v1.9.2

### Steps to reproduce

Generating random image with adetailer on

### Screenshots

![Screenshot 2024-04-22 205316](https://github.com/Bing-su/adetailer/assets/61049870/487c92c3-083d-4bbf-a34c-3de18aee6832)
![Screenshot 2024-04-22 205440](https://github.com/Bing-su/adetailer/assets/61049870/d7720298-a65f-4e4a-b6d4-553d8929e7ae)
![Screenshot 2024-04-22 205809](https://github.com/Bing-su/adetailer/assets/61049870/a773fdb3-4119-426f-9eea-05b64735e554)

### Console logs, from start to end.

```Shell
Already up to date.
venv "D:\A1111\webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.9.2
Commit hash: e2b177c508447cd3068993c67e165880348ff0d8
Launching Web UI with arguments: --opt-sdp-attention
No module 'xformers'. Proceeding without it.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.4.2, num models: 16
ControlNet preprocessor location: D:\A1111\webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-22 20:56:14,073 - ControlNet - INFO - ControlNet v1.1.445
2024-04-22 20:56:14,170 - ControlNet - INFO - ControlNet v1.1.445
Loading weights [ec6acf3c0b] from D:\A1111\webui\models\Stable-diffusion\zBase Model\fantasticmix25D_v45.safetensors
2024-04-22 20:56:14,765 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: D:\A1111\webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
🤯 LobeTheme: Initializing...
Startup time: 13.3s (prepare environment: 3.0s, import torch: 4.0s, import gradio: 0.8s, setup paths: 1.1s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 2.1s, create ui: 0.8s, gradio launch: 0.4s, app_started_callback: 0.3s).
Loading VAE weights specified in settings: D:\A1111\webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sdp... done.
Model loaded in 6.4s (load weights from disk: 1.0s, create model: 0.4s, apply weights to model: 4.5s, load VAE: 0.1s, calculate empty prompt: 0.2s).
100%|████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.57it/s]
tiled upscale: 100%|█████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00,  9.83it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.77it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████| 48/48 [00:12<00:00,  2.77it/s]
0: 640x448 1 face, 100.5ms
Speed: 2.0ms preprocess, 100.5ms inference, 16.7ms postprocess per image at shape (1, 3, 640, 448)
*** Error running postprocess_image: D:\A1111\webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\A1111\webui\modules\scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\A1111\webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    TypeError:
    ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                      System info                                                       │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                                ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.22631-SP0                                                                            │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]                   │ │
    │ │     Version │ v1.9.2                                                                                               │ │
    │ │      Commit │ e2b177c508447cd3068993c67e165880348ff0d8                                                             │ │
    │ │ Commandline │ ['launch.py', '--opt-sdp-attention']                                                                 │ │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.1.47', 'mediapipe':        │ │
    │ │             │ '0.10.11'}                                                                                           │ │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                                         Inputs                                                         │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                            ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ a man in a car                                                                                   │ │
    │ │ negative_prompt │ (worst quality:1.4, low quality:1.4), (missing arms, missing legs, moles:1.1), bad anatomy,      │ │
    │ │                 │ mutation, deformed, cloned face, disfigured, bad proportions, strawberry                         │ │
    │ │          n_iter │ 1                                                                                                │ │
    │ │      batch_size │ 1                                                                                                │ │
    │ │           width │ 512                                                                                              │ │
    │ │          height │ 768                                                                                              │ │
    │ │    sampler_name │ DPM++ 2M                                                                                         │ │
    │ │       enable_hr │ True                                                                                             │ │
    │ │     hr_upscaler │ 4x-UltraSharp                                                                                    │ │
    │ │      checkpoint │ zBase Model\fantasticmix25D_v45.safetensors                                                      │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors                                                         │ │
    │ │            unet │ Automatic                                                                                        │ │
    │ └─────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                 ADetailer                                                                                              │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                              │
    │ ┃                     ┃ Value           ┃                                                                              │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                              │
    │ │             version │ 24.4.2          │                                                                              │
    │ │            ad_model │ face_yolov8n.pt │                                                                              │
    │ │           ad_prompt │                 │                                                                              │
    │ │  ad_negative_prompt │                 │                                                                              │
    │ │ ad_controlnet_model │ None            │                                                                              │
    │ │              is_api │ False           │                                                                              │
    │ └─────────────────────┴─────────────────┘                                                                              │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                   │
    │ │ D:\A1111\webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper                        │                   │
    │ │                                                                                                  │                   │
    │ │   138 │   │   try:                                                                               │                   │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │                   │
    │ │   140 │   │   except Exception as e:                                                             │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\extensions\adetailer\scripts\!adetailer.py:805 in postprocess_image               │                   │
    │ │                                                                                                  │                   │
    │ │    804 │   │   │   │   │   continue                                                              │                   │
    │ │ ❱  805 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │                   │
    │ │    806                                                                                           │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\extensions\adetailer\scripts\!adetailer.py:766 in _postprocess_image_inner        │                   │
    │ │                                                                                                  │                   │
    │ │    765 │   │   │   try:                                                                          │                   │
    │ │ ❱  766 │   │   │   │   processed = process_images(p2)                                            │                   │
    │ │    767 │   │   │   except NansException as e:                                                    │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\modules\processing.py:845 in process_images                                       │                   │
    │ │                                                                                                  │                   │
    │ │    844 │   │                                                                                     │                   │
    │ │ ❱  845 │   │   res = process_images_inner(p)                                                     │                   │
    │ │    846                                                                                           │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\modules\processing.py:915 in process_images_inner                                 │                   │
    │ │                                                                                                  │                   │
    │ │    914 │   │   with devices.autocast():                                                          │                   │
    │ │ ❱  915 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                            │                   │
    │ │    916                                                                                           │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\modules\processing.py:1616 in init                                                │                   │
    │ │                                                                                                  │                   │
    │ │   1615 │   │   │   │   if crop_region:                                                           │                   │
    │ │ ❱ 1616 │   │   │   │   │   crop_region = masking.expand_crop_region(crop_region, self.width, se  │                   │
    │ │   1617 │   │   │   │   │   x1, y1, x2, y2 = crop_region                                          │                   │
    │ │                                                                                                  │                   │
    │ │ D:\A1111\webui\modules\masking.py:45 in expand_crop_region                                       │                   │
    │ │                                                                                                  │                   │
    │ │   44 │                                                                                           │                   │
    │ │ ❱ 45 │   ratio_crop_region = (x2 - x1) / (y2 - y1)                                               │                   │
    │ │   46 │   ratio_processing = processing_width / processing_height                                 │                   │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                   │
    │ TypeError: unsupported operand type(s) for -: 'tuple' and 'int'                                                        │
    ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 100%|████████████████████████████████████████████████████████████████████████| 48/48 [00:14<00:00,  3.31it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████| 48/48 [00:14<00:00,  2.77it/s]
```

### List of installed extensions

<html>
<body>

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
LDSR | built-in | None |   |   |  
Lora | built-in | None |   |   |  
ScuNET | built-in | None |   |   |  
SwinIR | built-in | None |   |   |  
canvas-zoom-and-pan | built-in | None |   |   |  
extra-options-section | built-in | None |   |   |  
hypertile | built-in | None |   |   |  
mobile | built-in | None |   |   |  
postprocessing-for-training | built-in | None |   |   |  
prompt-bracket-checker | built-in | None |   |   |  
soft-inpainting | built-in | None |   |   |  
ControlNet | https://github.com/lllyasviel/ControlNet | main | ed85cd1e | 2023-09-10 03:09:12 | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git | main | 0d24e697 | 2024-04-16 19:28:33 | unknown
adetailer | https://github.com/Bing-su/adetailer.git | main | 1edd5888 | 2024-04-17 18:57:43 | unknown
catppuccin | https://github.com/catppuccin/catppuccin | main | 9eaec2ae | 2024-04-15 06:17:32 | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | main | 574a0963 | 2024-03-30 17:56:11 | unknown
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts.git | main | 1567e787 | 2024-04-11 13:47:05 | unknown
sd-dynamic-thresholding | https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git | master | 701a2087 | 2024-04-21 22:51:14 | unknown
sd-web-ui-quickcss | https://github.com/Gerschel/sd-web-ui-quickcss.git | master | c7a7d097 | 2023-04-27 02:17:08 | unknown
sd-webui-aspect-ratio-helper | https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git | main | 99fcf9b0 | 2023-06-04 23:39:07 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | b4b5bfef | 2024-04-22 04:51:20 | unknown
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing | main | cadbe81c | 2024-04-20 23:15:51 | unknown
sd-webui-lobe-theme | https://github.com/canisminor1990/sd-webui-lobe-theme.git | main | b9ab9dc4 | 2024-01-17 02:50:35 | unknown
sd-webui-supermerger | https://github.com/hako-mikan/sd-webui-supermerger.git | main | 843ca282 | 2024-04-10 21:12:05 | unknown
stable-diffusion-webui | https://github.com/catppuccin/stable-diffusion-webui.git | main | 6f1eebbe | 2023-04-07 02:22:37 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | 2322caa4 | 2024-03-09 00:55:37 | unknown
ultralytics | https://github.com/ultralytics/ultralytics | main | 5a82b511 | 2024-04-21 02:58:34 | unknown

</body>
</html>Extension	URL	Branch	Version	Date	Update
LDSR	[built-in](http://127.0.0.1:7860/)	None			
Lora	[built-in](http://127.0.0.1:7860/)	None			
ScuNET	[built-in](http://127.0.0.1:7860/)	None			
SwinIR	[built-in](http://127.0.0.1:7860/)	None			
canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None			
extra-options-section	[built-in](http://127.0.0.1:7860/)	None			
hypertile	[built-in](http://127.0.0.1:7860/)	None			
mobile	[built-in](http://127.0.0.1:7860/)	None			
postprocessing-for-training	[built-in](http://127.0.0.1:7860/)	None			
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None			
soft-inpainting	[built-in](http://127.0.0.1:7860/)	None			
ControlNet	https://github.com/lllyasviel/ControlNet	main	[ed85cd1e](https://github.com/lllyasviel/ControlNet/commit/ed85cd1e25a5ed592f7d8178495b4483de0331bf)	2023-09-10 03:09:12	unknown
a1111-sd-webui-tagcomplete	https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git	main	[0d24e697](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/0d24e697d24439dac17cf717e3db665ffbf3e650)	2024-04-16 19:28:33	unknown
adetailer	https://github.com/Bing-su/adetailer.git	main	[1edd5888](https://github.com/Bing-su/adetailer/commit/1edd58886014a8fdea73cfcc30dfac84f4684926)	2024-04-17 18:57:43	unknown
catppuccin	https://github.com/catppuccin/catppuccin	main	[9eaec2ae](https://github.com/catppuccin/catppuccin/commit/9eaec2aed930e17aa08e9400454759d93b584c7f)	2024-04-15 06:17:32	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	[574a0963](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/574a0963133a34815f65bfaf985c19de54fdf323)	2024-03-30 17:56:11	unknown
sd-dynamic-prompts	https://github.com/adieyal/sd-dynamic-prompts.git	main	[1567e787](https://github.com/adieyal/sd-dynamic-prompts/commit/1567e7871a703ab7359a95e3d33fcbd708ce890b)	2024-04-11 13:47:05	unknown
sd-dynamic-thresholding	https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git	master	[701a2087](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/commit/701a2087cf2f64144ca74f23485efc0c6add663a)	2024-04-21 22:51:14	unknown
sd-web-ui-quickcss	https://github.com/Gerschel/sd-web-ui-quickcss.git	master	[c7a7d097](https://github.com/Gerschel/sd-web-ui-quickcss/commit/c7a7d097fe0c949c2699febb8cf058ff4137c0c0)	2023-04-27 02:17:08	unknown
sd-webui-aspect-ratio-helper	https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git	main	[99fcf9b0](https://github.com/thomasasfk/sd-webui-aspect-ratio-helper/commit/99fcf9b0a4e3f8c8cac07b12d17b66f12297b828)	2023-06-04 23:39:07	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[b4b5bfef](https://github.com/Mikubill/sd-webui-controlnet/commit/b4b5bfefb0d29d23f6b308f6369c4a989e74b112)	2024-04-22 04:51:20	unknown
sd-webui-infinite-image-browsing	https://github.com/zanllp/sd-webui-infinite-image-browsing	main	[cadbe81c](https://github.com/zanllp/sd-webui-infinite-image-browsing/commit/cadbe81c2462db09c7a8c79d85e9e89a47d2409e)	2024-04-20 23:15:51	unknown
sd-webui-lobe-theme	https://github.com/canisminor1990/sd-webui-lobe-theme.git	main	[b9ab9dc4](https://github.com/canisminor1990/sd-webui-lobe-theme/commit/b9ab9dc480c8f1b153a17ed1bc45fe32822cafb4)	2024-01-17 02:50:35	unknown
sd-webui-supermerger	https://github.com/hako-mikan/sd-webui-supermerger.git	main	[843ca282](https://github.com/hako-mikan/sd-webui-supermerger/commit/843ca282948dbd3fac1246fcb1b66544a371778b)	2024-04-10 21:12:05	unknown
stable-diffusion-webui	https://github.com/catppuccin/stable-diffusion-webui.git	main	[6f1eebbe](https://github.com/catppuccin/stable-diffusion-webui/commit/6f1eebbec4dc1c191899e285ec19d319e34d213c)	2023-04-07 02:22:37	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git	master	[2322caa4](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/2322caa480535b1011a1f9c18126d85ea444f146)	2024-03-09 00:55:37	unknown
ultralytics	https://github.com/ultralytics/ultralytics	main	[5a82b511](https://github.com/ultralytics/ultralytics/commit/5a82b511074617b9daa25000e5672c5d56188374)	2024-04-21 02:58:34	unknown

**Comment by Bing-su** [comment]
This is a bug in upstream, new in 1.9.1. 😿

**Comment by MonkeyDocs** [comment]
Thanks for replying, setting Inpaint only masked padding, pixels to >0 fixed it 👍

**Comment by MonkeyDocs** [comment]
> This is a bug in upstream, new in 1.9.1. 😿
> 
> You get this error only if you set `Inpaint only masked padding, pixels` to `0`

Hey, just letting you know this only works sometimes, now it doesn't process faces on some image (not sure if it's related to resolution of the generated image), it's behaving weirdly

![Screenshot 2024-04-22 235045](https://github.com/Bing-su/adetailer/assets/61049870/afd362db-9077-4d86-a7f7-e95819d67e2f)
