### ISSUE TITLE
[Feature Request] face restore option? (codeformer / gfpgan)

### ISSUE THREAD

**Issue by jmp909** [Bing-su/adetailer#61]
Hi,

specifically related to the feature I raised here this (with example images for the problem)
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8524 ([Feature Request]: face restoration minimum/maximum face size to process)

it would be useful if we could apply Face Restoration to specific faces only, most likely using a size / ratio threshold, so that eg foreground faces can be restored but not those in the background that may have blurred depth of field (although ADetailer still provides some great results without restoration) 

maybe there's a way to configure ADetailer to do this already?

or potentially an option to use the current settings in the main UI, but an option in the ADetailer UI to delay it and apply only to the ADetailer process?

hope the example in the other link better explains it visually anyway!

thanks
J

**Comment by Bing-su** [comment]
I don't want to add more options here. sorry

**Comment by Bing-su** [comment]
I've added the restore faces option.

**Comment by jmp909** [comment]
@Bing-su fantastic, I'll check this out.

I see a the `Mask min/max ratio` too.. this should be really useful thanks

J

**Comment by jmp909** [comment]
perfect thank you!

final codeformer may be a little less sharp here but you can see a bit of an improvement on the eyes

specifically though, background faces are not touched which is great

Original
![original](https://github.com/Bing-su/adetailer/assets/2184982/69ce01c8-90d5-46f4-9efb-ef99f73f7074)

Adetailer
![adetailer](https://github.com/Bing-su/adetailer/assets/2184982/eacb0bf9-0579-4c63-852f-ef4ea9fcc69a)

Adetailer + Codeformer
![adetailer + restore](https://github.com/Bing-su/adetailer/assets/2184982/8b00ef79-afdb-4d56-914f-be886be28de8)
