### ISSUE TITLE
img2img The ADetailer plug-in parameter is lost

### ISSUE THREAD

**Issue by youzisung** [Bing-su/adetailer#612]
### Describe the bug

When I use img2img interface, why does the parameter Steps I previously controlled default to 0 when I use the ADetailer plugin. And my parameters above won't work, resulting in poor quality graphics 

### Steps to reproduce

You only need to use the ADetailer plug-in when using the Img2img interface to generate images that will disappear when you view them in sd

### Screenshots

![adt](https://github.com/Bing-su/adetailer/assets/169972517/0c321ac0-80d7-4e74-bfce-13f010c2b642)

### Console logs, from start to end.

```Shell
no terminal
```

**Comment by Bing-su** [comment]
skip img2img 옵션을 사용했을 때, 이렇게 나옵니다.

**Comment by LucianoDaluz** [comment]
Seems like it ignores any LoRA when using Inpaint
