### ISSUE TITLE
[Bug]: Connections to google-analytics.com when running adetailer

### ISSUE THREAD

**Issue by askAvoid** [Bing-su/adetailer#613]
### Describe the bug

When I create an image with stable-diffusion-webui and enable adetailer, my computer makes requests to www.google-analytics.com

### Steps to reproduce

1. Generate a picture without a detailer - just requests for localhost (/api, /reset, etc)
2. Enable adetailer and generate a picture - now there's a request for google-analytics.com

### Console logs, from start to end.

```Shell
Nothing relevant to this issue appears in the console logs.
```

**Comment by Bing-su** [comment]
I have no idea.

**Comment by hben35096** [comment]
```
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
 Could it be the same situation? When I installed it before, it didn't seem to have appeared

**Comment by flaggx1** [comment]
My own testing and searches showed that adetailer utilizes ultralytics, which in turn uses Google Analytics (ref: https://docs.ultralytics.com/help/privacy/). This page shows you how to disable Google Analytics. I found this solution stopped the network requests upon every generation with adetailer. The following two lines marked with +++ need to be added in different places. Removes the pluses of course, then restart Stable Diffusion completely.

```
File: stable-diffusion-webui/extensions/adetailer/adetailer/__init__.py

from .__version__ import __version__
from .args import ALL_ARGS, ADetailerArgs
from .common import PredictOutput, get_models
from .mediapipe import mediapipe_predict
from .ultralytics import ultralytics_predict
+++ from ultralytics import settings

AFTER_DETAILER = "ADetailer"

+++ settings.update({"sync": False})

__all__ = [
    "__version__",
    "ADetailerArgs",
    "AFTER_DETAILER",
    "ALL_ARGS",
    "PredictOutput",
    "get_models",
    "mediapipe_predict",
    "ultralytics_predict",
]

```
