### ISSUE TITLE
[Feature Request]: Enhancement of Adetailer Script to Allow Multiple Processing Fields

### ISSUE THREAD

**Issue by XT-404** [Bing-su/adetailer#615]
Dear Sir/Madam,

I am writing to you to submit a request for an enhancement to the Adetailer script, which I regularly use in my work.

Currently, it is possible to use two processing fields with this script. For my part, I primarily use the face_mesh_detailer model for the face and the face_mesh_eyes_only model for the eyes. However, to further improve the quality of my work, I would like to be able to use additional models, such as the hand model or other specialized models.

Therefore, I would like to know if it would be possible to add the functionality to use three or four processing models simultaneously in the Adetailer script. If a workaround or alternative method already exists to bypass this limitation and allow the use of multiple models, I would also be grateful for information on this.

Thank you in advance for your attention to my request. I remain at your disposal for any further information.

Sincerely,

![image](https://github.com/Bing-su/adetailer/assets/128090530/87cc1789-aa6f-4dd7-91c6-246b9f4fadc0)

### Describe alternatives you've considered

no idea

**Comment by Bing-su** [comment]
![chrome_cEJ0TEHsS1](https://github.com/Bing-su/adetailer/assets/37621276/c8eb2e59-bc1d-465c-94e9-6d6c961784b4)
That option already exists.

**Comment by XT-404** [comment]
@Bing-su ho ok , thx :) ♥
