### ISSUE TITLE
[Bug]: requirements conflict

### ISSUE THREAD

**Issue by ananosleep** [Bing-su/adetailer#616]
### Describe the bug

mediapipe>=0.10.13 needs protobuf>=4 while open-clip-torch==2.20.0 (claimed in requirements_version.txt of main WebUI) requires protobuf<4. Since mediapipe 0.10.11 also work, why force user to use new version with conflict?

### Steps to reproduce

Just install.

### Console logs, from start to end.

```Shell
Logs isn't needed since it's just about requirements.
```

**Comment by Bing-su** [comment]
나름 이 문제에 대해 열심히 조사했습니다.

텐서플로우를 사용하는 다른 확장과의 호환을 위해 protobuf의 버전을 4 이상으로 올릴 필요가 있었습니다. 여기서 문제가 된 게 `open-clip-torch` 패키지와의 호환성이었는데, 해당 깃허브의 커밋 로그에서 protobuf의 버전 제한이 오직 transformers 4.31.0 버전에서 해결된 토크나이저의 어떤 문제 때문에 고정되어 있다는 사실을 확인할 수 있었습니다. 

그래서 transformers 4.31.0 버전 이상을 설치하도록 시도해보았는데, clip 토크나이저와 관련된 다른 문제가 발생하여 취소했습니다.
대신에 webui에서 open-clip-torch가 protobuf 3을 요구했던 기능을 사용하지 않는다는 것을 확인하고 버전을 올려도 문제없을것으로 봤습니다.

다른 문제가 있다면 알려주세요.

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/actions/runs/8679631484

그리고 사실 그동안 macOS에서 mediapipe가 제대로 동작하지 않고 있었습니다. 이 문제는 mediapipe 0.10.13에서 해결되었습니다.
