### ISSUE TITLE
[Bug]: Disabling support for feedback tensors.

### ISSUE THREAD

**Issue by XT-404** [Bing-su/adetailer#617]
### Describe the bug

hello, since the update I have had this message constantly, although I had no problem before

Since then I have had weird faces

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1716224470.718558   20328 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1716224470.722138   10672 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

### Steps to reproduce

update

### Screenshots

![image](https://github.com/Bing-su/adetailer/assets/128090530/6a87b95e-dbb3-432b-a1ea-bd595163229c)

![image](https://github.com/Bing-su/adetailer/assets/128090530/a9bfbd69-bfa8-4b00-acaf-81280c99f4dd)

![image](https://github.com/Bing-su/adetailer/assets/128090530/4f5818ea-ad5c-47eb-bd93-26a8a06f81ba)

### Console logs, from start to end.

```Shell
venv "W:\A1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements

Check mmcv version...
Your mmcv version 2.0.1 may not work with mmyolo.
or you need to fix version restriction of __init__.py of mmyolo manually, to use mmcv 2.1.0 with mmyolo.
Check mmengine version...
your mmengine version is 0.8.5

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 24.4.2, num models: 10
Loading weights [3028167bcf] from W:\A1111\stable-diffusion-webui\models\Stable-diffusion\!!TEST§§\NoosRealCartoonV1.fp16.safetensors
Creating model from config: W:\A1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
 Total 8 mmdet, 7 yolo and 3 mediapipe models.
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\bbox\face_yolov8n.pth!
 You can enable model validity tester in the Settings-> μ DDetailer.
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\bbox\face_yolov8s.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\bbox\hand_yolov8n.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\bbox\hand_yolov8s.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\bbox\mmdet_anime-face_yolov3.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\segm\mmdet_dd-person_mask2former.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\segm\yolov5_ins_n.pth!
SUCCESS - success to load config for W:\A1111\stable-diffusion-webui\models\mmdet\segm\yolov5_ins_s.pth!
 Total 8 valid mmdet configs are found.
 You can disable validity tester in the Settings-> μ DDetailer.
Check config files...
Done
loading.. cn_modole
 - default µ DDetailer model= bbox/face_yolov8n.pth [882ebbb6]
 - default µ DDetailer model= bbox/face_yolov8n.pth [882ebbb6]
Loading VAE weights specified in settings: W:\A1111\stable-diffusion-webui\models\VAE\vae-Evil-666-Bitch_v100.pt
Running on local URL:  http://127.0.0.1:7861
```

**Comment by XT-404** [comment]
I have already returned to an old version 24.3.0, this does not change the problem, since the update it has changed something and I have the error in a loop, the generations with Adetailer in support have become distorted

**Comment by XT-404** [comment]
always the same anomaly

**Comment by XT-404** [comment]
I installed the very latest version of A1111, version: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.9.3

I have exactly the same anomaly on the last version provided, it really comes from a code problem

**Comment by XT-404** [comment]
*** Error running install.py for extension W:\A1111\stable-diffusion-webui\extensions\adetailer.
*** Command: "W:\A1111\stable-diffusion-webui\venv\Scripts\python.exe" "W:\A1111\stable-diffusion-webui\extensions\adetailer\install.py"
*** Error code: 1
*** stdout: Collecting protobuf<=4.9999,>=4.25.3
***   Using cached protobuf-4.25.3-cp310-abi3-win_amd64.whl (413 kB)
*** Installing collected packages: protobuf
***   Attempting uninstall: protobuf
***     Found existing installation: protobuf 3.20.3
***     Uninstalling protobuf-3.20.3:
***       Successfully uninstalled protobuf-3.20.3
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
***     WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Accs refus: 'W:\\A1111\\stable-diffusion-webui\\venv\\Lib\\site-packages\\google\\~-otobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (w:\a1111\stable-diffusion-webui\venv\lib\site-packages)
***
*** [notice] A new release of pip available: 22.3.1 -> 24.0
*** [notice] To update, run: W:\A1111\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
*** Traceback (most recent call last):
***   File "W:\A1111\stable-diffusion-webui\extensions\adetailer\install.py", line 79, in <module>
***     install()
***   File "W:\A1111\stable-diffusion-webui\extensions\adetailer\install.py", line 68, in install
***     run_pip(*pkgs)
***   File "W:\A1111\stable-diffusion-webui\extensions\adetailer\install.py", line 41, in run_pip
***     subprocess.run([sys.executable, "-m", "pip", "install", *args], check=True)
***   File "C:\Users\XT404\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
***     raise CalledProcessError(retcode, process.args,
*** subprocess.CalledProcessError: Command '['W:\\A1111\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'protobuf>=4.25.3,<=4.9999']' returned non-zero exit status 1.

**Comment by XT-404** [comment]
*** Error executing callback ui_settings_callback for W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\script_callbacks.py", line 171, in ui_settings_callback
        c.callback()
      File "W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 873, in on_ui_settings
        .needs_reload_ui(),
    AttributeError: 'OptionInfo' object has no attribute 'needs_reload_ui'

**Comment by Bing-su** [comment]
```sh
*** ERROR: Could not install packages due to an OSError: [WinError 5] Accs refus: 'W:\A1111\stable-diffusion-webui\venv\Lib\site-packages\google\~-otobuf\internal\_api_implementation.cp310-win_amd64.pyd'
*** Check the permissions.
```

This seems to be the root of the problem:

Check the permissions of your W: drive.

**Comment by XT-404** [comment]
Hello, @Bing-su 

The hard drive never had permission issues before the update. I've checked all the permissions and everything is set to full control (see screenshot). The anomaly persists across all hard drives; I've changed A1111 on all my NVMe or SSD drives. I get the exact same error message.

And this has been the case since the update provided yesterday.

I had never received this message before, and this message does not appear with any other extension than this one.

![image](https://github.com/Bing-su/adetailer/assets/128090530/6f713498-ce8f-489d-aa94-56f4180afa25)
![image](https://github.com/Bing-su/adetailer/assets/128090530/9a71ac03-3f24-46ee-b795-c0e631f34b77)
![image](https://github.com/Bing-su/adetailer/assets/128090530/c0ad8a27-8c28-4c48-8746-a81d74050da5)
![image](https://github.com/Bing-su/adetailer/assets/128090530/8cdcc30b-1bde-481e-9b2f-5fb32602b4aa)
 loading extension : 
 
 ** Error executing callback ui_settings_callback for W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\script_callbacks.py", line 171, in ui_settings_callback
        c.callback()
      File "W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 873, in on_ui_settings
        .needs_reload_ui(),
    AttributeError: 'OptionInfo' object has no attribute 'needs_reload_ui'

Generation error: 

W0000 00:00:1716309000.910288   17092 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

**Comment by Bing-su** [comment]
제발 로그 좀 잘라서 올리지 말고 전체를 다 올려주면 안됩니까? 그렇게 잘라서 올리시니까 저도 이게 webui 버전문제인지 pip 설치 실패 문제인지 권한 문제인지 알 수가 없습니다.

**Comment by XT-404** [comment]
Totaly Journal : @Bing-su 
Running as administrator.

launching stable-diffusion-webui at W:\A1111\stable-diffusion-webui
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1-100-g8b036d8a
Commit hash: 8b036d8a8253996f2a9c977bea63babbe59eb348


Launching Web UI with arguments: --autolaunch --theme=dark --force-enable-xformers --xformers
[-] ADetailer: Support for webui versions below 1.6.0 will be discontinued.
[-] ADetailer initialized. version: 24.5.1, num models: 10
Loading weights [3028167bcf] from W:\A1111\stable-diffusion-webui\models\Stable-diffusion\!!TEST§§\NoosRealCartoonV1.fp16.safetensors
*** Error executing callback ui_settings_callback for W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "W:\A1111\stable-diffusion-webui\modules\script_callbacks.py", line 171, in ui_settings_callback
        c.callback()
      File "W:\A1111\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py", line 873, in on_ui_settings
        .needs_reload_ui(),
    AttributeError: 'OptionInfo' object has no attribute 'needs_reload_ui'

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: W:\A1111\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
W:\A1111\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Startup time: 12.1s (prepare environment: 5.8s, import torch: 2.3s, import gradio: 0.5s, setup paths: 0.5s, other imports: 0.6s, list SD models: 0.4s, load scripts: 1.2s, create ui: 0.4s, gradio launch: 0.3s).
Loading VAE weights specified in settings: W:\A1111\stable-diffusion-webui\models\VAE\vae-Evil-666-Bitch_v100.pt
Applying attention optimization: xformers... done.
Model loaded in 2.5s (load weights from disk: 0.6s, create model: 0.2s, apply weights to model: 0.9s, apply half(): 0.2s, load VAE: 0.1s, move model to device: 0.3s, calculate empty prompt: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.10it/s]
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1716326629.699816   18640 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1716326629.703369   15568 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
mediapipe: 1 detected.
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 14.11it/s]

**Comment by XT-404** [comment]
@Bing-su 
I'm waiting for feedback on the subject, I even found a topic from another person who has exactly the same error message:

https://stackoverflow.com/questions/78493742/feedback-manager-requires-a-model-with-a-single-signature-inference

**Comment by XT-404** [comment]
Additional information I went back to the version: 24.3.5 and no more errors, so this confirms that there is an anomaly in the code with supporting evidence

![image](https://github.com/Bing-su/adetailer/assets/128090530/bcf3273d-0a87-4e7e-b343-cad97d84557d)

**Comment by Bing-su** [comment]
해당 '경고'는 '에러'가 아니며, 이미지 생성에 아무 영향을 주지 않는 것을 확인했습니다. 이 경고는 mediapipe 0.10.13버전부터 출력됐으며, 조용하게 만들 방법을 찾고 있습니다.

**Comment by XT-404** [comment]
So what is the solution to make this message disappear from mediapipe 0.10.13?

**Comment by XT-404** [comment]
Still no feedback on resolving this bug; honestly, it's not professional. I'm leaving Adetailer to switch to a competitor. I've never seen such a thing: a developer claiming he's unable to fix his own code and talking nonsense!!!!

**Comment by Tom2112** [comment]
> Additional information I went back to the version: 24.3.5 and no more errors

XT-404, I'm also having the same problem with ADetailer. It is very frustrating. How did you revert to v24.3.5? I'm having trouble finding where to download it so I can manually overwrite the latest version with it. All I can find on the github page is the latest version. If you could post a link to the old version that works, I would appreciate it.

**Comment by Tom2112** [comment]
I reverted back to v24.3.5 of ADetailer, but I'm still having problems. Now I get this:
`100%|██████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:14<00:00,  2.82it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00,  8.03it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:13<00:00,  1.52it/s]
W0000 00:00:1717953999.624599   10564 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1717953999.632039   28664 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
*** Error running postprocess_image: M:\A1111-2\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "M:\A1111-2\stable-diffusion-webui\modules\scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "M:\A1111-2\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py", line 159, in wrapper
        raise error from None
    AttributeError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                        System info                                                           │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓   │
    │ ┃             ┃ Value                                                                                                    ┃   │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩   │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                                │   │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]                         │   │
    │ │     Version │ v1.9.4                                                                                                   │   │
    │ │      Commit │ feee37d75f1b168768014e4634dcb156ee649c05                                                                 │   │
    │ │ Commandline │ ['launch.py', '--autolaunch', '--xformers']                                                              │   │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.2.18', 'mediapipe': '0.10.14'} │   │
    │ └─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────┘   │
    │                                                            Inputs                                                            │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                 ┃ Value                                                                                                  ┃ │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │          prompt │ score_9, score_8_up, score_7_up, 1girl, {small breasts|medium breasts, skinny}, (small ass, narrow     │ │
    │ │                 │ hips:1.1), petite, {stylish|black|red|purple|white|ivory|yellow|blue|green|(dark green:1.1)|(dark      │ │
    │ │                 │ blue:1.1)|pastel|(rainbow:1.1)|pink} lace trim, __ttb2112/hair-style__, __ttb2112/hair-color__,        │ │
    │ │                 │ {freckles|tan lines|eye shadow}, __ttb2112/eye-color__, off-shoulder top and mini skirt, lacy, sheer,  │ │
    │ │                 │ shiny cloth, choker, {thong, |}dancing at a rooftop party, under string lights, lively, festive,       │ │
    │ │                 │ youthful, dynamic, neon palette, festive, at night, {small demure smile|(dancing:1.1)|(from behind,    │ │
    │ │                 │ looking at viewer, small ass, narrow hips:1.1)}, highly detailed background, highly detailed hair,     │ │
    │ │                 │ perfect hands, ({7$$, $$__ttb2112/female-descriptives-short__}:1.1)                                    │ │
    │ │ negative_prompt │ score_1, score_2, score_3, score_4, score_5, score_6, immature, child, childlike, lolita, loli, shota, │ │
    │ │                 │ large ass, thick thighs, watermark, text, signature, logo, monochrome, censored, extra limbs, (bad     │ │
    │ │                 │ hands, extra fingers), bad anatomy, muscular, censored, disfigured, ugly, amputee, shoes, pom-poms,    │ │
    │ │                 │ simple background                                                                                      │ │
    │ │          n_iter │ 1                                                                                                      │ │
    │ │      batch_size │ 1                                                                                                      │ │
    │ │           width │ 960                                                                                                    │ │
    │ │          height │ 544                                                                                                    │ │
    │ │    sampler_name │ Restart                                                                                                │ │
    │ │       enable_hr │ True                                                                                                   │ │
    │ │     hr_upscaler │ 4x-UltraSharp                                                                                          │ │
    │ │      checkpoint │ Pony\serendipityPDXL_v10.safetensors [81a312fca7]                                                      │ │
    │ │             vae │ sdxl_vae.safetensors                                                                                   │ │
    │ │            unet │ Automatic                                                                                              │ │
    │ └─────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                        ADetailer                                                                                             │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                      │
    │ ┃                     ┃ Value                         ┃                                                                      │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                                                      │
    │ │             version │ 24.3.5                        │                                                                      │
    │ │            ad_model │ mediapipe_face_mesh_eyes_only │                                                                      │
    │ │           ad_prompt │                               │                                                                      │
    │ │  ad_negative_prompt │                               │                                                                      │
    │ │ ad_controlnet_model │ None                          │                                                                      │
    │ │              is_api │ False                         │                                                                      │
    │ └─────────────────────┴───────────────────────────────┘                                                                      │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                         │
    │ │ M:\A1111-2\stable-diffusion-webui\extensions\adetailer\adetailer\traceback.py:139 in wrapper     │                         │
    │ │                                                                                                  │                         │
    │ │   138 │   │   try:                                                                               │                         │
    │ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │                         │
    │ │   140 │   │   except Exception as e:                                                             │                         │
    │ │                                                                                                  │                         │
    │ │ M:\A1111-2\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:824 in              │                         │
    │ │ postprocess_image                                                                                │                         │
    │ │                                                                                                  │                         │
    │ │    823 │   │   │   │   │   continue                                                              │                         │
    │ │ ❱  824 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │                         │
    │ │    825                                                                                           │                         │
    │ │                                                                                                  │                         │
    │ │ M:\A1111-2\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:750 in              │                         │
    │ │ _postprocess_image_inner                                                                         │                         │
    │ │                                                                                                  │                         │
    │ │    749 │   │   masks = self.pred_preprocessing(p, pred, args)                                    │                         │
    │ │ ❱  750 │   │   shared.state.assign_current_image(pred.preview)                                   │                         │
    │ │    751                                                                                           │                         │
    │ │                                                                                                  │                         │
    │ │ M:\A1111-2\stable-diffusion-webui\modules\shared_state.py:165 in assign_current_image            │                         │
    │ │                                                                                                  │                         │
    │ │   164 │   def assign_current_image(self, image):                                                 │                         │
    │ │ ❱ 165 │   │   if shared.opts.live_previews_image_format == 'jpeg' and image.mode == 'RGBA':      │                         │
    │ │   166 │   │   │   image = image.convert('RGB')                                                   │                         │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                         │
    │ AttributeError: 'NoneType' object has no attribute 'mode'                                                                    │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---`

**Comment by XT-404** [comment]
@Tom2112
hello, I haven't found any solution, this error linked to Adetailer and present on all its versions, I therefore released Adetailer, given that the developer is unable to resolve the problems he created, I I therefore decided to release its extension burst on the ground, and to do without, thus finished the errors, I advise you to do the same, I think that the guy who dev adetailer uses gpt, he understands nothing of what long he is saying and lost himself in his own thing .

**Comment by Tom2112** [comment]
Sorry, @XT-404, I'm having trouble understanding you. Are you saying you just stopped using ADetailer? That's what I've done. Which is rather annoying, since it was very good at improving eyes and faces. I haven't found any alternatives that I like. Have you?

**Comment by Bing-su** [comment]
@Tom2112 

Before we go any further, let's check it out. Which of the following is the problem you're talking about?

1. it's annoying to see that warning message in the console window.

2. the image generation is weird, and I think it's related to this warning.

**Comment by Bing-su** [comment]
This warning was added in version 0.10.13 of mediapipe and states that when using the legacy solution of mediapipe, the feedback tensor feature is disabled. I have already verified that this is just a warning and does not affect the functionality.

**Comment by Tom2112** [comment]
> Before we go any further, let's check it out. Which of the following is the problem you're talking about?
>     1. it's annoying to see that warning message in the console window.
>     2. the image generation is weird, and I think it's related to this warning.

Actually, I don't mean either of those two things. For me, the image generation isn't weird, it just refuses to do the ADetailer steps at all. The warning message is just a symptom. The fact that it doesn't run ADetailer is the problem. So it's annoying that it doesn't do the face/eye fixes that I had planned it to do.

**Comment by Tom2112** [comment]
> This warning was added in version 0.10.13 of mediapipe and states that when using the legacy solution of mediapipe, the feedback tensor feature is disabled. I have already verified that this is just a warning and does not affect the functionality.

You mention mediapipe specifically. Do you believe the problem is only with the mediapipe model files? I haven't tried the yolo files.

**Comment by Bing-su** [comment]
This is actually a functionality of mediapipe.

https://github.com/google-ai-edge/mediapipe/blob/c37721b9df27b03da34ff304696c2ed3c6d2b4cf/mediapipe/calculators/tensor/inference_feedback_manager.cc#L114-L117

**Comment by DotPoker2** [comment]
so 

> This is actually a functionality of mediapipe.
> 
> https://github.com/google-ai-edge/mediapipe/blob/c37721b9df27b03da34ff304696c2ed3c6d2b4cf/mediapipe/calculators/tensor/inference_feedback_manager.cc#L114-L117

so what does this now mean? do we update mediapipe or just ignore the warning?
