### ISSUE TITLE
[Feature Request]: Fix face (Upside down and facing up)

### ISSUE THREAD

**Issue by timmyhk852** [Bing-su/adetailer#618]
### Is your feature request related to a problem? Please describe.

When I generate pictures of a person whose face is upside down or facing up, his face becomes weird

### Describe the solution you'd like

Fix it if possible

**Comment by 3blackbar** [comment]
yeah adetailer is defo missing face aligner

**Comment by Bing-su** [comment]
잘 모르는 분야입니다.

대신 여기에 괜찮은 구현이 있는 걸로 압니다.

https://github.com/ototadana/sd-face-editor

**Comment by timmyhk852** [comment]
how to roll back to previous versions which seem to be better even when generating facing up images

**Comment by timmyhk852** [comment]
> 잘 모르는 분야입니다.
> 
> 대신 여기에 괜찮은 구현이 있는 걸로 압니다.
> 
> https://github.com/ototadana/sd-face-editor

I used this tool but it shows "no face detected"

**Comment by kalle07** [comment]
this is more a bug of the "image recognition" yolov8n and midiapipe
but anyway adetailer can may check the direction of the face too ?!?

i uploaded a lora, which will help a bit 
https://civitai.com/models/506819?modelVersionId=563320

**Comment by andupotorac** [comment]
> this is more a bug of the "image recognition" yolov8n and midiapipe but anyway adetailer can may check the direction of the face too ?!?
> 
> i uploaded a lora, which will help a bit https://civitai.com/models/506819?modelVersionId=563320

Something like this is needed: https://facerec.gjung.com/FaceAlignment
