### ISSUE TITLE
[Feature Request]: Add Option to Enable or Disable Automatic Download of Huggingface Model Files

### ISSUE THREAD

**Issue by hben35096** [Bing-su/adetailer#619]
### Is your feature request related to a problem? Please describe.

I understand that there is already a --ad-no-huggingface option in the startup parameters. Using this option significantly improves the webui startup speed (by 50 seconds) in cases of poor network connectivity, as it indeed prevents connections to Huggingface. However, it also seems that the Huggingface cache files cannot be correctly read (if they exist).

I would like to add a local_files_only parameter to hf_hub_download in adetailer/common.py, as shown below. The boolean value of LOCAL_FILES_ONLY will determine whether to connect to Huggingface. The benefit of this approach is that when LOCAL_FILES_ONLY = True, it will not connect to Huggingface, but cached files can still be correctly read.

```
from __future__ import annotations

import os
from collections import OrderedDict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from huggingface_hub import hf_hub_download
from PIL import Image, ImageDraw
from rich import print
from torchvision.transforms.functional import to_pil_image

REPO_ID = "Bingsu/adetailer"
_download_failed = False
LOCAL_FILES_ONLY = True  # Define the "local_files_only" option as a global variable.

@dataclass
class PredictOutput:
    bboxes: list[list[int | float]] = field(default_factory=list)
    masks: list[Image.Image] = field(default_factory=list)
    preview: Optional[Image.Image] = None
    

def hf_download(file: str, repo_id: str = REPO_ID) -> str | None:
    global _download_failed

    if _download_failed:
        return "INVALID"

    try:
        path = hf_hub_download(repo_id, file, local_files_only=LOCAL_FILES_ONLY) # Here, the option "local_files_only=LOCAL_FILES_ONLY" is added.
    except Exception: 
        msg = f"[-] ADetailer: Failed to load model {file!r} from huggingface"
        print(msg)
        path = "INVALID"
        _download_failed = True
    return path
```

**Comment by Bing-su** [comment]
괜찮은 생각입니다.

당분간은 이걸 써주세요

https://github.com/Bing-su/adetailer/wiki/HF-environment-variables

**Comment by hben35096** [comment]
@Bing-su 
Thank you, this problem has been bothering me for a long time and now it can finally be solved (✪ω✪)

**Comment by hben35096** [comment]
@KafeD 
![image](https://github.com/Bing-su/adetailer/assets/139383150/2cff0d5c-9666-4ff1-a4e6-9309b2135824)

**Comment by Bing-su** [comment]
@KafeD 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#webui-user
