### ISSUE TITLE
[Feature Request]: Has Anyone Experienced Image Generation Area Freezing?

### ISSUE THREAD

**Issue by hben35096** [Bing-su/adetailer#624]
### Is your feature request related to a problem? Please describe.
After enabling the adetailer plugin, there is a chance that if the number of generated images is set to 1, the image generation area may get stuck on a certain masked image. During this time, the backend output is normal, but the image generation area in the web UI remains unchanged. The only way to restore normal operation is by refreshing the webpage.
![PixPin_2024-05-26_04-49-24](https://github.com/Bing-su/adetailer/assets/139383150/0ca3ebef-5559-4a0d-9f45-ef9340a03d61)

https://github.com/Bing-su/adetailer/assets/139383150/fdf0c59c-75ff-43d7-af79-4928892155c8

If the number of generated images is greater than 1 each time, this issue does not occur.

I can't identify the cause of this problem as there are no error messages. I'm wondering if anyone else has encountered this issue. Perhaps an option could be added to prevent masked images from appearing during image generation?

**Comment by DotPoker2** [comment]
I'm having same issue, even with newest version of 24.6.0, it sometimes works, but now constantly freezes and takes nearly 15 to 20 minutes to cancel the generation during it freezing the Adetailer stage of generation.
