### ISSUE TITLE
UI typo

### ISSUE THREAD

**Issue by jhfong** [Bing-su/adetailer#625]
https://github.com/Bing-su/adetailer/blob/a89c01d357fc9b6c1978cfda597ee19a4b5c5eec/aaaaaa/ui.py#L183
Should be "Enable this tab".

**Comment by Bing-su** [comment]
![스크린샷 2024-05-27 100343](https://github.com/Bing-su/adetailer/assets/37621276/e9350dfb-da0d-4e2a-b1e6-d1b3b171d0cd)
