### ISSUE TITLE
[Feature Request]: count faces and choose

### ISSUE THREAD

**Issue by kalle07** [Bing-su/adetailer#635]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

if i have more than one face in my image
(face_yolov8n)
i see red rectangels around and the number of dectection level
so its possible to count every face ...
and at the end select the face I want to calculate?

### Describe alternatives you've considered

-

**Comment by Bing-su** [comment]
Thanks for suggestion. There is no GUI, but there is a text-based way to do this.

https://github.com/Bing-su/adetailer/wiki/Advanced

**Comment by kalle07** [comment]
i see...
at least its possible easy put the number of the recognized face like the detection level ... may its a first step for more compfort ;)

**Comment by FriedGenera** [comment]
> Thanks for suggestion. There is no GUI, but there is a text-based way to do this.
> 
> https://github.com/Bing-su/adetailer/wiki/Advanced

When using [SEP] for multiple faces it seems to only add one of the faces to the parameters in png info. Any idea why(on webui 1.9.4, it seems to work fine on my older 1.6 webui install)? @Bing-su
