### ISSUE TITLE
How do I create a mask but not optimize it?

### ISSUE THREAD

**Issue by zdoek001** [Bing-su/adetailer#636]
How to create a black and white mask of a face

**Comment by zdoek001** [comment]
> mediapipe_face_mesh

@dosu
Is there an API?

**Comment by Bing-su** [comment]
What are you trying to get the mask image for?

**Comment by zdoek001** [comment]
> What are you trying to get the mask image for?

Once I get the mask image, I'm going to exclude the face from redrawing when it is generated. I'm going to do something else in the next program, so I need this mask for the face

**Comment by Bing-su** [comment]
Can't you just draw the mask image directly in img2img inpaint? I don't see the need for a mask.

**Comment by zdoek001** [comment]
> Can't you just draw the mask image directly in img2img inpaint? I don't see the need for a mask.

If I'm using the Web UI, that can be drawn, but I'm using the Web UI API for the request, as a step in the program, so the implementation of the mask generation needs to be automated

**Comment by Bing-su** [comment]
![chrome_xJgSkCvP8z](https://github.com/Bing-su/adetailer/assets/37621276/6f9b3991-5d6b-4815-b200-ede0336efb97)
The WebUI has this feature so you can get inpaint masks, but it's probably not possible with the API.

**Comment by zdoek001** [comment]
> ! [chrome_xJgSkCvP8z] (https://private-user-images.githubusercontent.com/37621276/339330273-6f9b3991-5d6b-4815-b200-ede0336efb97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzYyNTcsIm5iZiI6MTcxODI3NTk1NywicGF0aCI6Ii8zNzYyMTI3Ni8zMzkzMzAyNzMtNmY5YjM5OTEtNWQ2Yi00ODE1LWIyMDAtZWRlMDMzNmVmYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NTJkZWI3MzE2Nzg2YjUwNjllODAwY2I1ZDNlOTMwMmE5NzFjZTUxOWYwOThmYzY4Y2ZjODUyOGU3ZjEwZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lc1pCMfV4zJmKd5wZ5vU3y9vhr9PTSFxsiGk_gTh8MI) The WebUI has this feature so you can get inpaint masks, but it's probably not possible with the API.

Ok, thanks for the help, is this button in adetailer, please? Or what location? Didn't find it

**Comment by Bing-su** [comment]
![chrome_HGcWbZJwmv](https://github.com/Bing-su/adetailer/assets/37621276/7cf777c7-2f8b-4342-b574-9d9f831e6696)
