### ISSUE TITLE
[Feature Request]: Recursive pass through, like LLM agents

### ISSUE THREAD

**Issue by andupotorac** [Bing-su/adetailer#638]
### Is your feature request related to a problem? Please describe.

Sometimes after aDetailer passes through, the image is still not fixed.

### Describe the solution you'd like

I'd like to tell it how many times to pass through, each time with a random seed, as it may improve the image iteratively - for example a malformed foot/hand could eventually get right through iterations.

**Comment by Bing-su** [comment]
Well, when you have this feature, you want to get the best result, not the last result.
In this case, I'd recommend doing the img2img inpaint directly.

**Comment by andupotorac** [comment]
One could stop iterations when the right image comes through. Sure, it can be a manual process, but so can the entire adetailer flow.
