### ISSUE TITLE
[Feature request] Use separate width/height defaults

### ISSUE THREAD

**Issue by Rogal80** [Bing-su/adetailer#64]
Hi, great work :) love extension. I there any chance that i could set up in UIconfig or else -  Use separate width/height - by default on true and also the resolution for 1k 

![image](https://github.com/Bing-su/adetailer/assets/112553453/3b2bebd3-867e-4971-9cb8-c48eb0b55803)

I notice that i don't have commands in UIconfig for that :(

**Comment by Bing-su** [comment]
I don't plan to change the default. maybe posting the full `ui-config.json` file will help me troubleshoot.

**Comment by Rogal80** [comment]
hi, most stuff in ui-config is for cfg
![image](https://github.com/Bing-su/adetailer/assets/112553453/29737f69-3d6c-4d12-973f-9bddfe86c88e)

and i missing parameters for with and height

**Comment by Bing-su** [comment]
I didn't put the `ADetailer` where it would make it too long. Please fix `Use separate width/height`...

**Comment by Rogal80** [comment]
i am completely noob in code :( - this i need to put in ui-config  ??

customscript/!adetailer.py/txt2img/Use separate width/height/value": true,
customscript/!adetailer.py/txt2img/Use separate width/height/with": 1024,
customscript/!adetailer.py/txt2img/Use separate width/height/height": 1024,

**Comment by Bing-su** [comment]
Don't put anything. just fix

```json
    "txt2img/Use separate width/height/visible": true,
    "txt2img/Use separate width/height/value": false,
    "txt2img/inpaint width/visible": true,
    "txt2img/inpaint width/value": 512,
    "txt2img/inpaint width/minimum": 64,
    "txt2img/inpaint width/maximum": 2048,
    "txt2img/inpaint width/step": 4,
    "txt2img/inpaint height/visible": true,
    "txt2img/inpaint height/value": 512,
    "txt2img/inpaint height/minimum": 64,
    "txt2img/inpaint height/maximum": 2048,
    "txt2img/inpaint height/step": 4,
```

fix here

**Comment by Rogal80** [comment]
thx :)
