### ISSUE TITLE
[Bug]: ADeatailer not working????

### ISSUE THREAD

**Issue by JimbooMan** [Bing-su/adetailer#640]
### Describe the bug

ADetailer is not showing up. I've downloaded and installed it and even rebooted my PC, but still now showing up. What is wrong? It gives me some kind of error in the Terminal It gives me this error

"stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access denied: 'C:\\Users\\larsl\\Desktop\\stablediffsuion\\system\\python\\Lib\\site-packages\\cv2\\cv2.pyd'

*** Consider using the --user option or check the permissions.

***

*** Traceback (most recent call last):

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\[install.py](http://install.py/)", line 77, in <module>

*** install()

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\[install.py](http://install.py/)", line 66, in install

*** run_pip(*pkgs)

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\[install.py](http://install.py/)", line 41, in run_pip

*** [subprocess.run](http://subprocess.run/)([sys.executable, "-m", "pip", "install", *args], check=True)

*** File "[subprocess.py](http://subprocess.py/)", line 524, in run

*** subprocess.CalledProcessError: Command '['C:\\Users\\larsl\\Desktop\\stablediffsuion\\system\\python\\python.exe', '-m', 'pip', 'install', 'ultralytics>=8.2.0', 'mediapipe>=0.10.13', 'rich>=13.0.0']' returned non-zero exit status 1.

*** "Disable all extensions" option was set, will not load any extensions ***"

What should i do??

### Steps to reproduce

Need help

### Console logs, from start to end.

```Shell
"stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access denied: 'C:\\Users\\larsl\\Desktop\\stablediffsuion\\system\\python\\Lib\\site-packages\\cv2\\cv2.pyd'

*** Consider using the --user option or check the permissions.

***

*** Traceback (most recent call last):

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\install.py", line 77, in <module>

*** install()

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\install.py", line 66, in install

*** run_pip(*pkgs)

*** File "C:\Users\larsl\Desktop\stablediffsuion\webui\extensions\adetailer\install.py", line 41, in run_pip

*** subprocess.run([sys.executable, "-m", "pip", "install", *args], check=True)

*** File "subprocess.py", line 524, in run

*** subprocess.CalledProcessError: Command '['C:\\Users\\larsl\\Desktop\\stablediffsuion\\system\\python\\python.exe', '-m', 'pip', 'install', 'ultralytics>=8.2.0', 'mediapipe>=0.10.13', 'rich>=13.0.0']' returned non-zero exit status 1.

*** "Disable all extensions" option was set, will not load any extensions ***"
```

**Comment by Bing-su** [comment]
```
*** "Disable all extensions" option was set, will not load any extensions ***"
```

As you can see here, setting the Disable all extensions option prevents any extensions from being loaded.

There was an error during the installation, but this issue is not related to the error.
