### ISSUE TITLE
[Bug]: ADtailer toolbar is not displayed even after restarting the web ui

### ISSUE THREAD

**Issue by yumuza** [Bing-su/adetailer#643]
### Describe the bug

After starting the web ui with Google colab, the ADtailer toolbar is not displayed even after installing ADtailer and restarting.
When I look at the console log, it says [RuntimeError: [-] ADtailer: WebUI versions below 1.6.0 are not supported.]

Is ADtailer no longer compatible with web ui1.6 or lower?

### Steps to reproduce

After starting the web ui with Google colab, install ADtailer using the steps described.

### Console logs, from start to end.

```Shell
*** Error loading script: !adetailer.py
    Traceback (most recent call last):
      File "/content/microsoftexcel/extensions/adetailer/aaaaaa/conditional.py", line 6, in <module>
        from modules.processing import create_binary_mask  # noqa: F401
    ImportError: cannot import name 'create_binary_mask' from 'modules.processing' (/content/microsoftexcel/modules/processing.py)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/content/microsoftexcel/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/microsoftexcel/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/microsoftexcel/extensions/adetailer/scripts/!adetailer.py", line 18, in <module>
        from aaaaaa.conditional import create_binary_mask, schedulers
      File "/content/microsoftexcel/extensions/adetailer/aaaaaa/conditional.py", line 8, in <module>
        raise RuntimeError(msg) from e
    RuntimeError: [-] ADetailer: WebUI versions below 1.6.0 are not supported.
```

**Comment by kevin10f** [comment]
> @yumuza Hello there! I'm here to help you with any bugs, questions, or contributions. Feel free to ask for assistance while we wait for a human maintainer.
> 
> ADtailer is no longer compatible with WebUI versions 1.6.0 or lower. The error message you encountered confirms this:
> 
> ```
> RuntimeError: [-] ADetailer: WebUI versions below 1.6.0 are not supported.
> ```
> 
> To resolve this issue, you need to upgrade your WebUI to version 1.6.0 or higher. This compatibility requirement is explicitly stated in the ADtailer code [[1]](https://github.com/Bing-su/adetailer/blob/main/aaaaaa/conditional.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu , is there any way we can run on webui lower than version 1.6.0 ? I don't want to update my WebUI version for various reasons.

**Comment by Bing-su** [comment]
You can use the previous version. Please do not auto update.
https://github.com/Bing-su/adetailer/archive/refs/tags/v24.5.1.zip
