### ISSUE TITLE
[Feature Request]: Option to use hires fix settings

### ISSUE THREAD

**Issue by StylusEcho** [Bing-su/adetailer#644]
### Is your feature request related to a problem? Please describe.

I currently have an A1111 workflow where I run the first pass on one checkpoint, and hires fix on a different one. I noticed that once ADetailer starts, it will revert back to the first pass settings, including the checkpoint. If the two checkpoints are drastically different in style this causes some issues as you can imagine.

### Describe the solution you'd like

Checkbox option in settings tab, to pass on the hires fix settings to ADetailer, or at least find a way to keep the hires checkpoint loaded throughout the ADetailer pass.

**Comment by Bing-su** [comment]
Well, isn't it enough to specify the checkpoint directly?

**Comment by StylusEcho** [comment]
> Well, isn't it enough to specify the checkpoint directly?

I thought of this, but that means the checkpoint would need to be selected for each job.
Currently my process for first pass is to run with ADetailer enabled and without Hires fix. This gets a low res image but with nice faces.
Then I set hires fix as desired, and hit the "Create an upscaled version of the current image using hires fix settings" button underneath the image. This runs the hires fix pass on the previous image, which is a good starting point for upscaling with good quality faces. Then it runs ADetailer once more after.

The result is a high res image with excellent quality on the faces/etc, without fundamentally changing too much.
Currently, I would need to manually change checkpoints on each tab at least twice per image.
