### ISSUE TITLE
[Feature Request]: Add Use same sampler option

### ISSUE THREAD

**Issue by StylusEcho** [Bing-su/adetailer#645]
### Is your feature request related to a problem? Please describe.

The img2img pass by default uses a varied number of steps depending on the denoising strength, and it seems some schedulers work better on lower/higher steps than others. Sometimes it would be helpful to be able to override the Scheduler only without touching the Sampler.

### Describe the solution you'd like

Add "Use same sampler" to samplers dropdown, bringing it in line with the other dropdown options.

**Comment by Bing-su** [comment]
Prior to webui version 1.9.0, there was no need for that option because samplers and schedulers were not divided. I'll consider it.

**Comment by StylusEcho** [comment]
Thank you. I suppose you technically might not need the checkbox for "Use separate sampler" with this change also.

**Comment by StylusEcho** [comment]
I saw that you've added this feature, many thanks!
