### ISSUE TITLE
`from modules.shared import *` causing web UI to load VAE too early

### ISSUE THREAD

**Issue by catboxanon** [Bing-su/adetailer#65]
https://github.com/Bing-su/adetailer/blob/209b703fbf310e1d212e833c03aae6d72f9a604e/sd_webui/shared.py#L41-L42

This section above is causing the web UI to attempt to resolve the VAE too early, as the scripts entrypoint is before the VAE list is loaded. This results in an error like this being printed to the console, and ultimately no VAE being loaded. The VAE must be manually changed after the fact to fix it.
```
Couldn't find VAE named vae-ft-mse-840000-ema-pruned.ckpt; using None instead
```

Call stack via Visual Studio Code. Note in `webui.py` that the script initialization (line 191) happens before the VAE list is loaded (line 197):
![image](https://github.com/Bing-su/adetailer/assets/122327233/71592fe6-d355-4cae-b641-840a0c6a04f5)

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a6b618d07248267de36f0e8f4a847d997285e272/webui.py#L191-L198

**Comment by Bing-su** [comment]
Thanks for pointing this out. While testing, I noticed that the [vladmandic/sd-extension-system-info](https://github.com/vladmandic/sd-extension-system-info) also causes the same problem, so maybe there are more extensions that cause this problem.
