### ISSUE TITLE
[Report]: what is going on with the output?

### ISSUE THREAD

**Issue by SonicSaber** [Bing-su/adetailer#650]
### Describe the bug

I do cleaning a cache a lot, so ADetailer will always redownload them when I start webui
it does look as it should on my local Windows

the screenshot is from Kaggle Linux Jupyter Notebook.

it does not look like this before, I don't remember which version tho.

### Steps to reproduce

run stable diffusion webui with adetailer installed on jupyter notebook.

### Screenshots

![a](https://github.com/Bing-su/adetailer/assets/154011906/f065110c-3ed1-4c6c-84c6-ff218a16923e)

![kaggle](https://github.com/Bing-su/adetailer/assets/154011906/874a8bfc-f592-48ef-b45e-bb1ad6b9982f)

### Console logs, from start to end.

```Shell
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
Version: 1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05

[-] ADetailer initialized. version: 24.6.0, num models: 18
```

**Comment by Bing-su** [comment]
This looks normal to me. Please be more specific about what you are reporting as an issue.

**Comment by GlamoramaAttack** [comment]
Please stop relying on Huggingsface's CACHE. I don't want that on my C: drive! Cached files are meant to be temporary not permanent. There is a folder called ADETAILER (in models), please direct them there. And most of the yolov-models are already in my ULTRALYTICS folder. The HF cache is wasting my desktop space with downloading models that are already somewhere in the WEBUI. And the extension ignores to scan the folders as set in the settings for Adetailer ("Extra paths to scan adetailer models separated by vertical bars") - is this only for use inside the WEBUI? It should scan while launching WEBUI. Aside from that WEBUI is supposed to work offline too, almost all other extensions except Bing-su's accept that and download to where the WEBUI is located, to make it easier for portable use. Symlinked files in the CACHE can't be moved. Please consider to change it.
