### ISSUE TITLE
[Feature Request]: Is requiring mediapipe>=0.10.13 too strict?

### ISSUE THREAD

**Issue by hben35096** [Bing-su/adetailer#655]
### Is your feature request related to a problem? Please describe.

Hello, in the pyproject.toml file, requiring mediapipe>=0.10.13 seems too strict. The latest version is mediapipe 0.10.14, which means that only versions 0.10.13 and 0.10.14 can be chosen. Could you please relax the version requirement a bit?

**Comment by Bing-su** [comment]
I've set it to a version that doesn't cause errors on macOS. Are you having any issues with the version?

**Comment by hben35096** [comment]
mediapipe 0.10.14 has requirement protobuf<5,>=4.25.3,

But
stable-diffusion-webui/requirements_versions.txt
and
stable-diffusion-webui/repositories/generative-models/requirements/pt2.txt
and
stable-diffusion-webui/repositories/generative-models/requirements/pt13.txt
Both require:
open-clip-torch==2.20.0

So every time I start stable-diffusion-webui, open-clip-torch becomes 2.20.0

open-clip-torch 2.20.0 has requirement protobuf<4, but you have protobuf 4.25.3.

**Comment by Bing-su** [comment]
I did some research on this issue.

First of all, mediapipe works fine with a protobuf of 3. And I found that the reason open-clip-torch has a protobuf version limit is because of the sentencepiece restriction in transformers, which doesn't really cause any problems. So it works fine.

**Comment by hben35096** [comment]
> I did some research on this issue.
> 
> First of all, mediapipe works fine with a protobuf of 3. And I found that the reason open-clip-torch has a protobuf version limit is because of the sentencepiece restriction in transformers, which doesn't really cause any problems. So it works fine.

Thank you for pointing this out. I was being too fixated.
