### ISSUE TITLE
[Feature Request]:  How to use code with prompt instead of ComfyUI and SDA1111

### ISSUE THREAD

**Issue by khawar-islam** [Bing-su/adetailer#659]
### Is your feature request related to a problem? Please describe.

I want to use the codebase where i can provide the picture and it fix the hand and face issue. I have implemented huggingface code but it detects the hand and face but do not fix this problem.

```
from huggingface_hub import hf_hub_download
from ultralytics import YOLO

path = hf_hub_download("Bingsu/adetailer", "hand_yolov9c.pt")
model = YOLO(path)

import cv2
from PIL import Image

img = "/home/cvpr/Downloads/imgtesting.webp"
output = model(img)
pred = output[0].plot()
pred = cv2.cvtColor(pred, cv2.COLOR_BGR2RGB)
pred = Image.fromarray(pred)
pred.save("ddd.jpg")
```

### Describe the solution you'd like

I need a code without comfyUI and SDAutomatic1111 where i can fix the hand and face.

### Describe alternatives you've considered

No

**Comment by Bing-su** [comment]
It only has the ability to detect specific parts of an image. Then, it calls the inpainting API via SDWebUI. 

So you can't do inpainting without a backend.

**Comment by khawar-islam** [comment]
I am also trying to fix the hand but still there are problems with finger, could you please check this thread? 

https://www.reddit.com/r/StableDiffusion/comments/1e19gbn/comment/lcsqg76/?context=3

**Comment by Bing-su** [comment]
It's hard to fix hands with just inpainting. Try ControlNet's [hand refiner](https://github.com/Mikubill/sd-webui-controlnet/pull/2394).
