### ISSUE TITLE
[Issue]: After Detailer causes UI Progress bar to break

### ISSUE THREAD

**Issue by brknsoul** [Bing-su/adetailer#66]
When using After Detailer, it seems that the UI progress bar is counting each After Detailer operation as a completed image generation, causing the UI progress bar to complete early.

This doesn't affect generating at all, it's just a visual UI bug.

Posted from https://github.com/vladmandic/automatic/issues/1044

**Comment by Bing-su** [comment]
It is because it's hard to calculate how many extra steps the ADetailer will take. This has been an issue since I started developing this extension, and I don't have any ideas to improve it yet.

**Comment by dalgibbard** [comment]
![image](https://github.com/Bing-su/adetailer/assets/1159620/70676486-6c91-4bba-83d7-1d56303ce768)

Noticed this also - you can see that with 45 steps and a batch size of 10, the first "steps" pass brings the progress bar to 45/450

And then, adetailer runs with 19 steps each, and increases this total by 19; to 64/450.

I haven't looked at the code, but is it possible to track the progress independently, and not using the existing progress counter? This would be in-keeping with how something like upscaling currently works too (basically just blindly waiting during post-processing, without touching the main overall progress counter).

**Comment by brknsoul** [comment]
Looks like this has been fixed to not break the UI progress bar. The UI seems to detect a new process and will adjust the progress bar accordingly.
