### ISSUE TITLE
[Bug]:  two faces are detected for one face

### ISSUE THREAD

**Issue by elistys** [Bing-su/adetailer#669]
### Describe the bug

I am having trouble with the problem that two faces are detected for one face and processed twice.

The situation remains the same whether I set the “Detection model confidence threshold” to 0.01 or 1.0.

There are multiple people on the screen, so I cannot set “Mask only the top k largest (0 to disable)” to 1.

I don't know if this is a bug or a problem with accuracy.

Is there any way to improve this?

Environment
ADetailer:v24.1.2
mediapipe_face_full
A1111 webUI:v1.7.0
M2 mac mini

### Steps to reproduce

Use mediapipe_face_full.

### Screenshots

![001](https://github.com/user-attachments/assets/d7880fdc-7cb7-465d-92e0-87fc811244b9)
![002](https://github.com/user-attachments/assets/90dd50d2-c904-4754-afea-efb02413f98b)

### Console logs, from start to end.

```Shell
mediapipe: 2 detected.
100%|█████████████████████████████████████████████| 9/9 [00:11<00:00,  1.29s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:09<00:00,  1.08s/it]
```

**Comment by Bing-su** [comment]
It's not common for machine learning models to fail to detect them, but it does happen. Try sending them to the img2img tab and inpainting them yourself.

**Comment by elistys** [comment]
Thanks for the reply.

I think this is the limit of accuracy and will give up.
