### ISSUE TITLE
[Feature Request]: add adetailer model hashes in pnginfo

### ISSUE THREAD

**Issue by bluelovers** [Bing-su/adetailer#675]
### Is your feature request related to a problem? Please describe.

 add adetailer model hashes in pnginfo

**Comment by SonicSaber** [comment]
yeah, also maybe something to automatically enable the ADetailer when we send from pnginfo to txt2img

**Comment by bluelovers** [comment]
https://github.com/bluelovers/sd-webui-pnginfo-injection/commit/95c603c54e27465bef151eb9b8657b8ddab32478
