### ISSUE TITLE
Would it be possible to disable the "1st" Tab model option?

### ISSUE THREAD

**Issue by TKS4** [Bing-su/adetailer#68]
The 2nd Tab option gives a choice of "None" of using a model. I was wondering if the same option could be given for the 1st Tab? The reason I ask is because sometimes I want to disable body recognition, or head recognition. I know you can simply turn off the 2nd Tab and then use the model you want to prioritize in the 1st Tab. But I have to keep re-dialing the settings, since there is no way to swap the slider values between tabs (like you can for example when doing XYZ plots).

It would also be useful because I can't think of many instances where I would want the Body recognition to run 2nd, while the Face recognition to run 1st.

I'm on vlad's fork of WebUI btw if that makes a difference.

**Comment by Bing-su** [comment]
Possible. However, I removed it because there are users who said that adetailer didn't work after setting all models to 'None'...

**Comment by huyzer** [comment]
It seems to me that if you use X/Y/Z plot, anything after "None" doesn't work.  For instance:

o = works
x = does not work

o, o, "None", x, x, x
"None", x, x, x
o, o, o, o, o, "None"
