### ISSUE TITLE
[Feature Request]: Option to limit how many objects to detect

### ISSUE THREAD

**Issue by adde88** [Bing-su/adetailer#682]
### Is your feature request related to a problem? Please describe.

Relatively often i'm troubled with Adetailer miss identifying things for what it actually is.
For example if i generate an image, and i know that there is only supposed to be two hands on this exact image, or another one where there's supposed to be only one visible foot.

### Describe the solution you'd like

An option to limit how many objects it should detect. For example after finding two hands, or one foot as i mentioned above, it would then stop searching. I'm guessing it would be good to chose the object with highest probability the be the object it's looking for.

**Comment by Bing-su** [comment]
In fact, there is already a feature to limit the masks to the largest k masks, or something like the [SEP] syntax, and I would recommend turning off adetailer and inpainting directly if you know where to inpaint.

**Comment by adde88** [comment]
Ohh, i was not aware of that. Thank you for the tips, i will definitely look more into what you suggested. :)
