### ISSUE TITLE
[Bug]: "Use separate checkpoint" dont work

### ISSUE THREAD

**Issue by kalle07** [Bing-su/adetailer#686]
### Describe the bug

"Use separate checkpoint" dont work

### Steps to reproduce

check the box choose another checkpoint than main.
so no checkpoint is loaded, , i dont know exactly 2-6 months ago it works

### Screenshots

![grafik](https://github.com/user-attachments/assets/6b07b703-04ac-417a-86a6-028640d0956e)

### Console logs, from start to end.

```Shell
0: 640x448 1 face, 10.2ms
Speed: 0.0ms preprocess, 10.2ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 448)
Cleanup minimal inference memory.
tiled upscale: 100%|█████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  5.23it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 17/17 [00:07<00:00,  2.22it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  1.70it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  3.37it/s]
```

**Comment by kalle07** [comment]
win10
webforge-ui
version: [f2.0.1v1.10.1-previous-250-g3589b57ec](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/3589b57ec1f59fd7c570b08c85e0108cf3ff67d6)

adtetailer: [a7d96113](https://github.com/Bing-su/adetailer/commit/a7d961131e879ea8a930034a21a2dee21b173e8c)

**Comment by kalle07** [comment]
i use webforge (i dont see any "get_ad_model")  ;)
all other is working 
separate steps
separate width/hight


but all in all webforge seems working not very clean ... may you have noticed all extensions not working
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/888
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1053

**Comment by Bing-su** [comment]
It still works fine in webui 1.10.1. Probably an issue on the forge side.

**Comment by Paharven-Salin** [comment]
Same issue for me. Latest updated commit, the separate checkpoint function in adetailer goes through the motions but nothing happens. I will try 1.10.1, thanks
