### ISSUE TITLE
[Bug]: Million faces, it's not working.

### ISSUE THREAD

**Issue by AdamKnappZ** [Bing-su/adetailer#687]
### Describe the bug

Hi! 
I'm using stable diffusion locally, i installed the extension and i dont know, but it's not working properly. 
I added a screenshot to the post so you can see what's going on.

### Steps to reproduce

a

### Screenshots

![Captura de pantalla 2024-08-17 193723](https://github.com/user-attachments/assets/ea39ac08-78c1-49b5-a9dd-5c242f1f1b93)

### Console logs, from start to end.

```Shell
a
```

### List of installed extensions

a

**Comment by solss-bit** [comment]
After I updated pytorch to 2.4 12.4 cuda, I had this issue, went back to 2.3.1 12.1 and the issue went away.

**Comment by Bing-su** [comment]
I tested it a lot on pytorch 2.4cu124 and it worked fine.

If anyone else reports on this, please include the nvidia driver version along with the pytorch version.

**Comment by Bing-su** [comment]
This issue appears to be with pytorch 2.4.0 when inferencing with CPU.

https://github.com/ultralytics/ultralytics/issues/15049

Until 2.4.1 is released, please use version 2.3.1.
