### ISSUE TITLE
[Feature Request]: in inpainting and use separate checkpoint, the possibility to choose flux models

### ISSUE THREAD

**Issue by ivaxsirc** [Bing-su/adetailer#703]
### Is your feature request related to a problem? Please describe.

Not accept a separate checkpoint model flux

### Describe the solution you'd like

support model fux into a separate checkpoint, add new options not only the vae and checkpoint

**Comment by kalle07** [comment]
same with normal img generation
you can choose a new checkpoint and vae and mark the checkbox
but it dont work
no error message! 
eg it recognize the face and generate some steps but the image is the same like before
