### ISSUE TITLE
[Feature Request]: hires 사용시 디테일러 업스케일러만 변경할수있는 기능

### ISSUE THREAD

**Issue by kakaruYH03** [Bing-su/adetailer#711]
### Describe the solution you'd like

hires 사용시 업스케일링후 -> 디테일러 적용이 되는걸로아는데
hires 강도 0.2, swinlr_4x -> 디테일러 적용을

디테일러 인페이팅 설정에 [별도의 샘플러 사용] 같은 항목 추가로
hires 강도 0.2, swinlr_4x  -> 얼굴 영역만 hires 강도 0.4, Latent -> 디테일러 적용 할수 있는 기능 추가가 가능할까요?
_No response_

### Additional context
<img width="639" alt="1543" src="https://github.com/user-attachments/assets/38dad305-7d9a-4362-b57b-c949e5b3422d">

**Comment by Bing-su** [comment]
한번 알아볼게요
