### ISSUE TITLE
[Feature Request]: Distilled CFG in Forge (Flux)

### ISSUE THREAD

**Issue by Jonseed** [Bing-su/adetailer#713]
### Is your feature request related to a problem? Please describe.

You can't properly use adetailer in Forge with Flux, because distilled CFG setting is missing. It seems to default to 3.5, but there is no way to adjust it.

### Describe the solution you'd like

Add distilled CFG setting to adetailer when using Forge (Flux).

### Describe alternatives you've considered

Settle for 3.5, or change the default somewhere. Not sure where (I tried ui-config.json, but that didn't change it when adetailer ran).

**Comment by Bing-su** [comment]
I can't add features that are only possible in forge. If automatic1111 adds flux support, I'll consider it.
