### ISSUE TITLE
[Bug]: It detects a large number of nonexistent faces.

### ISSUE THREAD

**Issue by No-Kan** [Bing-su/adetailer#718]
### Describe the bug

Suddenly we had a large number of false positives, as shown in the following image.
I thought it was a bug, so I uninstalled it, but it didn't change.
I have no idea what the cause is and I need help!
突然、以下の画像のような大量の誤検知が発生するようになりました。
バグかと思ってアンインストールしましたが、変わりませんでした。
原因がさっぱりなので、助けてほしいです！

### Screenshots

![ダウンロード (1)](https://github.com/user-attachments/assets/2408b618-f21f-4934-b2f3-c2adbb4f6692)
![ダウンロード](https://github.com/user-attachments/assets/ff6b1cff-eb69-4847-8474-a0998c68f3f9)

### Console logs, from start to end.

```Shell
0: 640x448 300 faces, 838.8ms
```

**Comment by No-Kan** [comment]
Sorry... I've solved myself.
The cause was that I was using “--medvram-sdxl”, and it worked fine when I started without it.
However, it is not a fundamental solution, so I would like it to be OK even if “--medvram-sdxl” is used.

**Comment by Bing-su** [comment]
Windowsで、pytorch 2.4.0バージョンを使っていて、cpuで推論するときにこの問題が発生します。 pytorchのバージョンを変更してください。
https://github.com/Bing-su/adetailer/issues/693

**Comment by No-Kan** [comment]
I reverted Pytorch back to 2.1.2 and the bug didn't occur when using medvram-sdxl.
If the bug is caused by Pytorch 2.4.0, I hope it will be fixed.
Thanks to you for letting me know!
Pytorchを2.1.2に戻したらmedvram-sdxlを使用してもバグが発生しませんでした。
Pytorch2.4.0に起因するバグなら、修正されることを願います。
教えてくれたあなたに感謝を！
