### ISSUE TITLE
con't work with contronnet

### ISSUE THREAD

**Issue by minaco101** [Bing-su/adetailer#72]
I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?

**Comment by alenknight** [comment]
I'm having this issue now too. odd cause it worked fine yesterday.....with control net.

**Comment by alenknight** [comment]
> I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?

i just noticed.... for me it's happening when i'm using the reference mode in ControlNet.  you?  others work... it' sjust Reference where it's happening.

**Comment by minaco101** [comment]
> > I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?
> 
> i just noticed.... for me it's happening when i'm using the reference mode in ControlNet. you? others work... it' sjust Reference where it's happening.

all the controlnet model can't work well，when i use controlnet the pic just become mosaic

**Comment by Smiley710** [comment]
> > > I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?
> > 
> > 
> > i just noticed.... for me it's happening when i'm using the reference mode in ControlNet. you? others work... it' sjust Reference where it's happening.
> 
> all the controlnet model can't work well，when i use controlnet the pic just become mosaic

Hi all, I'm having the same issue.
I have also tried the combination of openpose and reference, but I have the same issue.

I have tried the following workaround, but another problem occurs.

When I try to generate images by applying the "inpainting model" currently available from the "ControlNet model" item at the bottom of the page, the first image is output correctly, but after the second image, a black image is output.
In addition, the following error message is displayed.
ADetailer: nothing detected on image [current number of output images] with 1st setting.

I am using automatic translation, thanks.

**Comment by alenknight** [comment]
> > > I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?
> > 
> > 
> > i just noticed.... for me it's happening when i'm using the reference mode in ControlNet. you? others work... it' sjust Reference where it's happening.
> 
> all the controlnet model can't work well，when i use controlnet the pic just become mosaic

i think try controlnet version 1c994ff4f757d3d40e24d0ca367c1dfb9c717107.
- go into the controlnet folder.  type cmd at the top... then "git checkout 1c994ff4f757d3d40e24d0ca367c1dfb9c717107"
- restart SD.  
that version of controlnet is 2 days old.

i found it works with ADetailer and controlnet... but it fails with SAG.... (when using Reference).  still ... better than this issue where NOTHING works.

**Comment by minaco101** [comment]
> > > > 我试过使用 hed 或 tile 模型。只要勾选了Controlnet，Detailer处理的部分就变成了没有图像本身正确信息的马赛克。是设置问题还是插件与 Controlnet 不兼容？
> > > 
> > > 
> > > 我刚刚注意到....对我来说，当我在 ControlNet 中使用参考模式时，它就会发生。你？其他人工作......它只是参考发生的地方。
> > 
> > 
> > 所有的 controlnet 模型都不能很好地工作，当我使用 controlnet 时，图片就会变成马赛克
> 
> 大家好，我有同样的问题。 我也尝试过结合使用 openpose 和 reference，但我遇到了同样的问题。
> 
> 我尝试了以下解决方法，但出现了另一个问题。
> 
> 当我尝试通过应用页面底部“ControlNet 模型”项中当前可用的“修复模型”来生成图像时，第一张图像正确输出，但在第二张图像之后输出黑色图像。 此外，还会显示以下错误消息。 ADetailer：在第一个设置的图像 [当前输出图像数] 上未检测到任何内容。
> 
> 我正在使用自动翻译，谢谢。

My After Detailer plugin has been unable to display models in the control net model, and only the control net plugin itself can display them normally. However, after selecting enable with the control net plugin, any model cannot be used properly. After enabling control net, the part processed by After Detailer is like a mosaic.

**Comment by Bing-su** [comment]
I failed to reproduce the mosaic issue you told about, and instead found something else issue, and I still don't know what's causing it.

**Comment by minaco101** [comment]
> > > > I have tried using the hed or tile model. As long as Controlnet is checked, the part processed by the Detailer becomes a mosaic without the correct information of the image itself. Is it a setup issue or does the plugin not work well with Controlnet?
> > > 
> > > 
> > > i just noticed.... for me it's happening when i'm using the reference mode in ControlNet. you? others work... it' sjust Reference where it's happening.
> > 
> > 
> > all the controlnet model can't work well，when i use controlnet the pic just become mosaic
> 
> i think try controlnet version 1c994ff4f757d3d40e24d0ca367c1dfb9c717107.
> 
> * go into the controlnet folder.  type cmd at the top... then "git checkout 1c994ff4f757d3d40e24d0ca367c1dfb9c717107"
> * restart SD.
>   that version of controlnet is 2 days old.
> 
> i found it works with ADetailer and controlnet... but it fails with SAG.... (when using Reference). still ... better than this issue where NOTHING works.

thanks，I tried this controlnet version，really work！

**Comment by alenknight** [comment]
> I failed to reproduce the mosaic issue you told about, and instead found something else issue, and I still don't know what's causing it.

Thanks for looking at it. You tried using reference only mode with pixel perfect on and latest version of controlnet?

**Comment by alenknight** [comment]
a few other notes - i tried disabling all optimizations and using full precision...
in the latest build of controlnet - the error has changed .... 
now ADetailer works... lol.  controlnet doesn't 
might be the order they running in?  i'll opne a ticket to controlnet too... cause they changing stuff keeps adjusting the Adetailer interaction... 

but disabling optimizations doesn't work.  
also now it's no longer a mosaic.  just flat out won't work.  

getting this error
```
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 51, in unmark_prompt_context
    assert prompt_context_is_marked(x), 'ControlNet Error: Failed to detect whether an instance is cond or uncond!'
AssertionError: ControlNet Error: Failed to detect whether an instance is cond or uncond!
```

**Comment by Bing-su** [comment]
Please check if you are still having the same issue after today's update.

**Comment by Antigone84** [comment]
It is now working for me after update.

**Comment by Smiley710** [comment]
me too.
thank you everyone!

**Comment by alenknight** [comment]
me too!!!  yay!  yeah it works just fine now . with Reference mode as well!  thanks!

**Comment by Oceanswave** [comment]
Still getting this in a batch
![Screenshot 2023-05-23 at 11 33 59 PM](https://github.com/Bing-su/adetailer/assets/760674/4c0b6649-cbdb-4c45-a8b6-88cf9139a76b)

**Comment by alenknight** [comment]
> Still getting this in a batch with controlnet ![Screenshot 2023-05-23 at 11 33 59 PM](https://user-images.githubusercontent.com/760674/240480059-4c0b6649-cbdb-4c45-a8b6-88cf9139a76b.png)

yeah me too. i found as a workaround - do them without controlnet... then dump the folder path in batch img2img... and reduce noise to zero... but let the adetailer use it's own noise... produces same results.

**Comment by Oceanswave** [comment]
I can happily confirm that this issue is fixed! Thank you so much!

**Comment by alenknight** [comment]
yep.  Bing-Su the hero!  fixed a few days ago.  I had a separate ticket out for this, and I closed it there..  awesome work
