### ISSUE TITLE
[Bug]: generate white image with directml + fp16

### ISSUE THREAD

**Issue by ChiaYen-Kan** [Bing-su/adetailer#722]
### Describe the bug

i use [SD.Next](https://github.com/vladmandic/automatic)
adetailer version is v24.8.0
when use directml + fp16 to fix face is generate white image
but use directml + fp32 is ok
i test the v24.9.0, but is also generate white image

### Screenshots

fp16
![fp16-20240917201107-ad-before](https://github.com/user-attachments/assets/8178d91a-47cb-4897-85df-93c01216c1ca)
![fp16-20240917201107](https://github.com/user-attachments/assets/f5729277-2bf6-48aa-b606-d64aa9586499)

fp32
![fp32-20240917195751-ad-before](https://github.com/user-attachments/assets/18bc0242-60c3-4881-bf28-c915b05b24f4)
![fp32-20240917195752](https://github.com/user-attachments/assets/db2e0699-4423-41d1-ab60-20b5aaa1c380)

### Console logs, from start to end.

fp16 log
[fp16.txt](https://github.com/user-attachments/files/17052431/fp16.txt)

fp32 log
[fp32.txt](https://github.com/user-attachments/files/17052434/fp32.txt)

```
Platform:
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD (amd ryzen 5 5600g without other gpu)
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.11.9
torch: 2.3.1
```

**Comment by Bing-su** [comment]
Adetailer generates the mask, and requests inpainting back to the backend. These hardware-specific issues are specific to that backend, and not something I can fix.
