### ISSUE TITLE
[Feature Request]: Option to have "Save images before ADetailer" checkbox in main ADetailer box.

### ISSUE THREAD

**Issue by NemukaPrime** [Bing-su/adetailer#726]
### Is your feature request related to a problem? Please describe.

Sometimes, certain checkpoints respond better than others, so I'd like to see the images before ADetailer processing for comparison. Add the extra variable of LoRAs and I toggle that setting a lot.

I tend to toggle that setting quite a bit when changing or comparing checkpoints.

### Describe the solution you'd like

It'd be convenient to have the option of having that checkbox in the main ADetailer box. I think it should be an option in case some people get bothered with it in their workflow or flat out don't need it.

### Describe alternatives you've considered

Just going into the settings every time I want to toggle it, or not bothering with it at all and just let the enabled components generate the images, which isn't convenient.

### Additional context

I'm on Forge WebUI ~~using the integrated ADetailer~~. Thanks.

**Comment by Woisek** [comment]
Why don't you just put it into the quick settings ... ? 🤷‍♂️
