### ISSUE TITLE
Desaturated faces and visible masking

### ISSUE THREAD

**Issue by danielos123ssa** [Bing-su/adetailer#73]
![image](https://github.com/Bing-su/adetailer/assets/67702499/78feb87b-509c-42a1-884c-d8e07c5be6c9)
you can see a grey tinted square around the face, especially visible around the right shoulder, I am using default settings of adetailer, so I am sorry if this is just a bad use case on my part this is the image before:
![image](https://github.com/Bing-su/adetailer/assets/67702499/0d9aaed8-eeec-407c-840e-e88f60d66f8b)
changing inpainting settings a little hasn't produced any different results, also changing models either.

**Comment by Bing-su** [comment]
I experience the same problem and I'm sure others do too, increasing the `inpaint at full resolution padding` may help.

**Comment by danielos123ssa** [comment]
Thank you, since it's a thing with masking settings and not a bug I will close this issue
