### ISSUE TITLE
[Feature Request]: Ip-Adapter controlnet support

### ISSUE THREAD

**Issue by merket** [Bing-su/adetailer#730]
### Is your feature request related to a problem? Please describe.

When trying to create a character grid, using ip adapters for influencing the faces with a formerly created character, adetailer totally bypasses that and makes it impossible to use ip adapters for a prompt.

### Describe the solution you'd like

ADetailer doesn't seem to support IP-Adapter controlnets, but hopefully it will in the future. It does allow changing checkpoints and even have a controlnet model input but it doesn't allow ip-adapters.
Please make it so that we can supply source images for adetailer to build on.

**Comment by Bing-su** [comment]
Well, I'm still not sure about the usefulness of other controlnet models for inpainting. 

At least the ip adapter isn't the type that uses the generated image as a control image, is it?

**Comment by lhucklen** [comment]
looks like he did something in dev branch and referenced this, I think our ideas and desires align. Hopefully, @Bing-su  has some ideas.

#701

**Comment by lhucklen** [comment]
> Well, I'm still not sure about the usefulness of other controlnet models for inpainting.
> 
> At least the ip adapter isn't the type that uses the generated image as a control image, is it?

I have played with it via pass through and it does have the desired effect at low denoise value. 

I mentioned some ideas in #701, looks like you did something in the dev section, would love to hear an elaboration on how you used that idea. have you had any chance to consider this for full main branch?
