### ISSUE TITLE
[Feature Request]: add color correction option 

### ISSUE THREAD

**Issue by Hugs288** [Bing-su/adetailer#731]
### Is your feature request related to a problem? Please describe.

running color correction on an image after adetailer makes the colors stay more true to the original image and makes the detection box much less obvious.
the webui has an option to run color correction after img2img but adetailer doesnt. it would be much more convenient if adetailer had this option natively and could just apply it after every inpaint.

here is a comparison

original image:
![image](https://github.com/user-attachments/assets/da2dbe13-35f3-43f1-a0ed-b5455c0db769)

original image after adetailer:
![image](https://github.com/user-attachments/assets/57af4de0-a0fd-4f6e-b8e4-90bf57642e39)

adetail image after color correction:
![image](https://github.com/user-attachments/assets/cb09b4a2-615e-4551-b1f3-a485494d647e)

**Comment by Bing-su** [comment]
Thank you for your request. The `img2img_color_correction` option is a global setting, and adetailer respects global settings.

**Comment by Hugs288** [comment]
oh, guess im just stupid, sorry.
