### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rubberfashion** [Bing-su/adetailer#732]
### Describe the bug

Error in using ADetailer with img2img

### Steps to reproduce

SD.Next Version 2024-10-17 + ADetailer

I ran into an error using ADetailer in img2img with face and eyes.

Error AttributeError: module 'modules.images' has no attribute 'LANCZOS'

extensions/adetailer/scripts/!adetailer.py line 655

function:

@staticmethod
    def inpaint_mask_filter(
        img2img_mask: Image.Image, ad_mask: list[Image.Image]
    ) -> list[Image.Image]:
        if ad_mask and img2img_mask.size != ad_mask[0].size:
            img2img_mask = img2img_mask.resize(ad_mask[0].size, resample=images.LANCZOS)
        return [mask for mask in ad_mask if has_intersection(img2img_mask, mask)]

I changed to (solved my problem):
@staticmethod
def inpaint_mask_filter(
    img2img_mask: Image.Image, ad_mask: list[Image.Image]
) -> list[Image.Image]:
    if ad_mask and img2img_mask.size != ad_mask[0].size:
        img2img_mask = img2img_mask.resize(ad_mask[0].size, resample=Image.LANCZOS)
    return [mask for mask in ad_mask if has_intersection(img2img_mask, mask)]

### Screenshots

-

### Console logs, from start to end.

```Shell
-
```

**Comment by rubberfashion** [comment]
Yes. this is exactly the problem, can you update the code please?

**Comment by devstein** [comment]
Hi @rubberfashion - Dosu isn't able to generate PRs, but would encourage you to do so
