### ISSUE TITLE
[Feature Request]: Default Values for ADetailer after running Stable Diffusion

### ISSUE THREAD

**Issue by Victorcorcos** [Bing-su/adetailer#734]
### Is your feature request related to a problem? Please describe.

Always when I run Stable Diffusion and use `ADetailer` to improve the face, it is required to perform the following sequence of actions before working with Stable Diffusion...

https://github.com/user-attachments/assets/226ac62d-65c0-4712-a538-8ff12c0b95f4

If it is not possible to automatize this repetitive task that is performed 100% of times when I run the Stable Diffusion, is it possible to implement it? 💡 

### Describe the solution you'd like

Is there a way to automatize it through a file for example (`defaults.json`) so we can have total freedom to provide any default value we want to these `ADetailer` checkboxes?

> [!TIP]
> Similar to the [`ui-config.json` file](https://www.reddit.com/r/StableDiffusion/comments/159k8n7/quick_tip_for_beginners_you_can_change_the/) of the *Stable Diffusion WebUI Forge*

Cheers 🤝

**Comment by Bing-su** [comment]
The stable diffusion webui already has the ability to change the defaults. 
Please see the following links
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/12278#discussioncomment-6627430
