### ISSUE TITLE
[Feature Request]: 我的sd forge版本安装了插件且重启后，并没有看到adetailer按钮。

### ISSUE THREAD

**Issue by takidla** [Bing-su/adetailer#735]
### Is your feature request related to a problem? Please describe.

如题，我已经安装了插件，如下图：
![image](https://github.com/user-attachments/assets/be1eaa3f-ed74-4e20-aa4d-be1fde943c40)
在reload了sd UI之后，在文生图界面并没有看到adetailer按钮，我是forge版本。
![image](https://github.com/user-attachments/assets/29e37b72-35b2-4bec-b0f6-992f32c81a69)
请问是不兼容forge版本吗？

**Comment by Bing-su** [comment]
请在 “报告错误 ”选项卡中张贴这些内容，并附上控制台日志
