### ISSUE TITLE
[Bug]: ADetailer locks available CPU threads to 8 after running the script once

### ISSUE THREAD

**Issue by ChiNoel-osu** [Bing-su/adetailer#747]
### Describe the bug

sd-webui is ran in CPU only mode:
```
export COMMANDLINE_ARGS="--no-download-sd-model --listen --enable-console-prompts --enable-insecure-extension-access --use-cpu all --precision autocast --no-half --skip-torch-cuda-test"
export CUDA_VISIBLE_DEVICES="-1"
export OMP_NUM_THREADS=24
export MKL_NUM_THREADS=24
```
Inference without enabling the ADetailer script will use 24 threads every time.

When ADetailer script is enabled in this session, the first pass (where it generates with original prompts and settings) of the first generated image will use 24 threads, the "ADetailer" pass (where it masks the generated image and inpaints it) will only use 8 threads. All subsequent inferences will only use 8 threads from now on, even if I disable ADetailer.

### Steps to reproduce

0. Have a CPU that has more than 8 threads
1. Launch webui in CPU only mode
2. Generate any image w/ ADetailer script
3. Observe the CPU usage during each pass

### Console logs, from start to end.

```Shell
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --no-download-sd-model --listen --enable-console-prompts --enable-insecure-extension-access --use-cpu all --precision autocast --no-half --skip-torch-cuda-test
No module 'xformers'. Proceeding without it.
Warning: caught exception 'No CUDA GPUs are available', memory monitor disabled
[-] ADetailer initialized. version: 24.11.1, num models: 10
....(Everything is normal with no exceptions)
```

### List of installed extensions

adetailer
tagcomplete
dynamic prompt
controlnet
webui-state

**Comment by Bing-su** [comment]
This is a problem I never imagined. Please let me know what hardware and software version you're using and I'll give it a try.

Also, since there was a supply chain attack on the ultralytics package, please make sure you're not using version 8.3.41 of ultralytics.

**Comment by ChiNoel-osu** [comment]
Using the latest version of both SDWebUI (82a973c) and adetailer (v24.11.1).
The CPU is a Intel Xeon w7-3455 (24C48T), but I think any CPU with more than 8 cores should be able to replicate this problem.

ultralytics               8.3.19
ultralytics-thop          2.0.9
