### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'package'

### ISSUE THREAD

**Issue by wanlic1017** [Bing-su/adetailer#751]
### Describe the bug

Hi there,

Was running the addetailer but it doesn't seem to work.

### Steps to reproduce

Generated image with stable diffusion.

Here's what it says:

   ADetailer                                                     │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃                     ┃ Value                                                                                  ┃ │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │             version │ 24.11.1                                                                                │ │
    │ │            ad_model │ face_yolov8n.pt                                                                        │ │
    │ │           ad_prompt │ (best quality, masterpiece:1.2, photo realistic:1.4), (finely detailed beautiful eyes  │ │
    │ │                     │ and detailed face), (detailed face), (smile:0.6), happy, detailed texture, finely      │ │
    │ │                     │ detailed, high detail, extremely detailed cg, <lora:chinaDollLikeness_v10:0.66>        │ │
    │ │  ad_negative_prompt │ paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres,   │ │
    │ │                     │ normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age  │ │
    │ │                     │ spot, glans, nsfw, bad anatomy,                                                        │ │
    │ │ ad_controlnet_model │ None                                                                                   │ │
    │ │              is_api │ False                                                                                  │ │
    │ └─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────┘ │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\aaaaaa\traceback.py:153 in       │             │
    │ │ wrapper                                                                                          │             │
    │ │                                                                                                  │             │
    │ │   152 │   │   try:                                                                               │             │
    │ │ ❱ 153 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   154 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:916 in     │             │
    │ │ postprocess_image                                                                                │             │
    │ │                                                                                                  │             │
    │ │    915 │   │   │   │   │   continue                                                              │             │
    │ │ ❱  916 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
    │ │    917                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py:830 in     │             │
    │ │ _postprocess_image_inner                                                                         │             │
    │ │                                                                                                  │             │
    │ │    829 │   │   │   │   ad_model = self.get_ad_model(args.ad_model)                               │             │
    │ │ ❱  830 │   │   │   │   pred = ultralytics_predict(                                               │             │
    │ │    831 │   │   │   │   │   ad_model,                                                             │             │
    │ │                                                                                                  │             │
    │ │ C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\adetailer\ultralytics.py:25 in   │             │
    │ │ ultralytics_predict                                                                              │             │
    │ │                                                                                                  │             │
    │ │   24 ) -> PredictOutput[float]:                                                                  │             │
    │ │ ❱ 25 │   from ultralytics import YOLO                                                            │             │
    │ │   26                                                                                             │             │
    │ │                                                                                                  │             │
    │ │ C:\Users\wanli\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\__init__.py │             │
    │ │ :6 in <module>                                                                                   │             │
    │ │                                                                                                  │             │
    │ │    5 import os                                                                                   │             │
    │ │ ❱  6 import package                                                                              │             │
    │ │    7                                                                                             │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ ModuleNotFoundError: No module named 'package'                                                                   │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Help please thank you!

### Screenshots

![Screenshot 2024-12-07 223122](https://github.com/user-attachments/assets/60d0dac1-da0f-4c40-9db5-a6dec22e4845)

### Console logs, from start to end.

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Launching Web UI with arguments:
C:\Users\wanli\AppData\Local\Programs\Python\Python310\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 24.11.1, num models: 10
Loading weights [7234b76e42] from C:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\chilloutmix_Ni.safetensors
Creating model from config: C:\Stable Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860
C:\Users\wanli\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

To create a public link, set `share=True` in `launch()`.
C:\Users\wanli\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Startup time: 19.7s (prepare environment: 5.3s, import torch: 7.2s, import gradio: 2.7s, setup paths: 1.3s, initialize shared: 0.3s, other imports: 0.8s, load scripts: 1.2s, initialize extra networks: 0.2s, create ui: 0.6s, gradio launch: 0.3s).
Loading VAE weights specified in settings: C:\Stable Diffusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: Doggettx... done.
Model loaded in 6.8s (load weights from disk: 0.7s, create model: 0.6s, apply weights to model: 4.5s, apply dtype to VAE: 0.1s, load VAE: 0.5s, calculate empty prompt: 0.2s).
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:16<00:00,  1.85it/s]
*** Error running postprocess_image: C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Stable Diffusion\stable-diffusion-webui\extensions\adetailer\aaaaaa\traceback.py", line 173, in wrapper
        raise error from None
    ModuleNotFoundError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.26100-SP0                                                                      │ │
    │ │      Python │ 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]               │ │
    │ │     Version │ v1.10.1                                                                                        │ │
    │ │      Commit │ 82a973c04367123ae98bd9abdf80d9eda9b910e2                                                       │ │
    │ │ Commandline │ ['C:\\Stable Diffusion\\stable-diffusion-webui\\launch.py']                                    │ │
    │ │   Libraries │ {'torch': '2.1.2+cu121', 'torchvision': '0.16.2+cu121', 'ultralytics': '8.3.46', 'mediapipe':  │ │
    │ │             │ '0.10.14'}                                                                                     │ │
```

### List of installed extensions

Ad detailer only.

**Comment by JasonWenTheFox** [comment]
I have encountered and resolved the same issue. Based on the error you're experiencing, it appears to be caused by 'ultralytics': '8.3.46'. If you've been following recent news, you might be aware that **ultralytics has been compromised** in the past week as discussed in this GitHub issue: [ultralytics/ultralytics#18086](https://github.com/ultralytics/ultralytics/issues/18086). Starting from version 8.3.41, malicious code has been inserted to use machines for cryptocurrency mining, which affects Linux and Mac systems, while Windows systems do not execute the mining but may report errors. Regardless, **please uninstall or reinstall any version of ultralytics above 8.3.40**. This is a Python package related to YOLOv11. Uninstalling or downgrading 'adetailer' does not effectively remove the malicious code. It is imperative to uninstall the 8.3.46 version of ultralytics and revert to version 8.3.40 to ensure normal operation. This update issue arises from the automatic acquisition of the latest ultralytics during upgrades or reinstallation of the 'adetailer' program.

**I kindly request the developers to take note of this issue and patch the relevant vulnerabilities.**
我遇到了同样的问题，而且已经解决。看你的报错，这是'ultralytics': '8.3.46'导致的，如果你关注最近的新闻就会知道ultralytics最近一周被人下毒了 https://github.com/ultralytics/ultralytics/issues/18086 ，8.3.41版本开始就被加入恶意代码使用你的机器挖矿（虚拟货币），但是这个行为只会在Linux和Mac系统上，Windows不起作用，但是会报错。但无论如何都请把大于8.3.40版本的ultralytics卸载或者重装，这是一个yolo11的Python包，卸载或者降级adetailer不能有效清除恶意代码，请务必卸载8.3.46版本的ultralytics，更换为8.3.40的就可以正常运行了。出现这个更新是你升级或者重新安装adetailer程序自动获取最新的ultralytics导致的。
请作者注意到这个问题修补相关漏洞。

**Comment by jtran-developer** [comment]
I am getting the same error.  I understand that the latest version of ultralytics has been compromised, so I downgraded to 8.3.40 using the command, "pip install ultralytics==8.3.40".  It now shows it as 8.3.40 when I do "pip list".  However, I am still getting the same "ModuleNotFoundError: No module named 'package'" error message as before.

**Comment by rinkis6** [comment]
> I am getting the same error. I understand that the latest version of ultralytics has been compromised, so I downgraded to 8.3.40 using the command, "pip install ultralytics==8.3.40". It now shows it as 8.3.40 when I do "pip list". However, I am still getting the same "ModuleNotFoundError: No module named 'package'" error message as before.
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
In your opinion, I tried.
I downloaded the latest adetailer, deleted the original ultralytics, and downloaded the .40 version of the ultralytics. As a result, I reworked.

**Comment by jtran-developer** [comment]
Ok, it works for me now.  After downgrading to ultralytics 8.3.40, I also have to to remove adetailer and reinstall it to get it to work.  Thank you.

**Comment by wanlic1017** [comment]
Thank you, working now, really appreciate the support!
