### ISSUE TITLE
[Feature Request]: output the left/right label for hand detection results

### ISSUE THREAD

**Issue by weidong-z** [Bing-su/adetailer#758]
### Describe the solution you'd like

is it possible to give the left/right label when using yolo hand detection?

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the ultralytics_predict function to include left/right labels for hand detection. This change will determine the hand orientation based on the x-coordinate of the bounding box center relative to the image width.

You can review changes in this commit: https://github.com/jack-samo10000/Bing-su-adetailer-758/commit/e1f89a99db9af062f2ecdf44fc9e34bad112887e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by weidong-z** [comment]
Thanks very much!, it works

> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modify the ultralytics_predict function to include left/right labels for hand detection. This change will determine the hand orientation based on the x-coordinate of the bounding box center relative to the image width.
> 
> You can review changes in this commit: [jack-samo10000@e1f89a9](https://github.com/jack-samo10000/Bing-su-adetailer-758/commit/e1f89a99db9af062f2ecdf44fc9e34bad112887e).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
