### ISSUE TITLE
Adetailer preventing SD from reloading or loading (Win11)

### ISSUE THREAD

**Issue by GuruVirus** [Bing-su/adetailer#8]
I installed the git through A1111's extension tab, click reload, the CMD output hung at "Restarting WebUI". I left it for a few hours before forcing it close.

When running webui-user.bat it hangs at:
 warnings.warn(

I deleted the extension folder then ran it again and I'm back to normal. I noticed the next line for me would normally be:
ControlNet v1.1.133

So maybe there's a conflict with ControlNet?

**Comment by Bing-su** [comment]
I've been hearing about this issue in the community since it was first released, but I don't know anything about it - I've heard it on various versions of python and torch. sorry.

**Comment by GuruVirus** [comment]
I got it to load on a fresh install with no other extensions.
Then I installed Mikubil's ControlNet extension and it did load.
Must have been the Auto1111 commit I was using from around the 21st.
