### ISSUE TITLE
How to maintain facial expressions when redrawing?

### ISSUE THREAD

**Issue by minaco101** [Bing-su/adetailer#80]
When redrawing the face, Lora was given the definition of a beautiful face, but after redrawing, it becomes a beautiful face with no expression. How can we maintain the expression of the original image when redrawing the face?

I tried to combine the face and faceonly preprocessors of openpose with Controlnet, but there were no significant changes~

**Comment by WesleyNery** [comment]
I guess you have to separate it and input on the positive prompt option on Adetailer.
