### ISSUE TITLE
All Yolov8 models Support & Img2Img,Inpainting

### ISSUE THREAD

**Issue by FlowDownTheRiver** [Bing-su/adetailer#82]
How can we add all v8 models officially released?
![2023-05-23 22_38_34-Window](https://github.com/Bing-su/adetailer/assets/71787427/2f341634-2203-4d98-b0db-92e4b7bd13ed)

I have manually downloaded some models and put them in here,they were not detected by the extension. Can you add support for the other models? 

Edit : Sorry,I missed the part that you have written : 

"User Model

Put your [ultralytics](https://github.com/ultralytics/ultralytics) model in webui/models/adetailer. The model name should end with .pt or .pth.

It must be a bbox detection or segment model and use all label. "

Suggestion : Instead of using the  .cache\huggingface\hub\models--Bingsu--adetailer\snapshots\403e56c1b291da2145da824f3f whatever path for the models,can you add models folder in the extension directory,so the script can read the files from there?

Edit : Again I missed the instructions.

Another question is :
"Inpainting conditioning mask strength" is a viable option for controlnet inpainting model? If so,can you expose the parameter and add to the extension UI?

Can we also have img2img and inpainting tabs support?

And thanks for the great extension and amazing work.

**Comment by Bing-su** [comment]
I'll look into it.
