### ISSUE TITLE
hands on  face

### ISSUE THREAD

**Issue by osmania101** [Bing-su/adetailer#83]
I simply wanted to alter the facial appearance, and this extension has proven to be quite helpful. I have encountered a significant obstacle, but I am hopeful that it will be resolved. It may pose a challenge to change only the face. Is there a method specifically for altering the face without affecting other aspects?

not only one single image but a batch

**Comment by Bing-su** [comment]
For now, the only way to do this is to set the denoising to 0.0 and do img2img. it works in batches too.
