### ISSUE TITLE
How to? Batch  processing as in "Batch Face Swap" extension

### ISSUE THREAD

**Issue by Maelstrom2014** [Bing-su/adetailer#85]
1) Can't understand how to make batch processing similar "Batch Face Swap" . W/o processing full size input image, just face? 

2) Is any option to use not rectangle mask? face shape?

**Comment by Bing-su** [comment]
1. For now, the only way to do this is to set the denoising to 0.0 and do img2img.
2. No

**Comment by ManuelMultiverse** [comment]
> 1. For now, the only way to do this is to set the denoising to 0.0 and do img2img.
> 2. No

Would be that possible making a mask in another software of just the face and use in inpaint folder, and then use inpaint only masked + One controlnet?
