### ISSUE TITLE
Faces are awesome but ... hands

### ISSUE THREAD

**Issue by enzyme69** [Bing-su/adetailer#88]
I am curious if we could actually target detailed hands, because so far, I could get the face looking really great, but hands are making me sad.
![Screenshot 2023-05-25 at 7 21 06 am](https://github.com/Bing-su/adetailer/assets/3952687/496c883b-de69-40bf-b46a-b65335bc5bb2)
52ae3a19-fd26-4dc0-9090-c35e2eedcb29)

**Comment by Bing-su** [comment]
Hands are really hard...

**Comment by GuruVirus** [comment]
Sure, but 1) are hands being targeted and 2) what hand prompts actually do anything for hands (is it model specific)? Most of the time my adetailer passes on hands, doing nothing with the hands model selected.

**Comment by Raivshard** [comment]
This. If it improved existing hands, great. But it doesn't. Sometimes it does, but usually it just returns a featureless blob of blurry flesh. Controlnet can place hands. Shouldn't this be able to improve them?
