### ISSUE TITLE
마지막 커밋때문에 항상 Adetailer 가 적용되는 문제가 있습니다.

### ISSUE THREAD

**Issue by rubyon** [Bing-su/adetailer#9]
안녕하세요 프롬프츠 운영자 입니다.

마지막 커밋을 보니 디폴트 모델 값을 "None" 에서 모델 배열 첫번째 것으로 가져오는 것으로 바꾸었는데

이로인해 API 를 이용한 모든 이미지 생성시 Adetailer 가 적용되더라고요... 그래서 쭉 지켜본결과...

ㅠㅠ

Adetailer 체크박스를 해제 했음에도 불구하고 무조건 적용되는거 같아 보입니다.

기존에는 무조건 적용되더라도 기본 모델이 "None" 이어서 바이패스 된거같아 보입니다.

현재 마지막 커밋중 디폴트 모델 선택하는 부분만 급하게 수정해서 사용중인데 확인해 주셨으면 해서 글 남겨봅니다.

**Comment by Bing-su** [comment]
분명 테스트할땐 문제가 없었는데, 왜 체크박스가 무시되는지 모르겠네요... `None`을 부활시켰습니다.
