### ISSUE TITLE
How to make the ControlNet model in After Detailer optional?

### ISSUE THREAD

**Issue by minaco101** [Bing-su/adetailer#90]
I am unable to find any models in the ControlNet model in After Detailer, as it is empty. I have installed Controlnet and can use it normally, but I cannot read any models in the ControlNet model in After Detailer. Do you need to put any special paths in it?

![微信截图_20230525120946](https://github.com/Bing-su/adetailer/assets/75287160/cea878e0-6d25-45d7-aff6-ad934e15a108)

Controlnet outside of After Detailer is normal

![微信截图_20230525121254](https://github.com/Bing-su/adetailer/assets/75287160/65ae965a-8d45-450b-a576-75be966c0e03)

I believe that Controlnet outside of After Detailer can only control the overall imgtoimg content and cannot control the content during additional redrawing of After Detailer. Therefore, how can we read the Controlnet model in After Detailer?

**Comment by Bing-su** [comment]
Only ControlNet models with `inpaint` in their name are displayed.

**Comment by Thetinsnail** [comment]
I also have this problem, but I have inpaint controlnet models installed.

**Comment by Natotela** [comment]
I'm also wondering how to use the inpaint models ControlNet
especially since it seems like my OpenPose (via regular controlnet addon) is not making any effect

**Comment by MIDG3Tp3nguin** [comment]
Do the models need to be in any particular folder? ?Or just the default model for Controlnet?
