### ISSUE TITLE
API (adetailer + controlnet) is slower than webUI

### ISSUE THREAD

**Issue by djkim-gogo** [Bing-su/adetailer#91]
Thank you for this great extension. i love it!

When i test adetailer + controlnet(openpose) in Automatic1111 webUI, it works perfect.
When i try API call it works well but 30% slower.
According to the logs, it looks like controlnet is called in each adetailer call.
When called via webUI, controlnet is loaded once.
But when called via API, controlnet is loaded multiple times as the number of batch size.
I guess this multiple controlnet loading can affect slow performance in API call.

Belows are console log in Automatic1111.

**Called via webUI (batch size: 3)** 

        Loading model from cache: control_sd15_openpose [fef5e48e]
        Loading preprocessor: openpose
        preprocessor resolution = 512
        100%|████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.54it/s]
        Total progress: 100%|██████████████████████████████████████████| 20/20 [00:03<00:00,  5.55it/s]
        0: 640x640 1 face, 11.2ms
        Speed: 4.1ms preprocess, 11.2ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)
        100%|████████████████████████████████████████████████████| 9/9 [00:00<00:00, 14.19it/s]
        Total progress: 29it [00:04, 10.25it/s]                                                                                                   
        0: 640x640 1 face, 3.9ms
        Speed: 1.7ms preprocess, 3.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
        100%|████████████████████████████████████████████████████| 9/9 [00:00<00:00, 15.19it/s]
        Total progress: 37it [00:05, 10.48it/s]
        0: 640x640 1 face, 4.5ms
        Speed: 1.7ms preprocess, 4.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
        100%|████████████████████████████████████████████████████| 9/9 [00:00<00:00, 15.24it/s]
        Total progress: 47it [00:06,  6.74it/s]
        Total progress: 47it [00:06, 11.69it/s]

 **Called via API**

We can see multiple logs "Loading model from cache: control_sd15_openpose [fef5e48e]"

    payload = {
        "prompt": "a boy", 
        "width": 512, 
        "height": 512, 
        "steps": 20,
        "batch_size": 3,
        "sampler_name": "Euler a",
        "alwayson_scripts": {
          "After Detailer": {
            "args": [
              {
                "ad_model": "face_yolov8n.pt",
                "ad_prompt": "a boy",
                "ad_controlnet_model": "control_sd15_openpose [fef5e48e]",
                "ad_controlnet_weight": 0.3
              }
            ]
          },
          "controlnet": {
            "args": [
              {
                "input_image": encoded_image,
                "module": "openpose",
                "model": "control_sd15_openpose [fef5e48e]",
                "weight": 0.3
              }
            ]
          }
        }
    }

          Loading model from cache: control_sd15_openpose [fef5e48e]
          Loading preprocessor: openpose
          preprocessor resolution = 512
          100%|█████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.60it/s]
          Total progress: 100%|███████████████████████████████████████| 20/20 [00:03<00:00,  5.63it/s]
          0: 640x640 1 face, 10.3ms
          Speed: 4.5ms preprocess, 10.3ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 640)
          Loading model from cache: control_sd15_openpose [fef5e48e]
          Loading preprocessor: inpaint
          Pixel Perfect Mode Enabled.
          resize_mode = ResizeMode.RESIZE
          raw_H = 512
          raw_W = 512
          target_H = 512
          target_W = 512
          estimation = 512.0
          preprocessor resolution = 512
          Calling preprocessor inpaint outside of cache.
          100%|█████████████████████████████████████████████████| 9/9 [00:00<00:00, 10.20it/s]
          Total progress: 29it [00:05,  7.34it/s]                                                                                                   
          0: 640x640 1 face, 4.2ms
          Speed: 1.7ms preprocess, 4.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
          Loading model from cache: control_sd15_openpose [fef5e48e]
          Loading preprocessor: inpaint
          Pixel Perfect Mode Enabled.
          resize_mode = ResizeMode.RESIZE
          raw_H = 512
          raw_W = 512
          target_H = 512
          target_W = 512
          estimation = 512.0
          preprocessor resolution = 512
          Calling preprocessor inpaint outside of cache.
          100%|█████████████████████████████████████████████████| 9/9 [00:00<00:00, 10.87it/s]
          Total progress: 38it [00:06,  7.58it/s]
          0: 640x640 1 face, 3.6ms
          Speed: 1.7ms preprocess, 3.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)
          Loading model from cache: control_sd15_openpose [fef5e48e]
          Loading preprocessor: inpaint
          Pixel Perfect Mode Enabled.
          resize_mode = ResizeMode.RESIZE
          raw_H = 512
          raw_W = 512
          target_H = 512
          target_W = 512
          estimation = 512.0
          preprocessor resolution = 512
          Calling preprocessor inpaint outside of cache.
          100%|█████████████████████████████████████████████████| 9/9 [00:00<00:00, 10.32it/s]
          Total progress: 46it [00:08,  6.93it/s]

**Comment by djkim-gogo** [comment]
Thank you for the reply.

I tested again without "ad_controlnet_model": "ad_controlnet_weight".
The results look the same.
There are still multiple logs "Loading model from cache: control_sd15_openpose [fef5e48e]" if we use API call.

    payload = {
        "prompt": "a boy", 
        "width": 512, 
        "height": 512, 
        "steps": 20,
        "batch_size": 3,
        "sampler_name": "Euler a",
        "alwayson_scripts": {
          "After Detailer": {
            "args": [
              {
                "ad_model": "face_yolov8n.pt",
                "ad_prompt": "a boy"
              }
            ]
          },
          "controlnet": {
            "args": [
              {
                "input_image": encoded_image,
                "module": "openpose",
                "model": "control_sd15_openpose [fef5e48e]",
                "weight": 0.3
              }
            ]
          }
        }
    }


      Loading model from cache: control_sd15_openpose [fef5e48e]
      Loading preprocessor: openpose
      preprocessor resolution = 512
      100%|███████████████████████████████████████████████| 20/20 [00:03<00:00,  5.62it/s]
      Total progress: 67it [00:52,  5.24it/s]
      0: 640x640 1 face, 3.5ms
      Speed: 1.7ms preprocess, 3.5ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)
      Loading model from cache: control_sd15_openpose [fef5e48e]
      Loading preprocessor: openpose
      preprocessor resolution = 512
      Calling preprocessor openpose outside of cache.
      100%|███████████████████████████████████████████████| 9/9 [00:00<00:00, 10.50it/s]
      Total progress: 75it [00:54,  5.78it/s]
      0: 640x640 1 face, 3.5ms
      Speed: 1.6ms preprocess, 3.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)
      Loading model from cache: control_sd15_openpose [fef5e48e]
      Loading preprocessor: openpose
      preprocessor resolution = 512
      Calling preprocessor openpose outside of cache.
      100%|███████████████████████████████████████████████| 9/9 [00:00<00:00, 10.64it/s]
      Total progress: 85it [00:56,  6.20it/s]
      0: 640x640 1 face, 3.5ms
      Speed: 1.6ms preprocess, 3.5ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 640)
      Loading model from cache: control_sd15_openpose [fef5e48e]
      Loading preprocessor: openpose
      preprocessor resolution = 512
      Calling preprocessor openpose outside of cache.
      100%|███████████████████████████████████████████████| 9/9 [00:00<00:00, 10.86it/s]
      Total progress: 94it [00:59,  6.19it/s]

**Comment by Bing-su** [comment]
Fixed calling controlnet multiple times. thanks.

**Comment by djkim-gogo** [comment]
I updated adetailer to the latest version and found that it works great!
API call speed is the same as webUI now.
Thanks a ton for the fast fix!!

**Comment by J-Wu97** [comment]
> Fixed calling controlnet multiple times. thanks.

hello，the latest version v23.8.1 also found this problem.
