### ISSUE TITLE
Negative Mask?

### ISSUE THREAD

**Issue by a3nima** [Bing-su/adetailer#97]
Hi, is it possible to use the mask as a negative mask? so that img2img /inpainting does change the image except the mask?

**Comment by Bing-su** [comment]
![Cap 2023-05-28 22-25-52-257](https://github.com/Bing-su/adetailer/assets/37621276/e0aec259-cff0-4c49-a59f-49b433081763)
The `Merge and Invert` inside the mask preprocessing is what you want.
