### ISSUE TITLE
혹시 adetailer 관련 기능에 대해서 간단한 의뢰 좀 가능할까요?

### ISSUE THREAD

**Issue by DOODED** [Bing-su/adetailer#99]
제가 파이썬으로 며칠째 계속 해서 스크립트를 개조하고 있는데 안되네요 
해주시면 제가 그지라 별건 없지만 치킨 쏘겠습니다
혹시 관심있으시면 댓글로 연락해주세요

**Comment by Bing-su** [comment]
네 말씀하세요

**Comment by DOODED** [comment]
아 좋습니다 제가 요청할건 adetailer의 수치들을 xyz plot에 적용시키고 싶습니다. 예를 들어 make erosion/dilation 이나 inpaint denoising strength같은 adetailer 중요한 기능들인 변수들의 수치들을 xyzplot에 적용시켜서 생성된 그림의 변화를 비교하고 싶습니다.
그리고 xyzplot의 프롬프트 서치도 adetailer의 프롬에 적용할 수 있을까요?
 치킨은 나중에 네이버 메일에 선물코드로 보내도록 하지요 뭐 좋아하시는거라도 있나요?

**Comment by DOODED** [comment]
> 네 말씀하세요

아 좋습니다 제가 요청할건 adetailer의 수치들을 xyz plot에 적용시키고 싶습니다. 예를 들어 make erosion/dilation 이나 inpaint denoising strength같은 adetailer 중요한 기능들인 변수들의 수치들을 xyzplot에 적용시켜서 생성된 그림의 변화를 비교하고 싶습니다.
그리고 xyzplot의 프롬프트 서치도 adetailer의 프롬에 적용할 수 있을까요?
치킨은 나중에 네이버 메일에 선물코드로 보내도록 하지요 뭐 좋아하시는거라도 있나요?

**Comment by Bing-su** [comment]
해보도록 하죠.. 치킨은 필요없습니다.

**Comment by DOODED** [comment]
> 해보도록 하죠.. 치킨은 필요없습니다.

아 그러면 후원은 하겠습니다
